-- CITYOBJECT.sql
--
-- Authors:     Prof. Dr. Thomas H. Kolbe <thomas.kolbe@tum.de>
--              Zhihang Yao <zhihang.yao@tum.de>
--              Claus Nagel <cnagel@virtualcitysystems.de>
--              Philipp Willkomm <pwillkomm@moss.de>
--              Gerhard König <gerhard.koenig@tu-berlin.de>
--              Alexandra Lorenz <di.alex.lorenz@googlemail.com>
--
-- Copyright:   (c) 2012-2014  Chair of Geoinformatics,
--                             Technische Universität München, Germany
--                             http://www.gis.bv.tum.de
--
--              (c) 2007-2012  Institute for Geodesy and Geoinformation Science,
--                             Technische Universität Berlin, Germany
--                             http://www.igg.tu-berlin.de
--
--              This skript is free software under the LGPL Version 2.1.
--              See the GNU Lesser General Public License at
--              http://www.gnu.org/copyleft/lgpl.html
--              for more details.
-------------------------------------------------------------------------------
-- About:
--
--
-------------------------------------------------------------------------------
--
-- ChangeLog:
--
-- Version | Date       | Description                               | Author
-- 3.0.0     2013-12-06   new version for 3DCityDB V3                 ZYao
--                                                                    TKol
--                                                                    CNag
--                                                                    PWil
-- 2.0.0     2007-11-23   release version                             TKol
--                                                                    GKoe
--                                                                    CNag
--                                                                    ALor
--
--//ADDRESS_TO_BUILDING CONSTRAINTS

ALTER TABLE ADDRESS_TO_BUILDING
ADD CONSTRAINT ADDRESS_TO_BUILDING_FK FOREIGN KEY (BUILDING_ID)
REFERENCES BUILDING (ID) ENABLE;

ALTER TABLE ADDRESS_TO_BUILDING
ADD CONSTRAINT ADDRESS_TO_BUILDING_ADDRESS_FK FOREIGN KEY (ADDRESS_ID)
REFERENCES ADDRESS (ID) ENABLE;

--// ADDRESS_TO_BRIDGE CONSTRAINT

ALTER TABLE ADDRESS_TO_BRIDGE
ADD CONSTRAINT ADDRESS_TO_BRIDGE_ADDRESS_FK FOREIGN KEY (ADDRESS_ID)
REFERENCES ADDRESS (ID) ENABLE;

ALTER TABLE ADDRESS_TO_BRIDGE
ADD CONSTRAINT ADDRESS_TO_BRIDGE_FK FOREIGN KEY (BIRDGE_ID)
REFERENCES BRIDGE (ID) ENABLE;


--//APPEARANCE CONSTRAINTS

ALTER TABLE APPEARANCE
ADD CONSTRAINT APPEARANCE_CITYMODEL_FK FOREIGN KEY (CITYMODEL_ID)
REFERENCES CITYMODEL (ID) ENABLE;

ALTER TABLE APPEARANCE
ADD CONSTRAINT APPEARANCE_CITYOBJECT_FK FOREIGN KEY (CITYOBJECT_ID)
REFERENCES CITYOBJECT (ID) ENABLE;


--//APPEAR_TO_SURFACE_DATA CONSTRAINT

ALTER TABLE APPEAR_TO_SURFACE_DATA
ADD CONSTRAINT APPEAR_TO_SURFACE_DATA_FK1 FOREIGN KEY (APPEARANCE_ID)
REFERENCES APPEARANCE (ID) ENABLE;

ALTER TABLE APPEAR_TO_SURFACE_DATA
ADD CONSTRAINT APPEAR_TO_SURFACE_DATA_FK FOREIGN KEY (SURFACE_DATA_ID)
REFERENCES SURFACE_DATA (ID) ENABLE;


--//BREAKLINE_RELIEF CONSTRAINT

ALTER TABLE BREAKLINE_RELIEF
ADD CONSTRAINT BREAKLINE_RELIEF_FK FOREIGN KEY (ID)
REFERENCES RELIEF_COMPONENT (ID) ENABLE;


--//BUILDING CONSTRAINT
ALTER TABLE BUILDING
ADD CONSTRAINT BUILDING_CITYOBJECT_FK FOREIGN KEY (ID)
REFERENCES CITYOBJECT (ID) ENABLE;

ALTER TABLE BUILDING
ADD CONSTRAINT BUILDING_BUILDING_FK FOREIGN KEY (BUILDING_PARENT_ID)
REFERENCES BUILDING (ID) ENABLE;

ALTER TABLE BUILDING
ADD CONSTRAINT BUILDING_BUILDING_FK1 FOREIGN KEY (BUILDING_ROOT_ID)
REFERENCES BUILDING (ID) ENABLE;

ALTER TABLE BUILDING
ADD CONSTRAINT BUILDING_SURFACE_GEOMETRY_FK FOREIGN KEY (LOD1_SOLID_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE BUILDING
ADD CONSTRAINT BUILDING_SURFACE_GEOMETRY_FK1 FOREIGN KEY (LOD2_SOLID_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE BUILDING
ADD CONSTRAINT BUILDING_SURFACE_GEOMETRY_FK2 FOREIGN KEY (LOD3_SOLID_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE BUILDING
ADD CONSTRAINT BUILDING_SURFACE_GEOMETRY_FK3 FOREIGN KEY (LOD4_SOLID_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE BUILDING
ADD CONSTRAINT BUILDING_SURFACE_GEOMETRY_FK4 FOREIGN KEY (LOD0_FOOTPRINT_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE BUILDING
ADD CONSTRAINT BUILDING_SURFACE_GEOMETRY_FK5 FOREIGN KEY (LOD0_ROOFPRINT_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE BUILDING
ADD CONSTRAINT BUILDING_SURFACE_GEOMETRY_FK6 FOREIGN KEY (LOD1_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE BUILDING
ADD CONSTRAINT BUILDING_SURFACE_GEOMETRY_FK7 FOREIGN KEY (LOD2_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE BUILDING
ADD CONSTRAINT BUILDING_SURFACE_GEOMETRY_FK8 FOREIGN KEY (LOD3_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE BUILDING
ADD CONSTRAINT BUILDING_SURFACE_GEOMETRY_FK9 FOREIGN KEY (LOD4_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;


--//BUILDING_FURNITURE CONSTRAINT

ALTER TABLE BUILDING_FURNITURE
ADD CONSTRAINT BUILDING_FURNITURE_FK1 FOREIGN KEY (ID)
REFERENCES CITYOBJECT (ID) ENABLE;

ALTER TABLE BUILDING_FURNITURE
ADD CONSTRAINT BUILDING_FURNITURE_FK2 FOREIGN KEY (LOD4_BREP_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE BUILDING_FURNITURE
ADD CONSTRAINT BUILDING_FURNITURE_FK FOREIGN KEY (LOD4_IMPLICIT_REP_ID)
REFERENCES IMPLICIT_GEOMETRY (ID) ENABLE;

ALTER TABLE BUILDING_FURNITURE
ADD CONSTRAINT BUILDING_FURNITURE_ROOM_FK FOREIGN KEY (ROOM_ID)
REFERENCES ROOM (ID) ENABLE;


--//BUILDING_INSTALLATION CONSTRAINT


ALTER TABLE BUILDING_INSTALLATION
ADD CONSTRAINT BUILDING_INSTALLATION_FK FOREIGN KEY (ID)
REFERENCES CITYOBJECT (ID) ENABLE;

ALTER TABLE BUILDING_INSTALLATION
ADD CONSTRAINT BUILDING_INSTALLATION_FK1 FOREIGN KEY (BUILDING_ID)
REFERENCES BUILDING (ID) ENABLE;

ALTER TABLE BUILDING_INSTALLATION
ADD CONSTRAINT BUILDING_INSTALLATION_FK2 FOREIGN KEY (LOD2_BREP_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE BUILDING_INSTALLATION
ADD CONSTRAINT BUILDING_INSTALLATION_FK3 FOREIGN KEY (LOD3_BREP_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE BUILDING_INSTALLATION
ADD CONSTRAINT BUILDING_INSTALLATION_FK4 FOREIGN KEY (LOD4_BREP_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE BUILDING_INSTALLATION
ADD CONSTRAINT BUILDING_INSTALLATION_FK5 FOREIGN KEY (LOD2_IMPLICIT_REP_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE BUILDING_INSTALLATION
ADD CONSTRAINT BUILDING_INSTALLATION_FK6 FOREIGN KEY (LOD3_IMPLICIT_REP_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE BUILDING_INSTALLATION
ADD CONSTRAINT BUILDING_INSTALLATION_FK7 FOREIGN KEY (LOD4_IMPLICIT_REP_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE BUILDING_INSTALLATION
ADD CONSTRAINT BUILDING_INSTALLATION_ROOM_FK FOREIGN KEY (ROOM_ID)
REFERENCES ROOM (ID) ENABLE;

--// BRD_CONSTR_ELEMENT CONSTRAINT

ALTER TABLE BRD_CONSTR_ELEMENT
ADD CONSTRAINT BRD_CONSTR_ELEMENT_FK FOREIGN KEY(ID)
REFERENCES CITYOBJECT (ID) ENABLE;

ALTER TABLE BRD_CONSTR_ELEMENT
ADD CONSTRAINT BRD_CONSTR_ELEMENT_FK1 FOREIGN KEY (BRIDGE_ID)
REFERENCES BRIDGE (ID) ENABLE;

ALTER TABLE BRD_CONSTR_ELEMENT
ADD CONSTRAINT BRD_CONSTR_ELEMENT_FK2 FOREIGN KEY (LOD1_BREP_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE BRD_CONSTR_ELEMENT
ADD CONSTRAINT BRD_CONSTR_ELEMENT_FK3 FOREIGN KEY (LOD2_BREP_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE BRD_CONSTR_ELEMENT
ADD CONSTRAINT BRD_CONSTR_ELEMENT_FK4 FOREIGN KEY (LOD3_BREP_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE BRD_CONSTR_ELEMENT
ADD CONSTRAINT BRD_CONSTR_ELEMENT_FK5 FOREIGN KEY (LOD4_BREP_ID)
REFERENCES IMPLICIT_GEOMETRY (ID) ENABLE;

ALTER TABLE BRD_CONSTR_ELEMENT
ADD CONSTRAINT BRD_CONSTR_ELEMENT_FK6 FOREIGN KEY (LOD1_IMPLICIT_REP_ID)
REFERENCES IMPLICIT_GEOMETRY (ID) ENABLE;

ALTER TABLE BRD_CONSTR_ELEMENT
ADD CONSTRAINT BRD_CONSTR_ELEMENT_FK7 FOREIGN KEY (LOD2_IMPLICIT_REP_ID)
REFERENCES IMPLICIT_GEOMETRY (ID) ENABLE;

ALTER TABLE BRD_CONSTR_ELEMENT
ADD CONSTRAINT BRD_CONSTR_ELEMENT_FK8 FOREIGN KEY (LOD3_IMPLICIT_REP_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE BRD_CONSTR_ELEMENT
ADD CONSTRAINT BRD_CONSTR_ELEMENT_FK9 FOREIGN KEY (LOD4_IMPLICIT_REP_ID)
REFERENCES IMPLICIT_GEOMETRY (ID) ENABLE;

--// BRD_OPEN_TO_THEM_SURFACE CONSTRAINT

ALTER TABLE BRD_OPEN_TO_THEM_SURFACE
ADD CONSTRAINT BRD_OPEN_TO_THEM_SURFACE_FK FOREIGN KEY (BRIDGE_OPENING_ID)
REFERENCES BRIDGE_OPENING (ID) ENABLE;

ALTER TABLE BRD_OPEN_TO_THEM_SURFACE
ADD CONSTRAINT BRD_OPEN_TO_THEM_SURFACE_FK1 FOREIGN KEY (THEMATIC_SURFACE_ID)
REFERENCES BRD_THEMATIC_SURFACE (ID) ENABLE;

--// BRD_THEMATIC_SURFACE CONSTRAINT

ALTER TABLE BRD_THEMATIC_SURFACE
ADD CONSTRAINT BRD_THEMATIC_SURFACE_CLASS_FK FOREIGN KEY (OBJECTCLASS_ID)
REFERENCES OBJECTCLASS (ID) ENABLE;

ALTER TABLE BRD_THEMATIC_SURFACE
ADD CONSTRAINT BRD_THEMATIC_SURFACE_FK FOREIGN KEY (BRIDGE_ID)
REFERENCES BRIDGE (ID) ENABLE;

ALTER TABLE BRD_THEMATIC_SURFACE
ADD CONSTRAINT BRD_THEMATIC_SURFACE_FK2 FOREIGN KEY (BRIDGE_CONSTR_ELEM_ID)
REFERENCES BRD_CONSTR_ELEMENT (ID) ENABLE;

ALTER TABLE BRD_THEMATIC_SURFACE
ADD CONSTRAINT BRD_THEMATIC_SURFACE_FK3 FOREIGN KEY (BRIDGE_INSTALLATION_ID)
REFERENCES BRIDGE_INSTALLATION (ID) ENABLE;

ALTER TABLE BRD_THEMATIC_SURFACE
ADD CONSTRAINT BRD_THEMATIC_SURFACE_FK4 FOREIGN KEY (BRIDGE_ROOM_ID)
REFERENCES BRIDGE_ROOM (ID) ENABLE;

ALTER TABLE BRD_THEMATIC_SURFACE
ADD CONSTRAINT BRD_THEMATIC_SURFACE_FK5 FOREIGN KEY (ID)
REFERENCES CITYOBJECT (ID) ENABLE;

ALTER TABLE BRD_THEMATIC_SURFACE
ADD CONSTRAINT BRD_THEMATIC_SURFACE_FK6 FOREIGN KEY (LOD2_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE BRD_THEMATIC_SURFACE
ADD CONSTRAINT BRD_THEMATIC_SURFACE_FK7 FOREIGN KEY (LOD3_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE BRD_THEMATIC_SURFACE
ADD CONSTRAINT BRD_THEMATIC_SURFACE_FK8 FOREIGN KEY (LOD4_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;


--// BRIDGE_FURNITURE CONSTRAINT

ALTER TABLE BRIDGE_FURNITURE
ADD CONSTRAINT BRIDGE_FURNITURE_FK FOREIGN KEY (LOD4_IMPLICIT_REP_ID)
REFERENCES IMPLICIT_GEOMETRY (ID) ENABLE;

ALTER TABLE BRIDGE_FURNITURE
ADD CONSTRAINT BRIDGE_FURNITURE_FK1 FOREIGN KEY (ID)
REFERENCES CITYOBJECT (ID) ENABLE;

ALTER TABLE BRIDGE_FURNITURE
ADD CONSTRAINT BRIDGE_FURNITURE_FK2 FOREIGN KEY (LOD4_BREP_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE BRIDGE_FURNITURE
ADD CONSTRAINT BRIDGE_FURNITURE_ROOM_FK FOREIGN KEY (BRIDGE_ROOM_ID)
REFERENCES BRIDGE_ROOM (ID) ENABLE;

--// BRIDGE_INSTALLATION CONSTRAINT

ALTER TABLE BRIDGE_INSTALLATION
ADD CONSTRAINT BRIDGE_INSTALLATION_FK FOREIGN KEY (ID)
REFERENCES CITYOBJECT (ID) ENABLE;

ALTER TABLE BRIDGE_INSTALLATION
ADD CONSTRAINT BRIDGE_INSTALLATION_FK1 FOREIGN KEY (BRIDGE_ID)
REFERENCES BRIDGE (ID) ENABLE;

ALTER TABLE BRIDGE_INSTALLATION
ADD CONSTRAINT BRIDGE_INSTALLATION_FK2 FOREIGN KEY (LOD2_BREP_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE BRIDGE_INSTALLATION
ADD CONSTRAINT BRIDGE_INSTALLATION_FK3 FOREIGN KEY (LOD3_BREP_ID)
REFERENCES SURFACE_GEOMETRY(ID) ENABLE;

ALTER TABLE BRIDGE_INSTALLATION
ADD CONSTRAINT BRIDGE_INSTALLATION_FK4 FOREIGN KEY (LOD4_BREP_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE BRIDGE_INSTALLATION
ADD CONSTRAINT BRIDGE_INSTALLATION_FK5 FOREIGN KEY (LOD2_IMPLICIT_REP_ID)
REFERENCES IMPLICIT_GEOMETRY (ID) ENABLE;

ALTER TABLE BRIDGE_INSTALLATION
ADD CONSTRAINT BRIDGE_INSTALLATION_FK6 FOREIGN KEY (LOD3_IMPLICIT_REP_ID)
REFERENCES IMPLICIT_GEOMETRY (ID) ENABLE;

ALTER TABLE BRIDGE_INSTALLATION
ADD CONSTRAINT BRIDGE_INSTALLATION_FK7 FOREIGN KEY (LOD4_IMPLICIT_REP_ID)
REFERENCES IMPLICIT_GEOMETRY (ID) ENABLE;

ALTER TABLE BRIDGE_INSTALLATION
ADD CONSTRAINT BRIDGE_INSTALLATION_ROOM_FK FOREIGN KEY (BRIDGE_ROOM_ID)
REFERENCES BRIDGE_ROOM (ID) ENABLE;

--// BRIDGE_OPENING CONSTRAINT

ALTER TABLE BRIDGE_OPENING
ADD CONSTRAINT BRIDGE_OPENING_ADDRESS_FK FOREIGN KEY (ADDRESS_ID)
REFERENCES ADDRESS (ID) ENABLE;

ALTER TABLE BRIDGE_OPENING
ADD CONSTRAINT BRIDGE_OPENING_CITYOBJECT_FK FOREIGN KEY (ID)
REFERENCES CITYOBJECT (ID) ENABLE;

ALTER TABLE BRIDGE_OPENING
ADD CONSTRAINT BRIDGE_OPENING_FK1 FOREIGN KEY (LOD4_IMPLICIT_REP_ID)
REFERENCES IMPLICIT_GEOMETRY (ID) ENABLE;

ALTER TABLE BRIDGE_OPENING
ADD CONSTRAINT BRIDGE_OPENING_FK2 FOREIGN KEY (LOD3_IMPLICIT_REP_ID)
REFERENCES IMPLICIT_GEOMETRY (ID) ENABLE;

ALTER TABLE BRIDGE_OPENING
ADD CONSTRAINT BRIDGE_OPENING_FK3 FOREIGN KEY (LOD3_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE BRIDGE_OPENING
ADD CONSTRAINT BRIDGE_OPENING_FK4 FOREIGN KEY (LOD4_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE BRIDGE_OPENING
ADD CONSTRAINT BRIDGE_OPENING_OBJCLASS_FK FOREIGN KEY (OBJECTCLASS_ID)
REFERENCES OBJECTCLASS (ID) ENABLE;

--// BRIDGE_ROOM CONSTRAINT

ALTER TABLE BRIDGE_ROOM
ADD CONSTRAINT BRIDGE_ROOM_BUILDING_FK FOREIGN KEY (BRIDGE_ID)
REFERENCES BRIDGE (ID) ENABLE;

ALTER TABLE BRIDGE_ROOM
ADD CONSTRAINT BRIDGE_ROOM_CITYOBJECT_FK FOREIGN KEY (ID)
REFERENCES CITYOBJECT (ID) ENABLE;

ALTER TABLE BRIDGE_ROOM
ADD CONSTRAINT BRIDGE_ROOM_GEOMETRY_FK FOREIGN KEY (LOD4_SOLID_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE BRIDGE_ROOM
ADD CONSTRAINT BRIDGE_ROOM_GEOMETRY_FK1 FOREIGN KEY (LOD4_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

--// BRIDGE CONSTRAINT

ALTER TABLE BRIDGE
ADD CONSTRAINT BRIDGE_BRIDGE_FK FOREIGN KEY (BRIDGE_PARENT_ID)
REFERENCES BRIDGE (ID) ENABLE;

ALTER TABLE BRIDGE
ADD CONSTRAINT BRIDGE_BRIDGE_FK1 FOREIGN KEY (BRIDGE_ROOT_ID)
REFERENCES BRIDGE (ID) ENABLE;

ALTER TABLE BRIDGE
ADD CONSTRAINT BRIDGE_CITYOBJECT_FK FOREIGN KEY (ID)
REFERENCES CITYOBJECT (ID) ENABLE;

ALTER TABLE BRIDGE
ADD CONSTRAINT BRIDGE_SURFACE_GEOMETRY_FK FOREIGN KEY (LOD1_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE BRIDGE
ADD CONSTRAINT BRIDGE_SURFACE_GEOMETRY_FK1 FOREIGN KEY (LOD2_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE BRIDGE
ADD CONSTRAINT BRIDGE_SURFACE_GEOMETRY_FK2 FOREIGN KEY (LOD3_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE BRIDGE
ADD CONSTRAINT BRIDGE_SURFACE_GEOMETRY_FK3 FOREIGN KEY (LOD4_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE BRIDGE
ADD CONSTRAINT BRIDGE_SURFACE_GEOMETRY_FK4 FOREIGN KEY (LOD1_SOLID_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE BRIDGE
ADD CONSTRAINT BRIDGE_SURFACE_GEOMETRY_FK5 FOREIGN KEY (LOD2_SOLID_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE BRIDGE
ADD CONSTRAINT BRIDGE_SURFACE_GEOMETRY_FK6 FOREIGN KEY (LOD3_SOLID_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE BRIDGE
ADD CONSTRAINT BRIDGE_SURFACE_GEOMETRY_FK7 FOREIGN KEY (LOD4_SOLID_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

--//CITYOBJECT CONSTRAINT

ALTER TABLE CITYOBJECT
ADD CONSTRAINT CITYOBJECT_OBJECTCLASS_FK FOREIGN KEY (CLASS_ID)
REFERENCES OBJECTCLASS (ID) ENABLE;


--//CITYOBJECTGROUP CONSTRAINT

ALTER TABLE CITYOBJECTGROUP
ADD CONSTRAINT CITYOBJECT_GROUP_FK FOREIGN KEY (BREP_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE CITYOBJECTGROUP
ADD CONSTRAINT CITYOBJECTGROUP_CITYOBJECT_FK FOREIGN KEY (PARENT_CITYOBJECT_ID)
REFERENCES CITYOBJECT (ID) ENABLE;

ALTER TABLE CITYOBJECTGROUP
ADD CONSTRAINT CITYOBJECTGROUP_CITYOBJECT_FK1 FOREIGN KEY (ID)
REFERENCES CITYOBJECT (ID) ENABLE;


--//CITYOBJECT_GENERICATTRIB CONSTRAINT

ALTER TABLE CITYOBJECT_GENERICATTRIB
ADD CONSTRAINT CITYOBJECT_GENERICATTRIB_FK FOREIGN KEY (CITYOBJECT_ID)
REFERENCES CITYOBJECT (ID) ENABLE;

ALTER TABLE CITYOBJECT_GENERICATTRIB
ADD CONSTRAINT CITYOBJECT_GENERICATTRIB_FK1 FOREIGN KEY (SURFACE_GEOMETRY_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE CITYOBJECT_GENERICATTRIB
ADD CONSTRAINT CITYOBJECT_GENERICATTRIB_FK2 FOREIGN KEY (PARENT_GENATT_ID)
REFERENCES CITYOBJECT (ID) ENABLE;

ALTER TABLE CITYOBJECT_GENERICATTRIB
ADD CONSTRAINT CITYOBJECT_GENERICATTRIB_FK3 FOREIGN KEY (ROOT_GENATT_ID)
REFERENCES CITYOBJECT (ID) ENABLE;


--//CITYOBJECT_MEMBER CONSTRAINT

ALTER TABLE CITYOBJECT_MEMBER
ADD CONSTRAINT CITYOBJECT_MEMBER_CITYMODEL_FK FOREIGN KEY (CITYMODEL_ID)
REFERENCES CITYMODEL (ID) ENABLE;

ALTER TABLE CITYOBJECT_MEMBER
ADD CONSTRAINT CITYOBJECT_MEMBER_FK FOREIGN KEY (CITYOBJECT_ID)
REFERENCES CITYOBJECT (ID) ENABLE;


--//CITY_FURNITURE CONSTRAINT

ALTER TABLE CITY_FURNITURE
ADD CONSTRAINT CITY_FURNITURE_FK FOREIGN KEY (LOD1_BREP_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE CITY_FURNITURE
ADD CONSTRAINT CITY_FURNITURE_FK1 FOREIGN KEY (LOD2_BREP_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE CITY_FURNITURE
ADD CONSTRAINT CITY_FURNITURE_FK2 FOREIGN KEY (LOD3_BREP_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE CITY_FURNITURE
ADD CONSTRAINT CITY_FURNITURE_FK3 FOREIGN KEY (LOD4_BREP_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE CITY_FURNITURE
ADD CONSTRAINT CITY_FURNITURE_FK4 FOREIGN KEY (LOD1_IMPLICIT_REP_ID)
REFERENCES IMPLICIT_GEOMETRY (ID) ENABLE;

ALTER TABLE CITY_FURNITURE
ADD CONSTRAINT CITY_FURNITURE_FK5 FOREIGN KEY (LOD2_IMPLICIT_REP_ID)
REFERENCES IMPLICIT_GEOMETRY (ID) ENABLE;

ALTER TABLE CITY_FURNITURE
ADD CONSTRAINT CITY_FURNITURE_FK6 FOREIGN KEY (LOD3_IMPLICIT_REP_ID)
REFERENCES IMPLICIT_GEOMETRY (ID) ENABLE;

ALTER TABLE CITY_FURNITURE
ADD CONSTRAINT CITY_FURNITURE_FK7 FOREIGN KEY (LOD4_IMPLICIT_REP_ID)
REFERENCES IMPLICIT_GEOMETRY (ID) ENABLE;

ALTER TABLE CITY_FURNITURE
ADD CONSTRAINT CITY_FURNITURE_CITYOBJECT_FK FOREIGN KEY (ID)
REFERENCES CITYOBJECT (ID) ENABLE;


--//EXTERNAL_REFERENCE CONSTRAINT

ALTER TABLE EXTERNAL_REFERENCE
ADD CONSTRAINT EXTERNAL_REFERENCE_FK FOREIGN KEY (CITYOBJECT_ID)
REFERENCES CITYOBJECT (ID) ENABLE;


--//GENERALIZATION CONSTRAINT

ALTER TABLE GENERALIZATION
ADD CONSTRAINT GENERALIZATION_FK1 FOREIGN KEY (GENERALIZES_TO_ID)
REFERENCES CITYOBJECT (ID) ENABLE;

ALTER TABLE GENERALIZATION
ADD CONSTRAINT GENERALIZATION_FK FOREIGN KEY (CITYOBJECT_ID)
REFERENCES CITYOBJECT (ID) ENABLE;


--//GENERIC_CITYOBJECT CONSTRAINT

ALTER TABLE GENERIC_CITYOBJECT
ADD CONSTRAINT GENERIC_CITYOBJECT_FK FOREIGN KEY (LOD0_IMPLICIT_REP_ID)
REFERENCES IMPLICIT_GEOMETRY (ID) ENABLE;

ALTER TABLE GENERIC_CITYOBJECT
ADD CONSTRAINT GENERIC_CITYOBJECT_FK1 FOREIGN KEY (LOD1_IMPLICIT_REP_ID)
REFERENCES IMPLICIT_GEOMETRY (ID) ENABLE;

ALTER TABLE GENERIC_CITYOBJECT
ADD CONSTRAINT GENERIC_CITYOBJECT_FK2 FOREIGN KEY (LOD2_IMPLICIT_REP_ID)
REFERENCES IMPLICIT_GEOMETRY (ID) ENABLE;

ALTER TABLE GENERIC_CITYOBJECT
ADD CONSTRAINT GENERIC_CITYOBJECT_FK3 FOREIGN KEY (LOD3_IMPLICIT_REP_ID)
REFERENCES IMPLICIT_GEOMETRY (ID) ENABLE;

ALTER TABLE GENERIC_CITYOBJECT
ADD CONSTRAINT GENERIC_CITYOBJECT_FK4 FOREIGN KEY (LOD4_IMPLICIT_REP_ID)
REFERENCES IMPLICIT_GEOMETRY (ID) ENABLE;

ALTER TABLE GENERIC_CITYOBJECT
ADD CONSTRAINT GENERIC_CITYOBJECT_FK5 FOREIGN KEY (LOD0_BREP_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE GENERIC_CITYOBJECT
ADD CONSTRAINT GENERIC_CITYOBJECT_FK6 FOREIGN KEY (LOD1_BREP_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE GENERIC_CITYOBJECT
ADD CONSTRAINT GENERIC_CITYOBJECT_FK7 FOREIGN KEY (LOD2_BREP_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE GENERIC_CITYOBJECT
ADD CONSTRAINT GENERIC_CITYOBJECT_FK8 FOREIGN KEY (LOD3_BREP_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE GENERIC_CITYOBJECT
ADD CONSTRAINT GENERIC_CITYOBJECT_FK9 FOREIGN KEY (LOD4_BREP_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE GENERIC_CITYOBJECT
ADD CONSTRAINT GENERIC_CITYOBJECT_FK10 FOREIGN KEY (ID)
REFERENCES CITYOBJECT (ID) ENABLE;


--//GROUP_TO_CITYOBJECT CONSTRAINT

ALTER TABLE GROUP_TO_CITYOBJECT
ADD CONSTRAINT GROUP_TO_CITYOBJECT_FK FOREIGN KEY (CITYOBJECT_ID)
REFERENCES CITYOBJECT (ID) ENABLE;

ALTER TABLE GROUP_TO_CITYOBJECT
ADD CONSTRAINT GROUP_TO_CITYOBJECT_FK1 FOREIGN KEY (CITYOBJECTGROUP_ID)
REFERENCES CITYOBJECTGROUP (ID) ENABLE;

--//IMPLICIT_GEOMETRY CONSTRAINT

ALTER TABLE IMPLICIT_GEOMETRY
ADD CONSTRAINT IMPLICIT_GEOMETRY_FK FOREIGN KEY (RELATIVE_BREP_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;


--//LAND_USE CONSTRAINT

ALTER TABLE LAND_USE
ADD CONSTRAINT LAND_USE_CITYOBJECT_FK FOREIGN KEY (ID)
REFERENCES CITYOBJECT (ID) ENABLE;

ALTER TABLE LAND_USE
ADD CONSTRAINT LAND_USE_SURFACE_GEOMETRY_FK FOREIGN KEY (LOD0_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE LAND_USE
ADD CONSTRAINT LAND_USE_SURFACE_GEOMETRY_FK1 FOREIGN KEY (LOD1_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE LAND_USE
ADD CONSTRAINT LAND_USE_SURFACE_GEOMETRY_FK2 FOREIGN KEY (LOD2_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE LAND_USE
ADD CONSTRAINT LAND_USE_SURFACE_GEOMETRY_FK3 FOREIGN KEY (LOD3_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE LAND_USE
ADD CONSTRAINT LAND_USE_SURFACE_GEOMETRY_FK4 FOREIGN KEY (LOD4_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;


--//MASSPOINT_RELIEF CONSTRAINT

ALTER TABLE MASSPOINT_RELIEF
ADD CONSTRAINT MASSPOINT_RELIEF_FK FOREIGN KEY (ID)
REFERENCES RELIEF_COMPONENT (ID) ENABLE;


--//OBJECTCLASS CONSTRAINT

ALTER TABLE OBJECTCLASS
ADD CONSTRAINT OBJECTCLASS_OBJECTCLASS_FK FOREIGN KEY (SUPERCLASS_ID)
REFERENCES OBJECTCLASS (ID) ENABLE;


--//OPENING CONSTRAINT

ALTER TABLE OPENING
ADD CONSTRAINT OPENING_SURFACE_GEOMETRY_FK1 FOREIGN KEY (LOD4_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE OPENING
ADD CONSTRAINT OPENING_CITYOBJECT_FK FOREIGN KEY (ID)
REFERENCES CITYOBJECT (ID) ENABLE;

ALTER TABLE OPENING
ADD CONSTRAINT OPENING_SURFACE_GEOMETRY_FK FOREIGN KEY (LOD3_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE OPENING
ADD CONSTRAINT OPENING_ADDRESS_FK FOREIGN KEY (ADDRESS_ID)
REFERENCES ADDRESS (ID) ENABLE;

ALTER TABLE OPENING
ADD CONSTRAINT OPENING_IMPLICITGEOMETRY_FK FOREIGN KEY (LOD4_IMPLICIT_REP_ID)
REFERENCES IMPLICIT_GEOMETRY (ID) ENABLE;

ALTER TABLE OPENING
ADD CONSTRAINT OPENING_IMPLICITGEOMETRY_FK2 FOREIGN KEY (LOD3_IMPLICIT_REP_ID)
REFERENCES IMPLICIT_GEOMETRY (ID) ENABLE;

ALTER TABLE OPENING
ADD CONSTRAINT OPENING_OBJECTCLASS_FK FOREIGN KEY (OBJECTCLASS_ID)
REFERENCES OBJECTCLASS (ID) ENABLE;

--//OPENING_TO_THEM_SURFACE CONSTRAINT

ALTER TABLE OPENING_TO_THEM_SURFACE
ADD CONSTRAINT OPENING_TO_THEMATIC_SURFACE_FK FOREIGN KEY (OPENING_ID)
REFERENCES OPENING (ID) ENABLE;

ALTER TABLE OPENING_TO_THEM_SURFACE
ADD CONSTRAINT OPENING_TO_THEMATIC_SURFAC_FK1 FOREIGN KEY (THEMATIC_SURFACE_ID)
REFERENCES THEMATIC_SURFACE (ID) ENABLE;


--//PLANT_COVER CONSTRAINT

ALTER TABLE PLANT_COVER
ADD CONSTRAINT PLANT_COVER_CITYOBJECT_FK FOREIGN KEY (ID)
REFERENCES CITYOBJECT (ID) ENABLE;

ALTER TABLE PLANT_COVER
ADD CONSTRAINT PLANT_COVER_FK FOREIGN KEY (LOD1_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE PLANT_COVER
ADD CONSTRAINT PLANT_COVER_FK1 FOREIGN KEY (LOD2_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE PLANT_COVER
ADD CONSTRAINT PLANT_COVER_FK2 FOREIGN KEY (LOD3_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE PLANT_COVER
ADD CONSTRAINT PLANT_COVER_FK3 FOREIGN KEY (LOD4_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE PLANT_COVER
ADD CONSTRAINT PLANT_COVER_FK4 FOREIGN KEY (LOD1_SOLID_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE PLANT_COVER
ADD CONSTRAINT PLANT_COVER_FK5 FOREIGN KEY (LOD2_SOLID_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE PLANT_COVER
ADD CONSTRAINT PLANT_COVER_FK6 FOREIGN KEY (LOD3_SOLID_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE PLANT_COVER
ADD CONSTRAINT PLANT_COVER_FK7 FOREIGN KEY (LOD4_SOLID_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;


--//RELIEF_COMPONENT CONSTRAINT

ALTER TABLE RELIEF_COMPONENT
ADD CONSTRAINT RELIEF_COMPONENT_CITYOBJECT_FK FOREIGN KEY (ID)
REFERENCES CITYOBJECT (ID) ENABLE;

ALTER TABLE RELIEF_COMPONENT
ADD CONSTRAINT RELIEF_COMPONENT_CHK1 CHECK (LOD>=0 AND LOD<5) ENABLE;

ALTER TABLE RELIEF_COMPONENT
ADD CONSTRAINT RELIEF_COMPONENT_OBJCLASS_FK FOREIGN KEY (OBJECTCLASS_ID)
REFERENCES OBJECTCLASS (ID) ENABLE;

--//RELIEF_FEATURE CONSTRAINT

ALTER TABLE RELIEF_FEATURE
ADD CONSTRAINT RELIEF_FEATURE_CITYOBJECT_FK FOREIGN KEY (ID)
REFERENCES CITYOBJECT (ID) ENABLE;

ALTER TABLE RELIEF_FEATURE
ADD CONSTRAINT RELIEF_FEATURE_CHK1 CHECK (LOD>=0 AND LOD<5) ENABLE;


--//RELIEF_FEAT_TO_REL_COMP CONSTRAINT

ALTER TABLE RELIEF_FEAT_TO_REL_COMP
ADD CONSTRAINT RELIEF_FEAT_TO_REL_COMP_FK FOREIGN KEY (RELIEF_COMPONENT_ID)
REFERENCES RELIEF_COMPONENT (ID) ENABLE;

ALTER TABLE RELIEF_FEAT_TO_REL_COMP
ADD CONSTRAINT RELIEF_FEAT_TO_REL_COMP_FK1 FOREIGN KEY (RELIEF_FEATURE_ID)
REFERENCES RELIEF_FEATURE (ID) ENABLE;

--//RASTER_RELIEF CONSTRAINT

ALTER TABLE RASTER_RELIEF
ADD CONSTRAINT RASTER_RELIEF_FK FOREIGN KEY (ID)
REFERENCES RELIEF_COMPONENT (ID) ENABLE;

ALTER TABLE RASTER_RELIEF
ADD CONSTRAINT RASTER_RELIEF_FK1 FOREIGN KEY (GEORASTER_ID)
REFERENCES RASTER_RELIEF_GEORASTER (ID) ENABLE;

--//ROOM CONSTRAINT

ALTER TABLE ROOM
ADD CONSTRAINT ROOM_BUILDING_FK FOREIGN KEY (BUILDING_ID)
REFERENCES BUILDING (ID) ENABLE;

ALTER TABLE ROOM
ADD CONSTRAINT ROOM_SURFACE_GEOMETRY_FK FOREIGN KEY (LOD4_SOLID_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE ROOM
ADD CONSTRAINT ROOM_CITYOBJECT_FK FOREIGN KEY (ID)
REFERENCES CITYOBJECT (ID) ENABLE;

ALTER TABLE ROOM
ADD CONSTRAINT ROOM_SURFACE_GEOMETRY_FK1 FOREIGN KEY (LOD4_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

--//SOLITARY_VEGETAT_OBJECT CONSTRAINT

ALTER TABLE SOLITARY_VEGETAT_OBJECT
ADD CONSTRAINT SOLITARY_VEGETAT_OBJECT_FK FOREIGN KEY (ID)
REFERENCES CITYOBJECT (ID) ENABLE;

ALTER TABLE SOLITARY_VEGETAT_OBJECT
ADD CONSTRAINT SOLITARY_VEGETAT_OBJECT_FK1 FOREIGN KEY (LOD1_BREP_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE SOLITARY_VEGETAT_OBJECT
ADD CONSTRAINT SOLITARY_VEGETAT_OBJECT_FK2 FOREIGN KEY (LOD2_BREP_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE SOLITARY_VEGETAT_OBJECT
ADD CONSTRAINT SOLITARY_VEGETAT_OBJECT_FK3 FOREIGN KEY (LOD3_BREP_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE SOLITARY_VEGETAT_OBJECT
ADD CONSTRAINT SOLITARY_VEGETAT_OBJECT_FK4 FOREIGN KEY (LOD4_BREP_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE SOLITARY_VEGETAT_OBJECT
ADD CONSTRAINT SOLITARY_VEGETAT_OBJECT_FK5 FOREIGN KEY (LOD1_IMPLICIT_REP_ID)
REFERENCES IMPLICIT_GEOMETRY (ID) ENABLE;

ALTER TABLE SOLITARY_VEGETAT_OBJECT
ADD CONSTRAINT SOLITARY_VEGETAT_OBJECT_FK6 FOREIGN KEY (LOD2_IMPLICIT_REP_ID)
REFERENCES IMPLICIT_GEOMETRY (ID) ENABLE;

ALTER TABLE SOLITARY_VEGETAT_OBJECT
ADD CONSTRAINT SOLITARY_VEGETAT_OBJECT_FK7 FOREIGN KEY (LOD3_IMPLICIT_REP_ID)
REFERENCES IMPLICIT_GEOMETRY (ID) ENABLE;

ALTER TABLE SOLITARY_VEGETAT_OBJECT
ADD CONSTRAINT SOLITARY_VEGETAT_OBJECT_FK8 FOREIGN KEY (LOD4_IMPLICIT_REP_ID)
REFERENCES IMPLICIT_GEOMETRY (ID) ENABLE;


--//SURFACE_GEOMETRY CONSTRAINT

ALTER TABLE SURFACE_GEOMETRY
ADD CONSTRAINT SURFACE_GEOMETRY_FK FOREIGN KEY (PARENT_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE SURFACE_GEOMETRY
ADD CONSTRAINT SURFACE_GEOMETRY_FK1 FOREIGN KEY (ROOT_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE SURFACE_GEOMETRY
ADD CONSTRAINT SURFACE_GEOMETRY_CITYOBJECT_FK FOREIGN KEY (CITYOBJECT_ID)
REFERENCES CITYOBJECT (ID) ENABLE;

--//SURFACE_DATA CONSTRAINT

ALTER TABLE SURFACE_DATA
ADD CONSTRAINT SURF_DATA_OBJCLASS_FK2 FOREIGN KEY (OBJECTCLASS_ID)
REFERENCES OBJECTCLASS (ID) ENABLE;

ALTER TABLE SURFACE_DATA 
ADD CONSTRAINT SURF_DATA_TEX_IMAGE_FK1 FOREIGN KEY (TEX_IMAGE_ID)
REFERENCES TEX_IMAGE (ID) ENABLE;


--//TEXTUREPARAM CONSTRAINT

ALTER TABLE TEXTUREPARAM
ADD CONSTRAINT TEXTUREPARAM_SURFACE_GEOM_FK FOREIGN KEY (SURFACE_GEOMETRY_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE TEXTUREPARAM
ADD CONSTRAINT TEXTUREPARAM_SURFACE_DATA_FK FOREIGN KEY (SURFACE_DATA_ID)
REFERENCES SURFACE_DATA (ID) ENABLE;


--//THEMATIC_SURFACE CONSTRAINT

ALTER TABLE THEMATIC_SURFACE
ADD CONSTRAINT THEMATIC_SURFACE_ROOM_FK FOREIGN KEY (ROOM_ID)
REFERENCES ROOM (ID) ENABLE;

ALTER TABLE THEMATIC_SURFACE
ADD CONSTRAINT THEMATIC_SURFACE_BUILDING_FK FOREIGN KEY (BUILDING_ID)
REFERENCES BUILDING (ID) ENABLE;

ALTER TABLE THEMATIC_SURFACE
ADD CONSTRAINT THEMATIC_SURFACE_FK FOREIGN KEY (LOD2_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE THEMATIC_SURFACE
ADD CONSTRAINT THEMATIC_SURFACE_CITYOBJECT_FK FOREIGN KEY (ID)
REFERENCES CITYOBJECT (ID) ENABLE;

ALTER TABLE THEMATIC_SURFACE
ADD CONSTRAINT THEMATIC_SURFACE_FK2 FOREIGN KEY (LOD4_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE THEMATIC_SURFACE
ADD CONSTRAINT THEMATIC_SURFACE_FK1 FOREIGN KEY (LOD3_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE THEMATIC_SURFACE
ADD CONSTRAINT THEMATIC_SURFACE_INSTALL_FK FOREIGN KEY (BUILDINGINSTALLATION_ID)
REFERENCES BUILDING_INSTALLATION (ID) ENABLE;

ALTER TABLE THEMATIC_SURFACE
ADD CONSTRAINT THEMATIC_SURFACE_OBJCLASS_FK FOREIGN KEY (OBJECTCLASS_ID)
REFERENCES OBJECTCLASS (ID) ENABLE;


--//TIN_RELIEF CONSTRAINT

ALTER TABLE TIN_RELIEF
ADD CONSTRAINT TIN_RELIEF_SURFACE_GEOMETRY_FK FOREIGN KEY (SURFACE_GEOMETRY_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE TIN_RELIEF
ADD CONSTRAINT TIN_RELIEF_RELIEF_COMPONENT_FK FOREIGN KEY (ID)
REFERENCES RELIEF_COMPONENT (ID) ENABLE;


--//TRAFFIC_AREA CONSTRAINT

ALTER TABLE TRAFFIC_AREA
ADD CONSTRAINT TRAFFIC_AREA_CITYOBJECT_FK FOREIGN KEY (ID)
REFERENCES CITYOBJECT (ID) ENABLE;

ALTER TABLE TRAFFIC_AREA
ADD CONSTRAINT TRAFFIC_AREA_FK FOREIGN KEY (LOD2_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE TRAFFIC_AREA
ADD CONSTRAINT TRAFFIC_AREA_FK1 FOREIGN KEY (LOD3_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE TRAFFIC_AREA
ADD CONSTRAINT TRAFFIC_AREA_FK2 FOREIGN KEY (LOD4_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE TRAFFIC_AREA
ADD CONSTRAINT TRAFFIC_AREA_FK3 FOREIGN KEY (TRANSPORTATION_COMPLEX_ID)
REFERENCES TRANSPORTATION_COMPLEX (ID) ENABLE;


--//TRANSPORTATION_COMPLEX CONSTRAINT

ALTER TABLE TRANSPORTATION_COMPLEX
ADD CONSTRAINT TRANSPORTATION_COMPLEX_FK FOREIGN KEY (ID)
REFERENCES CITYOBJECT (ID) ENABLE;

ALTER TABLE TRANSPORTATION_COMPLEX
ADD CONSTRAINT TRANSPORTATION_COMPLEX_FK1 FOREIGN KEY (LOD1_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE TRANSPORTATION_COMPLEX
ADD CONSTRAINT TRANSPORTATION_COMPLEX_FK2 FOREIGN KEY (LOD2_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE TRANSPORTATION_COMPLEX
ADD CONSTRAINT TRANSPORTATION_COMPLEX_FK3 FOREIGN KEY (LOD3_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE TRANSPORTATION_COMPLEX
ADD CONSTRAINT TRANSPORTATION_COMPLEX_FK4 FOREIGN KEY (LOD4_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE TRANSPORTATION_COMPLEX
ADD CONSTRAINT TRANSPORTATION_COMPLEX_FK5 FOREIGN KEY (OBJECTCLASS_ID)
REFERENCES OBJECTCLASS (ID) ENABLE;

--// TUNNEL_FURNITURE CONSTRAINT

ALTER TABLE TUNNEL_FURNITURE
ADD CONSTRAINT TUNNEL_FURNITURE_FK FOREIGN KEY (LOD4_IMPLICIT_REP_ID)
REFERENCES IMPLICIT_GEOMETRY (ID) ENABLE;

ALTER TABLE TUNNEL_FURNITURE
ADD CONSTRAINT TUNNEL_FURNITURE_FK1 FOREIGN KEY (ID)
REFERENCES CITYOBJECT (ID) ENABLE;

ALTER TABLE TUNNEL_FURNITURE
ADD CONSTRAINT TUNNEL_FURNITURE_FK2 FOREIGN KEY (LOD4_BREP_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE TUNNEL_FURNITURE
ADD CONSTRAINT TUNNEL_FURNITURE_FK3 FOREIGN KEY (TUNNEL_HOLLOWSPACE_ID)
REFERENCES TUNNEL_HOLLOWSPACE (ID) ENABLE;

--// TUNNEL_HOLLOWSPACE CONSTRAINT

ALTER TABLE TUNNEL_HOLLOWSPACE
ADD CONSTRAINT TUNNEL_HOLLOWSPACE_CITYOBJ_FK FOREIGN KEY (ID) 
REFERENCES CITYOBJECT (ID) ENABLE;

ALTER TABLE TUNNEL_HOLLOWSPACE
ADD CONSTRAINT TUNNEL_HOLLOWSPACE_GEOM_FK FOREIGN KEY (LOD4_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE TUNNEL_HOLLOWSPACE
ADD CONSTRAINT TUNNEL_HOLLOWSPACE_GEOM_FK2 FOREIGN KEY (LOD4_SOLID_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE TUNNEL_HOLLOWSPACE
ADD CONSTRAINT TUNNEL_HOLLOWSPACE_TUNNEL_FK FOREIGN KEY (TUNNEL_ID)
REFERENCES TUNNEL (ID) ENABLE;

--// TUNNEL_INSTALLATION CONSTRAINT

ALTER TABLE TUNNEL_INSTALLATION
ADD CONSTRAINT TUNNEL_INSTALLATION_HOLL_FK FOREIGN KEY (TUNNEL_HOLLOWSPACE_ID)
REFERENCES TUNNEL_HOLLOWSPACE (ID) ENABLE;

ALTER TABLE TUNNEL_INSTALLATION
ADD CONSTRAINT TUNNEL_INSTALLATION_FK FOREIGN KEY (ID)
REFERENCES CITYOBJECT (ID) ENABLE;

ALTER TABLE TUNNEL_INSTALLATION
ADD CONSTRAINT TUNNEL_INSTALLATION_FK1 FOREIGN KEY (TUNNEL_ID)
REFERENCES TUNNEL (ID) ENABLE;

ALTER TABLE TUNNEL_INSTALLATION
ADD CONSTRAINT TUNNEL_INSTALLATION_FK2 FOREIGN KEY (LOD2_BREP_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE TUNNEL_INSTALLATION
ADD CONSTRAINT TUNNEL_INSTALLATION_FK3 FOREIGN KEY (LOD3_BREP_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE TUNNEL_INSTALLATION
ADD CONSTRAINT TUNNEL_INSTALLATION_FK4 FOREIGN KEY (LOD4_BREP_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE TUNNEL_INSTALLATION
ADD CONSTRAINT TUNNEL_INSTALLATION_FK5 FOREIGN KEY (LOD2_IMPLICIT_REP_ID)
REFERENCES IMPLICIT_GEOMETRY (ID) ENABLE;

ALTER TABLE TUNNEL_INSTALLATION
ADD CONSTRAINT TUNNEL_INSTALLATION_FK6 FOREIGN KEY (LOD3_IMPLICIT_REP_ID)
REFERENCES IMPLICIT_GEOMETRY (ID) ENABLE;

ALTER TABLE TUNNEL_INSTALLATION
ADD CONSTRAINT TUNNEL_INSTALLATION_FK7 FOREIGN KEY (LOD4_IMPLICIT_REP_ID)
REFERENCES IMPLICIT_GEOMETRY (ID) ENABLE;

--// TUNNEL_OPEN_TO_THEM_SURF CONSTRAINT

ALTER TABLE TUNNEL_OPEN_TO_THEM_SURF
ADD CONSTRAINT TUNNEL_OPEN_TO_THEM_SURF_FK FOREIGN KEY (OPENING_ID)
REFERENCES TUNNEL_OPENING (ID) ENABLE;

ALTER TABLE TUNNEL_OPEN_TO_THEM_SURF
ADD CONSTRAINT TUNNEL_OPEN_TO_THEM_SURF_FK1 FOREIGN KEY (OPENING_ID)
REFERENCES TUNNEL_THEMATIC_SURFACE (ID) ENABLE;

--// TUNNEL_OPENING CONSTRAINT

ALTER TABLE TUNNEL_OPENING
ADD CONSTRAINT TUNNEL_OPENING_FK FOREIGN KEY (ID)
REFERENCES CITYOBJECT (ID) ENABLE;

ALTER TABLE TUNNEL_OPENING
ADD CONSTRAINT TUNNEL_OPENING_FK1 FOREIGN KEY (LOD3_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE TUNNEL_OPENING
ADD CONSTRAINT TUNNEL_OPENING_FK2 FOREIGN KEY (LOD4_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE TUNNEL_OPENING
ADD CONSTRAINT TUNNEL_OPENING_FK3 FOREIGN KEY (LOD4_IMPLICIT_REP_ID)
REFERENCES IMPLICIT_GEOMETRY (ID) ENABLE;

ALTER TABLE TUNNEL_OPENING
ADD CONSTRAINT TUNNEL_OPENING_FK4 FOREIGN KEY (LOD3_IMPLICIT_REP_ID)
REFERENCES IMPLICIT_GEOMETRY (ID) ENABLE;

ALTER TABLE TUNNEL_OPENING
ADD CONSTRAINT TUNNEL_OPENING_OBJCLASS_FK FOREIGN KEY (OBJECTCLASS_ID)
REFERENCES OBJECTCLASS (ID) ENABLE;

--// TUNNEL_THEMATIC_SURFACE CONSTRAINT

ALTER TABLE TUNNEL_THEMATIC_SURFACE
ADD CONSTRAINT TUNNEL_THEMATIC_SURFACE_FK FOREIGN KEY (LOD2_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE TUNNEL_THEMATIC_SURFACE
ADD CONSTRAINT TUNNEL_THEMATIC_SURFACE_FK1 FOREIGN KEY (LOD3_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE TUNNEL_THEMATIC_SURFACE
ADD CONSTRAINT TUNNEL_THEMATIC_SURFACE_FK2 FOREIGN KEY (LOD4_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY(ID) ENABLE;

ALTER TABLE TUNNEL_THEMATIC_SURFACE
ADD CONSTRAINT TUNNEL_THEMATIC_SURFACE_FK3 FOREIGN KEY (ID)
REFERENCES CITYOBJECT (ID) ENABLE;

ALTER TABLE TUNNEL_THEMATIC_SURFACE
ADD CONSTRAINT TUNNEL_THEMATIC_SURFACE_FK4 FOREIGN KEY (TUNNEL_HOLLOWSPACE_ID)
REFERENCES TUNNEL_HOLLOWSPACE (ID) ENABLE;

ALTER TABLE TUNNEL_THEMATIC_SURFACE
ADD CONSTRAINT TUNNEL_THEMATIC_SURFACE_FK5 FOREIGN KEY (TUNNEL_INSTALLATION_ID)
REFERENCES TUNNEL_INSTALLATION (ID) ENABLE;

ALTER TABLE TUNNEL_THEMATIC_SURFACE
ADD CONSTRAINT TUNNEL_THEMATIC_SURFACE_FK6 FOREIGN KEY (TUNNEL_ID)
REFERENCES TUNNEL (ID) ENABLE;

ALTER TABLE TUNNEL_THEMATIC_SURFACE
ADD CONSTRAINT TUNNEL_THEMATIC_SURFACE_FK7 FOREIGN KEY (OBJECTCLASS_ID)
REFERENCES OBJECTCLASS (ID) ENABLE;

--// TUNNEL CONSTRAINT

ALTER TABLE TUNNEL
ADD CONSTRAINT TUNNEL_CITYOBJECT_FK FOREIGN KEY (ID)
REFERENCES CITYOBJECT (ID) ENABLE;

ALTER TABLE TUNNEL
ADD CONSTRAINT TUNNEL_SURFACE_GEOMETRY_FK FOREIGN KEY (LOD1_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE TUNNEL
ADD CONSTRAINT TUNNEL_SURFACE_GEOMETRY_FK1 FOREIGN KEY (LOD2_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE TUNNEL
ADD CONSTRAINT TUNNEL_SURFACE_GEOMETRY_FK2 FOREIGN KEY (LOD3_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE TUNNEL
ADD CONSTRAINT TUNNEL_SURFACE_GEOMETRY_FK3 FOREIGN KEY (LOD4_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE TUNNEL
ADD CONSTRAINT TUNNEL_SURFACE_GEOMETRY_FK4 FOREIGN KEY (LOD1_SOLID_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE TUNNEL
ADD CONSTRAINT TUNNEL_SURFACE_GEOMETRY_FK5 FOREIGN KEY (LOD2_SOLID_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE TUNNEL
ADD CONSTRAINT TUNNEL_SURFACE_GEOMETRY_FK6 FOREIGN KEY (LOD3_SOLID_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE TUNNEL
ADD CONSTRAINT TUNNEL_SURFACE_GEOMETRY_FK7 FOREIGN KEY (LOD4_SOLID_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE TUNNEL
ADD CONSTRAINT TUNNEL_TUNNEL_FK FOREIGN KEY (TUNNEL_PARENT_ID)
REFERENCES TUNNEL (ID) ENABLE;

ALTER TABLE TUNNEL
ADD CONSTRAINT TUNNEL_TUNNEL_FK1 FOREIGN KEY (TUNNEL_ROOT_ID)
REFERENCES TUNNEL (ID) ENABLE;

--//WATERBODY CONSTRAINT

ALTER TABLE WATERBODY
ADD CONSTRAINT WATERBODY_CITYOBJECT_FK FOREIGN KEY (ID)
REFERENCES CITYOBJECT (ID) ENABLE;

ALTER TABLE WATERBODY
ADD CONSTRAINT WATERBODY_SURFACE_GEOMETRY_FK1 FOREIGN KEY (LOD2_SOLID_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE WATERBODY
ADD CONSTRAINT WATERBODY_SURFACE_GEOMETRY_FK2 FOREIGN KEY (LOD3_SOLID_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE WATERBODY
ADD CONSTRAINT WATERBODY_SURFACE_GEOMETRY_FK3 FOREIGN KEY (LOD4_SOLID_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE WATERBODY
ADD CONSTRAINT WATERBODY_SURFACE_GEOMETRY_FK4 FOREIGN KEY (LOD0_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE WATERBODY
ADD CONSTRAINT WATERBODY_SURFACE_GEOMETRY_FK5 FOREIGN KEY (LOD1_MULTI_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE WATERBODY
ADD CONSTRAINT WATERBODY_SURFACE_GEOMETRY_FK FOREIGN KEY (LOD1_SOLID_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;


--//WATERBOD_TO_WATERBND_SRF CONSTRAINT

ALTER TABLE WATERBOD_TO_WATERBND_SRF
ADD CONSTRAINT WATERBOD_TO_WATERBND_FK FOREIGN KEY (WATERBOUNDARY_SURFACE_ID)
REFERENCES WATERBOUNDARY_SURFACE (ID) ENABLE;

ALTER TABLE WATERBOD_TO_WATERBND_SRF
ADD CONSTRAINT WATERBOD_TO_WATERBND_FK1 FOREIGN KEY (WATERBODY_ID)
REFERENCES WATERBODY (ID) ENABLE;

--//WATERBOUNDARY_SURFACE CONSTRAINT

ALTER TABLE WATERBOUNDARY_SURFACE
ADD CONSTRAINT WATERBOUNDARY_SRF_CITYOBJ_FK FOREIGN KEY (ID)
REFERENCES CITYOBJECT (ID) ENABLE;

ALTER TABLE WATERBOUNDARY_SURFACE
ADD CONSTRAINT WATERBOUNDARY_SURFACE_FK FOREIGN KEY (LOD2_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE WATERBOUNDARY_SURFACE
ADD CONSTRAINT WATERBOUNDARY_SURFACE_FK1 FOREIGN KEY (LOD3_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE WATERBOUNDARY_SURFACE
ADD CONSTRAINT WATERBOUNDARY_SURFACE_FK2 FOREIGN KEY (LOD4_SURFACE_ID)
REFERENCES SURFACE_GEOMETRY (ID) ENABLE;

ALTER TABLE WATERBOUNDARY_SURFACE
ADD CONSTRAINT WATERBOUNDARY_SURFACE_FK3 FOREIGN KEY (OBJECTCLASS_ID)
REFERENCES OBJECTCLASS (ID) ENABLE;





















