CREATE TABLE APPEAR_TO_SURFACE_DATA 
(
  SURFACE_DATA_ID NUMBER NOT NULL 
, APPEARANCE_ID NUMBER NOT NULL 
, CONSTRAINT APPEAR_TO_SURFACE_DATA_PK PRIMARY KEY 
  (
    SURFACE_DATA_ID 
  , APPEARANCE_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX APPEAR_TO_SURFACE_DATA_PK ON APPEAR_TO_SURFACE_DATA (SURFACE_DATA_ID ASC, APPEARANCE_ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX APP_TO_SURF_DATA_FKX ON APPEAR_TO_SURFACE_DATA (SURFACE_DATA_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX APP_TO_SURF_DATA_FKX1 ON APPEAR_TO_SURFACE_DATA (APPEARANCE_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

ALTER TABLE APPEAR_TO_SURFACE_DATA
ADD CONSTRAINT APPEAR_TO_SURFACE_DATA_FK FOREIGN KEY
(
  SURFACE_DATA_ID 
)
REFERENCES SURFACE_DATA
(
  ID 
)
ENABLE;

ALTER TABLE APPEAR_TO_SURFACE_DATA
ADD CONSTRAINT APPEAR_TO_SURFACE_DATA_FK1 FOREIGN KEY
(
  APPEARANCE_ID 
)
REFERENCES APPEARANCE
(
  ID 
)
ENABLE;
