CREATE TABLE DEFAULTSCHEMA.TEX_IMAGE 
(
  ID NUMBER NOT NULL 
, TEX_IMAGE_URI VARCHAR2(4000) 
, TEX_IMAGE ORDSYS.ORDIMAGE 
, TEX_MIME_TYPE VARCHAR2(256) 
, TEX_MIME_TYPE_CODESPACE VARCHAR2(4000) 
, CONSTRAINT TEX_IMAGE_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX DEFAULTSCHEMA.TEX_IMAGE_PK ON DEFAULTSCHEMA.TEX_IMAGE (ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
);
