CREATE TABLE TEXTUREPARAM 
(
  SURFACE_GEOMETRY_ID NUMBER NOT NULL 
, IS_TEXTURE_PARAMETRIZATION NUMBER(1, 0) 
, WORLD_TO_TEXTURE VARCHAR2(1000) 
, TEXTURE_COORDINATES MDSYS.SDO_GEOMETRY 
, SURFACE_DATA_ID NUMBER NOT NULL 
, CONSTRAINT TEXTUREPARAM_PK PRIMARY KEY 
  (
    SURFACE_GEOMETRY_ID 
  , SURFACE_DATA_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX TEXTUREPARAM_PK ON TEXTUREPARAM (SURFACE_GEOMETRY_ID ASC, SURFACE_DATA_ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX TEXTUREPARAM_FKX ON TEXTUREPARAM (SURFACE_GEOMETRY_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX TEXTUREPARAM_FKX1 ON TEXTUREPARAM (SURFACE_DATA_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

ALTER TABLE TEXTUREPARAM
ADD CONSTRAINT TEXTUREPARAM_SURFACE_DATA_FK FOREIGN KEY
(
  SURFACE_DATA_ID 
)
REFERENCES SURFACE_DATA
(
  ID 
)
ENABLE;

ALTER TABLE TEXTUREPARAM
ADD CONSTRAINT TEXTUREPARAM_SURFACE_GEOM_FK FOREIGN KEY
(
  SURFACE_GEOMETRY_ID 
)
REFERENCES SURFACE_GEOMETRY
(
  ID 
)
ENABLE;
