CREATE TABLE BREAKLINE_RELIEF 
(
  ID NUMBER NOT NULL 
, RIDGE_OR_VALLEY_LINES MDSYS.SDO_GEOMETRY 
, BREAK_LINES MDSYS.SDO_GEOMETRY 
, CONSTRAINT BREAKLINE_RELIEF_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX BREAKLINE_RELIEF_PK ON BREAKLINE_RELIEF (ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX BREAKLINE_BREAK_SPX ON BREAKLINE_RELIEF (BREAK_LINES) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE INDEX BREAKLINE_RID_SPX ON BREAKLINE_RELIEF (RIDGE_OR_VALLEY_LINES) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

ALTER TABLE BREAKLINE_RELIEF
ADD CONSTRAINT BREAKLINE_RELIEF_FK FOREIGN KEY
(
  ID 
)
REFERENCES RELIEF_COMPONENT
(
  ID 
)
ENABLE;
