CREATE TABLE MASSPOINT_RELIEF 
(
  ID NUMBER NOT NULL 
, RELIEF_POINTS MDSYS.SDO_GEOMETRY 
, CONSTRAINT MASSPOINT_RELIEF_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX MASSPOINT_RELIEF_PK ON MASSPOINT_RELIEF (ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX MASSPOINT_REL_SPX ON MASSPOINT_RELIEF (RELIEF_POINTS) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

ALTER TABLE MASSPOINT_RELIEF
ADD CONSTRAINT MASSPOINT_RELIEF_FK FOREIGN KEY
(
  ID 
)
REFERENCES RELIEF_COMPONENT
(
  ID 
)
ENABLE;
