CREATE TABLE RASTER_RELIEF_GEORASTER 
(
  ID NUMBER NOT NULL 
, RASTERPROPERTY MDSYS.SDO_GEORASTER NOT NULL 
, CONSTRAINT RASTER_RLF_GEORASTER_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX RASTER_RLF_GEORASTER_PK ON RASTER_RELIEF_GEORASTER (ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
);
