CREATE TABLE RASTER_RELIEF 
(
  ID NUMBER NOT NULL 
, URI VARCHAR2(4000) 
, GEORASTER_ID NUMBER 
, CONSTRAINT RASTER_RLF_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX RASTER_RLF_PK ON RASTER_RELIEF (ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX RASTER_RELIEF_FKX1 ON RASTER_RELIEF (GEORASTER_ID);

ALTER TABLE RASTER_RELIEF
ADD CONSTRAINT RASTER_RELIEF_FK FOREIGN KEY
(
  ID 
)
REFERENCES RELIEF_COMPONENT
(
  ID 
)
ENABLE;

ALTER TABLE RASTER_RELIEF
ADD CONSTRAINT RASTER_RELIEF_FK1 FOREIGN KEY
(
  GEORASTER_ID 
)
REFERENCES RASTER_RELIEF_GEORASTER
(
  ID 
)
ENABLE;
