CREATE TABLE RELIEF_FEAT_TO_REL_COMP 
(
  RELIEF_COMPONENT_ID NUMBER NOT NULL 
, RELIEF_FEATURE_ID NUMBER NOT NULL 
, CONSTRAINT RELIEF_FEAT_TO_REL_COMP_PK PRIMARY KEY 
  (
    RELIEF_COMPONENT_ID 
  , RELIEF_FEATURE_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX RELIEF_FEAT_TO_REL_COMP_PK ON RELIEF_FEAT_TO_REL_COMP (RELIEF_COMPONENT_ID ASC, RELIEF_FEATURE_ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

ALTER TABLE RELIEF_FEAT_TO_REL_COMP
ADD CONSTRAINT RELIEF_FEAT_TO_REL_COMP_FK FOREIGN KEY
(
  RELIEF_COMPONENT_ID 
)
REFERENCES RELIEF_COMPONENT
(
  ID 
)
ENABLE;

ALTER TABLE RELIEF_FEAT_TO_REL_COMP
ADD CONSTRAINT RELIEF_FEAT_TO_REL_COMP_FK1 FOREIGN KEY
(
  RELIEF_FEATURE_ID 
)
REFERENCES RELIEF_FEATURE
(
  ID 
)
ENABLE;
