CREATE TABLE RELIEF_COMPONENT 
(
  ID NUMBER NOT NULL 
, LOD NUMBER(1) 
, EXTENT MDSYS.SDO_GEOMETRY 
, OBJECTCLASS_ID NUMBER 
, CONSTRAINT RELIEF_COMPONENT_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX RELIEF_COMPONENT_PK ON RELIEF_COMPONENT (ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX RELIEF_COMPONENT_FK1 ON RELIEF_COMPONENT (OBJECTCLASS_ID);

CREATE INDEX RELIEF_COMPONENT_SPX ON RELIEF_COMPONENT (EXTENT) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

ALTER TABLE RELIEF_COMPONENT
ADD CONSTRAINT RELIEF_COMPONENT_CITYOBJECT_FK FOREIGN KEY
(
  ID 
)
REFERENCES CITYOBJECT
(
  ID 
)
ENABLE;

ALTER TABLE RELIEF_COMPONENT
ADD CONSTRAINT RELIEF_COMPONENT_OBJCLASS_FK FOREIGN KEY
(
  OBJECTCLASS_ID 
)
REFERENCES OBJECTCLASS
(
  ID 
)
ENABLE;

ALTER TABLE RELIEF_COMPONENT
ADD CONSTRAINT RELIEF_COMPONENT_CHK1 CHECK 
(LOD >= 0 AND LOD < 5)
ENABLE;
