CREATE TABLE RELIEF_FEATURE 
(
  ID NUMBER NOT NULL 
, LOD NUMBER(1) 
, CONSTRAINT RELIEF_FEATURE_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX RELIEF_FEATURE_PK ON RELIEF_FEATURE (ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

ALTER TABLE RELIEF_FEATURE
ADD CONSTRAINT RELIEF_FEATURE_CITYOBJECT_FK FOREIGN KEY
(
  ID 
)
REFERENCES CITYOBJECT
(
  ID 
)
ENABLE;

ALTER TABLE RELIEF_FEATURE
ADD CONSTRAINT RELIEF_FEATURE_CHK1 CHECK 
(LOD >= 0 AND LOD < 5)
ENABLE;
