CREATE TABLE TIN_RELIEF 
(
  ID NUMBER NOT NULL 
, MAX_LENGTH BINARY_DOUBLE 
, STOP_LINES MDSYS.SDO_GEOMETRY 
, BREAK_LINES MDSYS.SDO_GEOMETRY 
, CONTROL_POINTS MDSYS.SDO_GEOMETRY 
, SURFACE_GEOMETRY_ID NUMBER 
, CONSTRAINT TIN_RELIEF_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX TIN_RELIEF_PK ON TIN_RELIEF (ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX TIN_RELF_BREAK_SPX ON TIN_RELIEF (BREAK_LINES) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE INDEX TIN_RELF_CRTLPTS_SPX ON TIN_RELIEF (CONTROL_POINTS) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE INDEX TIN_RELF_STOP_SPX ON TIN_RELIEF (STOP_LINES) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE INDEX TIN_RELIEF_FKX ON TIN_RELIEF (SURFACE_GEOMETRY_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
);

ALTER TABLE TIN_RELIEF
ADD CONSTRAINT TIN_RELIEF_RELIEF_COMPONENT_FK FOREIGN KEY
(
  ID 
)
REFERENCES RELIEF_COMPONENT
(
  ID 
)
ENABLE;

ALTER TABLE TIN_RELIEF
ADD CONSTRAINT TIN_RELIEF_SURFACE_GEOMETRY_FK FOREIGN KEY
(
  SURFACE_GEOMETRY_ID 
)
REFERENCES SURFACE_GEOMETRY
(
  ID 
)
ENABLE;
