CREATE TABLE CITYOBJECT_GENERICATTRIB 
(
  ID NUMBER NOT NULL 
, PARENT_GENATT_ID NUMBER 
, ROOT_GENATT_ID NUMBER 
, ATTRNAME VARCHAR2(256) NOT NULL 
, DATATYPE NUMBER(1) 
, STRVAL VARCHAR2(4000) 
, INTVAL NUMBER 
, REALVAL NUMBER 
, URIVAL VARCHAR2(4000) 
, DATEVAL DATE 
, GEOMVAL MDSYS.SDO_GEOMETRY 
, BLOBVAL BLOB 
, UNIT VARCHAR2(4000) 
, CITYOBJECT_ID NUMBER NOT NULL 
, SURFACE_GEOMETRY_ID NUMBER 
, GRP_CODESPACE VARCHAR2(4000) 
, CONSTRAINT CITYOBJ_GENERICATTRIB_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX CITYOBJ_GENERICATTRIB_PK ON CITYOBJECT_GENERICATTRIB (ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
LOB (BLOBVAL) STORE AS SYS_LOB0000115593C00017$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  RETENTION 
  NOCACHE 
  LOGGING 
  TABLESPACE "USERS" 
  STORAGE 
  ( 
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    BUFFER_POOL DEFAULT 
  )  
);

CREATE INDEX CITYOBJ_GENERICATTRIB_FKX ON CITYOBJECT_GENERICATTRIB (CITYOBJECT_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX CITYOBJ_GENERICATTRIB_FKX1 ON CITYOBJECT_GENERICATTRIB (SURFACE_GEOMETRY_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX CITYOBJ_GENERICATTRIB_FKX2 ON CITYOBJECT_GENERICATTRIB (PARENT_GENATT_ID);

CREATE INDEX CITYOBJ_GENERICATTRIB_FKX3 ON CITYOBJECT_GENERICATTRIB (ROOT_GENATT_ID ASC);

ALTER TABLE CITYOBJECT_GENERICATTRIB
ADD CONSTRAINT CITYOBJECT_GENERICATTRIB_FK FOREIGN KEY
(
  CITYOBJECT_ID 
)
REFERENCES CITYOBJECT
(
  ID 
)
ENABLE;

ALTER TABLE CITYOBJECT_GENERICATTRIB
ADD CONSTRAINT CITYOBJECT_GENERICATTRIB_FK1 FOREIGN KEY
(
  SURFACE_GEOMETRY_ID 
)
REFERENCES SURFACE_GEOMETRY
(
  ID 
)
ENABLE;

ALTER TABLE CITYOBJECT_GENERICATTRIB
ADD CONSTRAINT CITYOBJECT_GENERICATTRIB_FK2 FOREIGN KEY
(
  PARENT_GENATT_ID 
)
REFERENCES CITYOBJECT_GENERICATTRIB
(
  ID 
)
ENABLE;

ALTER TABLE CITYOBJECT_GENERICATTRIB
ADD CONSTRAINT CITYOBJECT_GENERICATTRIB_FK3 FOREIGN KEY
(
  ROOT_GENATT_ID 
)
REFERENCES CITYOBJECT_GENERICATTRIB
(
  ID 
)
ENABLE;
