CREATE TABLE WATERBOD_TO_WATERBND_SRF 
(
  WATERBOUNDARY_SURFACE_ID NUMBER NOT NULL 
, WATERBODY_ID NUMBER NOT NULL 
, CONSTRAINT WATERBOD_TO_WATERBND_PK PRIMARY KEY 
  (
    WATERBOUNDARY_SURFACE_ID 
  , WATERBODY_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX WATERBOD_TO_WATERBND_PK ON WATERBOD_TO_WATERBND_SRF (WATERBOUNDARY_SURFACE_ID ASC, WATERBODY_ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

ALTER TABLE WATERBOD_TO_WATERBND_SRF
ADD CONSTRAINT WATERBOD_TO_WATERBND_FK FOREIGN KEY
(
  WATERBOUNDARY_SURFACE_ID 
)
REFERENCES WATERBOUNDARY_SURFACE
(
  ID 
)
ENABLE;

ALTER TABLE WATERBOD_TO_WATERBND_SRF
ADD CONSTRAINT WATERBOD_TO_WATERBND_FK1 FOREIGN KEY
(
  WATERBODY_ID 
)
REFERENCES WATERBODY
(
  ID 
)
ENABLE;
