CREATE TABLE WATERBODY 
(
  ID NUMBER NOT NULL 
, CLASS VARCHAR2(256) 
, CLASS_CODESPACE VARCHAR2(4000) 
, FUNCTION VARCHAR2(1000) 
, FUNCTION_CODESPACE VARCHAR2(4000) 
, USAGE VARCHAR2(1000) 
, USAGE_CODESPACE VARCHAR2(4000) 
, LOD0_MULTI_CURVE MDSYS.SDO_GEOMETRY 
, LOD1_MULTI_CURVE MDSYS.SDO_GEOMETRY 
, LOD1_SOLID_ID NUMBER 
, LOD2_SOLID_ID NUMBER 
, LOD3_SOLID_ID NUMBER 
, LOD4_SOLID_ID NUMBER 
, LOD0_MULTI_SURFACE_ID NUMBER 
, LOD1_MULTI_SURFACE_ID NUMBER 
, CONSTRAINT WATERBODY_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX WATERBODY_PK ON WATERBODY (ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX WATERBODY_FKX ON WATERBODY (LOD1_SOLID_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX WATERBODY_FKX1 ON WATERBODY (LOD2_SOLID_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX WATERBODY_FKX2 ON WATERBODY (LOD3_SOLID_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX WATERBODY_FKX3 ON WATERBODY (LOD4_SOLID_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX WATERBODY_FKX4 ON WATERBODY (LOD0_MULTI_SURFACE_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX WATERBODY_FKX5 ON WATERBODY (LOD1_MULTI_SURFACE_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX WATERBODY_LOD0MULTI_SPX ON WATERBODY (LOD0_MULTI_CURVE) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE INDEX WATERBODY_LOD1MULTI_SPX ON WATERBODY (LOD1_MULTI_CURVE) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

ALTER TABLE WATERBODY
ADD CONSTRAINT WATERBODY_CITYOBJECT_FK FOREIGN KEY
(
  ID 
)
REFERENCES CITYOBJECT
(
  ID 
)
ENABLE;

ALTER TABLE WATERBODY
ADD CONSTRAINT WATERBODY_SURFACE_GEOMETRY_FK FOREIGN KEY
(
  LOD1_SOLID_ID 
)
REFERENCES SURFACE_GEOMETRY
(
  ID 
)
ENABLE;

ALTER TABLE WATERBODY
ADD CONSTRAINT WATERBODY_SURFACE_GEOMETRY_FK1 FOREIGN KEY
(
  LOD2_SOLID_ID 
)
REFERENCES SURFACE_GEOMETRY
(
  ID 
)
ENABLE;

ALTER TABLE WATERBODY
ADD CONSTRAINT WATERBODY_SURFACE_GEOMETRY_FK2 FOREIGN KEY
(
  LOD3_SOLID_ID 
)
REFERENCES SURFACE_GEOMETRY
(
  ID 
)
ENABLE;

ALTER TABLE WATERBODY
ADD CONSTRAINT WATERBODY_SURFACE_GEOMETRY_FK3 FOREIGN KEY
(
  LOD4_SOLID_ID 
)
REFERENCES SURFACE_GEOMETRY
(
  ID 
)
ENABLE;

ALTER TABLE WATERBODY
ADD CONSTRAINT WATERBODY_SURFACE_GEOMETRY_FK4 FOREIGN KEY
(
  LOD0_MULTI_SURFACE_ID 
)
REFERENCES SURFACE_GEOMETRY
(
  ID 
)
ENABLE;

ALTER TABLE WATERBODY
ADD CONSTRAINT WATERBODY_SURFACE_GEOMETRY_FK5 FOREIGN KEY
(
  LOD1_MULTI_SURFACE_ID 
)
REFERENCES SURFACE_GEOMETRY
(
  ID 
)
ENABLE;
