-- SIMPLE_INDEX.sql
--
-- Authors:     Prof. Dr. Thomas H. Kolbe <thomas.kolbe@tum.de>
--              Zhihang Yao <zhihang.yao@tum.de>
--              Claus Nagel <cnagel@virtualcitysystems.de>
--              Philipp Willkomm <pwillkomm@moss.de>
--              Gerhard König <gerhard.koenig@tu-berlin.de>
--              Alexandra Lorenz <di.alex.lorenz@googlemail.com>
--
-- Copyright:   (c) 2012-2014  Chair of Geoinformatics,
--                             Technische Universität München, Germany
--                             http://www.gis.bv.tum.de
--
--              (c) 2007-2012  Institute for Geodesy and Geoinformation Science,
--                             Technische Universität Berlin, Germany
--                             http://www.igg.tu-berlin.de
--
--              This skript is free software under the LGPL Version 2.1.
--              See the GNU Lesser General Public License at
--              http://www.gnu.org/copyleft/lgpl.html
--              for more details.
-------------------------------------------------------------------------------
-- About:
--
--
-------------------------------------------------------------------------------
--
-- ChangeLog:
--
-- Version | Date       | Description                               | Author
-- 3.0.0     2013-12-06   new version for 3DCityDB V3                 ZYao
--                                                                    TKol
--                                                                    CNag
--                                                                    PWil
-- 2.0.0     2007-11-23   release version                             TKol
--                                                                    GKoe
--                                                                    CNag
--                                                                    ALor
--
CREATE INDEX ADDRESS_TO_BUILDING_FKX ON ADDRESS_TO_BUILDING (BUILDING_ID);
CREATE INDEX ADDRESS_TO_BUILDING_FKX1 ON ADDRESS_TO_BUILDING (ADDRESS_ID);

CREATE INDEX ADDRESS_TO_BRIDGE_FKX ON ADDRESS_TO_BRIDGE (BIRDGE_ID)
CREATE INDEX ADDRESS_TO_BRIDGE_FKX1 ON ADDRESS_TO_BRIDGE (ADDRESS_ID) 

CREATE INDEX APPEARANCE_FKX ON APPEARANCE (CITYMODEL_ID);
CREATE INDEX APPEARANCE_FKX1 ON APPEARANCE (CITYOBJECT_ID);
CREATE UNIQUE INDEX APPEARANCE_INX ON APPEARANCE (GMLID);

CREATE INDEX BUILDING_FKX ON BUILDING (LOD1_SOLID_ID);
CREATE INDEX BUILDING_FKX1 ON BUILDING (LOD2_SOLID_ID);
CREATE INDEX BUILDING_FKX2 ON BUILDING (LOD3_SOLID_ID);
CREATE INDEX BUILDING_FKX3 ON BUILDING (LOD4_SOLID_ID);
CREATE INDEX BUILDING_FKX4 ON BUILDING (BUILDING_ROOT_ID);
CREATE INDEX BUILDING_FKX5 ON BUILDING (BUILDING_PARENT_ID);
CREATE INDEX BUILDING_FKX6 ON BUILDING (LOD0_FOOTPRINT_ID);
CREATE INDEX BUILDING_FKX7 ON BUILDING (LOD0_ROOFPRINT_ID);
CREATE INDEX BUILDING_FKX8 ON BUILDING (LOD1_MULTI_SURFACE_ID);
CREATE INDEX BUILDING_FKX9 ON BUILDING (LOD2_MULTI_SURFACE_ID);
CREATE INDEX BUILDING_FKX10 ON BUILDING (LOD3_MULTI_SURFACE_ID);
CREATE INDEX BUILDING_FKX11 ON BUILDING (LOD4_MULTI_SURFACE_ID);

CREATE INDEX BUILDING_FURNITURE_FKX ON BUILDING_FURNITURE (LOD4_BREP_ID);
CREATE INDEX BUILDING_FURNITURE_FKX1 ON BUILDING_FURNITURE (LOD4_IMPLICIT_REP_ID);
CREATE INDEX BUILDING_FURNITURE_FKX2 ON BUILDING_FURNITURE (ROOM_ID);

CREATE INDEX BUILDING_INSTALLATION_FKX ON BUILDING_INSTALLATION (LOD3_BREP_ID);
CREATE INDEX BUILDING_INSTALLATION_FKX1 ON BUILDING_INSTALLATION (ROOM_ID);
CREATE INDEX BUILDING_INSTALLATION_FKX2 ON BUILDING_INSTALLATION (LOD4_BREP_ID);
CREATE INDEX BUILDING_INSTALLATION_FKX3 ON BUILDING_INSTALLATION (LOD2_BREP_ID);
CREATE INDEX BUILDING_INSTALLATION_FKX4 ON BUILDING_INSTALLATION (BUILDING_ID);
CREATE INDEX BUILDING_INSTALLATION_FKX5 ON BUILDING_INSTALLATION (LOD2_IMPLICIT_REP_ID);
CREATE INDEX BUILDING_INSTALLATION_FKX6 ON BUILDING_INSTALLATION (LOD3_IMPLICIT_REP_ID);
CREATE INDEX BUILDING_INSTALLATION_FKX7 ON BUILDING_INSTALLATION (LOD4_IMPLICIT_REP_ID);

CREATE INDEX BRD_CONSTR_ELEMENT_FK1 ON BRD_CONSTR_ELEMENT (LOD1_BREP_ID);
CREATE INDEX BRD_CONSTR_ELEMENT_FK2 ON BRD_CONSTR_ELEMENT (LOD4_BREP_ID);
CREATE INDEX BRD_CONSTR_ELEMENT_FK3 ON BRD_CONSTR_ELEMENT (LOD2_BREP_ID); 
CREATE INDEX BRD_CONSTR_ELEMENT_FK4 ON BRD_CONSTR_ELEMENT (BRIDGE_ID); 
CREATE INDEX BRD_CONSTR_ELEMENT_FK5 ON BRD_CONSTR_ELEMENT (LOD1_IMPLICIT_REP_ID);
CREATE INDEX BRD_CONSTR_ELEMENT_FK6 ON BRD_CONSTR_ELEMENT (LOD2_IMPLICIT_REP_ID);
CREATE INDEX BRD_CONSTR_ELEMENT_FK7 ON BRD_CONSTR_ELEMENT (LOD3_IMPLICIT_REP_ID);
CREATE INDEX BRD_CONSTR_ELEMENT_FK8 ON BRD_CONSTR_ELEMENT (LOD4_IMPLICIT_REP_ID);
CREATE INDEX BRD_CONSTR_ELEMENT_FK9 ON BRD_CONSTR_ELEMENT (LOD3_BREP_ID) 

CREATE INDEX BRD_THEMATIC_SURFACE_FKX ON BRD_THEMATIC_SURFACE (BRIDGE_ROOM_ID);
CREATE INDEX BRD_THEMATIC_SURFACE_FKX1 ON BRD_THEMATIC_SURFACE (BRIDGE_ID);
CREATE INDEX BRD_THEMATIC_SURFACE_FKX2 ON BRD_THEMATIC_SURFACE (LOD2_MULTI_SURFACE_ID);
CREATE INDEX BRD_THEMATIC_SURFACE_FKX3 ON BRD_THEMATIC_SURFACE (LOD3_MULTI_SURFACE_ID);
CREATE INDEX BRD_THEMATIC_SURFACE_FKX4 ON BRD_THEMATIC_SURFACE (LOD4_MULTI_SURFACE_ID);
CREATE INDEX BRD_THEMATIC_SURFACE_FKX5 ON BRD_THEMATIC_SURFACE (BRIDGE_INSTALLATION_ID);
CREATE INDEX BRD_THEMATIC_SURFACE_FKX6 ON BRD_THEMATIC_SURFACE (BRIDGE_CONSTR_ELEM_ID);
CREATE INDEX BRD_THEMATIC_SURFACE_FKX7 ON BRD_THEMATIC_SURFACE (OBJECTCLASS_ID);

CREATE INDEX BRIDGE_FURNITURE_FKX ON BRIDGE_FURNITURE (LOD4_BREP_ID);
CREATE INDEX BRIDGE_FURNITURE_FKX1 ON BRIDGE_FURNITURE (LOD4_IMPLICIT_REP_ID);
CREATE INDEX BRIDGE_FURNITURE_FKX2 ON BRIDGE_FURNITURE (BRIDGE_ROOM_ID);

CREATE INDEX BRIDGE_INSTALLATION_FKX ON BRIDGE_INSTALLATION (LOD3_BREP_ID);
CREATE INDEX BRIDGE_INSTALLATION_FKX1 ON BRIDGE_INSTALLATION (BRIDGE_ROOM_ID);
CREATE INDEX BRIDGE_INSTALLATION_FKX2 ON BRIDGE_INSTALLATION (LOD4_BREP_ID);
CREATE INDEX BRIDGE_INSTALLATION_FKX3 ON BRIDGE_INSTALLATION (LOD2_BREP_ID);
CREATE INDEX BRIDGE_INSTALLATION_FKX4 ON BRIDGE_INSTALLATION (BRIDGE_ID);
CREATE INDEX BRIDGE_INSTALLATION_FKX5 ON BRIDGE_INSTALLATION (LOD2_IMPLICIT_REP_ID);
CREATE INDEX BRIDGE_INSTALLATION_FKX6 ON BRIDGE_INSTALLATION (LOD3_IMPLICIT_REP_ID);
CREATE INDEX BRIDGE_INSTALLATION_FKX7 ON BRIDGE_INSTALLATION (LOD4_IMPLICIT_REP_ID);

CREATE INDEX BRIDGE_OPENING_FKX ON BRIDGE_OPENING (ADDRESS_ID);
CREATE INDEX BRIDGE_OPENING_FKX1 ON BRIDGE_OPENING (LOD3_MULTI_SURFACE_ID);
CREATE INDEX BRIDGE_OPENING_FKX2 ON BRIDGE_OPENING (LOD4_MULTI_SURFACE_ID);
CREATE INDEX BRIDGE_OPENING_FKX3 ON BRIDGE_OPENING (LOD3_IMPLICIT_REP_ID);
CREATE INDEX BRIDGE_OPENING_FKX4 ON BRIDGE_OPENING (LOD4_IMPLICIT_REP_ID);
CREATE INDEX BRIDGE_OPENING_FKX5 ON BRIDGE_OPENING (OBJECTCLASS_ID ASC);

CREATE INDEX BRIDGE_ROOM_FKX ON BRIDGE_ROOM (BRIDGE_ID);
CREATE INDEX BRIDGE_ROOM_FKX1 ON BRIDGE_ROOM (LOD4_SOLID_ID);
CREATE INDEX BRIDGE_ROOM_FKX2 ON BRIDGE_ROOM (LOD4_MULTI_SURFACE_ID);

CREATE INDEX BRIDGE_FKX ON BRIDGE (LOD1_MULTI_SURFACE_ID);
CREATE INDEX BRIDGE_FKX1 ON BRIDGE (LOD2_MULTI_SURFACE_ID);
CREATE INDEX BRIDGE_FKX2 ON BRIDGE (LOD3_MULTI_SURFACE_ID);
CREATE INDEX BRIDGE_FKX3 ON BRIDGE (LOD4_MULTI_SURFACE_ID);
CREATE INDEX BRIDGE_FKX4 ON BRIDGE (BRIDGE_ROOT_ID);
CREATE INDEX BRIDGE_FKX5 ON BRIDGE (BRIDGE_PARENT_ID);
CREATE INDEX BRIDGE_FKX6 ON BRIDGE (LOD1_SOLID_ID ASC);
CREATE INDEX BRIDGE_FKX7 ON BRIDGE (LOD2_SOLID_ID ASC);
CREATE INDEX BRIDGE_FKX8 ON BRIDGE (LOD3_SOLID_ID ASC);
CREATE INDEX BRIDGE_FKX9 ON BRIDGE (LOD4_SOLID_ID ASC);

CREATE UNIQUE INDEX CITYMODEL_INX ON CITYMODEL (GMLID);

CREATE INDEX CITYOBJECT_FKX ON CITYOBJECT (CLASS_ID);
CREATE UNIQUE INDEX CITYOBJECT_INX ON CITYOBJECT (GMLID);

CREATE INDEX CITYOBJECTGROUP_FKX ON CITYOBJECTGROUP (BREP_ID);
CREATE INDEX CITYOBJECTGROUP_FKX1 ON CITYOBJECTGROUP (PARENT_CITYOBJECT_ID);

CREATE INDEX CITYOBJ_GENERICATTRIB_FKX ON CITYOBJECT_GENERICATTRIB (CITYOBJECT_ID);
CREATE INDEX CITYOBJ_GENERICATTRIB_FKX1 ON CITYOBJECT_GENERICATTRIB (SURFACE_GEOMETRY_ID);
CREATE INDEX CITYOBJ_GENERICATTRIB_FKX2 ON CITYOBJECT_GENERICATTRIB (PARENT_GENATT_ID);
CREATE INDEX CITYOBJ_GENERICATTRIB_FKX3 ON CITYOBJECT_GENERICATTRIB (ROOT_GENATT_ID);

CREATE INDEX CITY_FURNITURE_FKX ON CITY_FURNITURE (LOD1_BREP_ID);
CREATE INDEX CITY_FURNITURE_FKX1 ON CITY_FURNITURE (LOD2_BREP_ID);
CREATE INDEX CITY_FURNITURE_FKX2 ON CITY_FURNITURE (LOD3_BREP_ID);
CREATE INDEX CITY_FURNITURE_FKX3 ON CITY_FURNITURE (LOD4_BREP_ID);
CREATE INDEX CITY_FURNITURE_FKX4 ON CITY_FURNITURE (LOD1_IMPLICIT_REP_ID);
CREATE INDEX CITY_FURNITURE_FKX5 ON CITY_FURNITURE (LOD2_IMPLICIT_REP_ID);
CREATE INDEX CITY_FURNITURE_FKX6 ON CITY_FURNITURE (LOD3_IMPLICIT_REP_ID);
CREATE INDEX CITY_FURNITURE_FKX7 ON CITY_FURNITURE (LOD4_IMPLICIT_REP_ID);

CREATE INDEX EXTERNAL_REFERENCE_FKX ON EXTERNAL_REFERENCE (CITYOBJECT_ID);

CREATE INDEX GENERIC_CITYOBJECT_FKX ON GENERIC_CITYOBJECT (LOD0_IMPLICIT_REP_ID);
CREATE INDEX GENERIC_CITYOBJECT_FKX1 ON GENERIC_CITYOBJECT (LOD1_IMPLICIT_REP_ID);
CREATE INDEX GENERIC_CITYOBJECT_FKX2 ON GENERIC_CITYOBJECT (LOD2_IMPLICIT_REP_ID);
CREATE INDEX GENERIC_CITYOBJECT_FKX3 ON GENERIC_CITYOBJECT (LOD3_IMPLICIT_REP_ID);
CREATE INDEX GENERIC_CITYOBJECT_FKX4 ON GENERIC_CITYOBJECT (LOD4_IMPLICIT_REP_ID);
CREATE INDEX GENERIC_CITYOBJECT_FKX5 ON GENERIC_CITYOBJECT (LOD0_BREP_ID);
CREATE INDEX GENERIC_CITYOBJECT_FKX6 ON GENERIC_CITYOBJECT (LOD1_BREP_ID);
CREATE INDEX GENERIC_CITYOBJECT_FKX7 ON GENERIC_CITYOBJECT (LOD2_BREP_ID);
CREATE INDEX GENERIC_CITYOBJECT_FKX8 ON GENERIC_CITYOBJECT (LOD3_BREP_ID);
CREATE INDEX GENERIC_CITYOBJECT_FKX9 ON GENERIC_CITYOBJECT (LOD4_BREP_ID);

CREATE INDEX GTCO_COGID_IDX ON GROUP_TO_CITYOBJECT (CITYOBJECTGROUP_ID);

CREATE INDEX IMPLICIT_GEOMETRY_FKX ON IMPLICIT_GEOMETRY (RELATIVE_BREP_ID);
CREATE INDEX IMPLICIT_GEOMETRY_INX ON IMPLICIT_GEOMETRY (REFERENCE_TO_LIBRARY);

CREATE INDEX LAND_USE_FKX ON LAND_USE (LOD0_MULTI_SURFACE_ID);
CREATE INDEX LAND_USE_FKX1 ON LAND_USE (LOD1_MULTI_SURFACE_ID);
CREATE INDEX LAND_USE_FKX2 ON LAND_USE (LOD2_MULTI_SURFACE_ID);
CREATE INDEX LAND_USE_FKX3 ON LAND_USE (LOD3_MULTI_SURFACE_ID);
CREATE INDEX LAND_USE_FKX4 ON LAND_USE (LOD4_MULTI_SURFACE_ID);

CREATE INDEX OBJECTCLASS_FKX ON OBJECTCLASS (SUPERCLASS_ID);

CREATE INDEX OPENING_FKX ON OPENING (ADDRESS_ID);
CREATE INDEX OPENING_FKX1 ON OPENING (LOD3_MULTI_SURFACE_ID);
CREATE INDEX OPENING_FKX2 ON OPENING (LOD4_MULTI_SURFACE_ID);
CREATE INDEX OPENING_FKX3 ON OPENING (LOD3_IMPLICIT_REP_ID);
CREATE INDEX OPENING_FKX4 ON OPENING (LOD4_IMPLICIT_REP_ID);
CREATE INDEX OPENING_FKX5 ON OPENING (OBJECTCLASS_ID);

CREATE INDEX PLANT_COVER_FKX ON PLANT_COVER (LOD1_MULTI_SURFACE_ID);
CREATE INDEX PLANT_COVER_FKX1 ON PLANT_COVER (LOD2_MULTI_SURFACE_ID);
CREATE INDEX PLANT_COVER_FKX2 ON PLANT_COVER (LOD3_MULTI_SURFACE_ID);
CREATE INDEX PLANT_COVER_FKX3 ON PLANT_COVER (LOD4_MULTI_SURFACE_ID);
CREATE INDEX PLANT_COVER_FKX4 ON PLANT_COVER (LOD1_SOLID_ID);
CREATE INDEX PLANT_COVER_FKX5 ON PLANT_COVER (LOD2_SOLID_ID);
CREATE INDEX PLANT_COVER_FKX6 ON PLANT_COVER (LOD3_SOLID_ID);
CREATE INDEX PLANT_COVER_FKX7 ON PLANT_COVER (LOD4_SOLID_ID);

CREATE INDEX ROOM_FKX ON ROOM (BUILDING_ID);
CREATE INDEX ROOM_FKX1 ON ROOM (LOD4_SOLID_ID);
CREATE INDEX ROOM_FKX2 ON ROOM (LOD4_MULTI_SURFACE_ID);

CREATE INDEX RASTER_RELIEF_FKX1 ON RASTER_RELIEF (GEORASTER_ID);

CREATE INDEX RELIEF_COMPONENT_FK1 ON RELIEF_COMPONENT (OBJECTCLASS_ID);

CREATE INDEX SOLITARY_VEGETAT_OBJ_FKX1 ON SOLITARY_VEGETAT_OBJECT (LOD1_BREP_ID);
CREATE INDEX SOLITARY_VEGETAT_OBJ_FKX2 ON SOLITARY_VEGETAT_OBJECT (LOD2_BREP_ID);
CREATE INDEX SOLITARY_VEGETAT_OBJ_FKX3 ON SOLITARY_VEGETAT_OBJECT (LOD3_BREP_ID);
CREATE INDEX SOLITARY_VEGETAT_OBJ_FKX4 ON SOLITARY_VEGETAT_OBJECT (LOD4_BREP_ID);
CREATE INDEX SOLITARY_VEGETAT_OBJ_FKX5 ON SOLITARY_VEGETAT_OBJECT (LOD1_IMPLICIT_REP_ID);
CREATE INDEX SOLITARY_VEGETAT_OBJ_FKX6 ON SOLITARY_VEGETAT_OBJECT (LOD2_IMPLICIT_REP_ID);
CREATE INDEX SOLITARY_VEGETAT_OBJ_FKX7 ON SOLITARY_VEGETAT_OBJECT (LOD3_IMPLICIT_REP_ID);
CREATE INDEX SOLITARY_VEGETAT_OBJ_FKX8 ON SOLITARY_VEGETAT_OBJECT (LOD4_IMPLICIT_REP_ID);

CREATE UNIQUE INDEX SURFACE_DATA_INX ON SURFACE_DATA (GMLID);
CREATE INDEX SURFACE_DATA_FKX1 ON SURFACE_DATA (TEX_IMAGE_ID);
CREATE INDEX SURFACE_DATA_FKX2 ON SURFACE_DATA (OBJECTCLASS_ID);

CREATE INDEX APP_TO_SURF_DATA_FKX on APPEAR_TO_SURFACE_DATA (SURFACE_DATA_ID);
CREATE INDEX APP_TO_SURF_DATA_FKX1 on APPEAR_TO_SURFACE_DATA (APPEARANCE_ID);

CREATE INDEX SURFACE_GEOMETRY_FKX ON SURFACE_GEOMETRY (PARENT_ID);
CREATE INDEX SURFACE_GEOMETRY_FKX1 ON SURFACE_GEOMETRY (ROOT_ID);
CREATE INDEX SURFACE_GEOMETRY_FKX2 ON SURFACE_GEOMETRY (CITYOBJECT_ID);
CREATE UNIQUE INDEX SURFACE_GEOMETRY_INX ON SURFACE_GEOMETRY (GMLID);

CREATE INDEX TEXTUREPARAM_FKX ON TEXTUREPARAM (SURFACE_GEOMETRY_ID);
CREATE INDEX TEXTUREPARAM_FKX1 ON TEXTUREPARAM (SURFACE_DATA_ID);

CREATE INDEX THEMATIC_SURFACE_FKX ON THEMATIC_SURFACE (ROOM_ID);
CREATE INDEX THEMATIC_SURFACE_FKX1 ON THEMATIC_SURFACE (BUILDING_ID);
CREATE INDEX THEMATIC_SURFACE_FKX2 ON THEMATIC_SURFACE (LOD2_MULTI_SURFACE_ID);
CREATE INDEX THEMATIC_SURFACE_FKX3 ON THEMATIC_SURFACE (LOD3_MULTI_SURFACE_ID);
CREATE INDEX THEMATIC_SURFACE_FKX4 ON THEMATIC_SURFACE (LOD4_MULTI_SURFACE_ID);
CREATE INDEX THEMATIC_SURFACE_FKX5 ON THEMATIC_SURFACE (BUILDINGINSTALLATION_ID);
CREATE INDEX THEMATIC_SURFACE_FKX6 ON THEMATIC_SURFACE (OBJECTCLASS_ID);

CREATE INDEX TIN_RELIEF_FKX ON TIN_RELIEF (SURFACE_GEOMETRY_ID);

CREATE INDEX TRAFFIC_AREA_FKX ON TRAFFIC_AREA (LOD2_MULTI_SURFACE_ID);
CREATE INDEX TRAFFIC_AREA_FKX1 ON TRAFFIC_AREA (LOD3_MULTI_SURFACE_ID);
CREATE INDEX TRAFFIC_AREA_FKX2 ON TRAFFIC_AREA (LOD4_MULTI_SURFACE_ID);
CREATE INDEX TRAFFIC_AREA_FKX3 ON TRAFFIC_AREA (TRANSPORTATION_COMPLEX_ID);

CREATE INDEX TRAN_COMPLEX_FKX1 ON TRANSPORTATION_COMPLEX (LOD1_MULTI_SURFACE_ID);
CREATE INDEX TRAN_COMPLEX_FKX2 ON TRANSPORTATION_COMPLEX (LOD2_MULTI_SURFACE_ID);
CREATE INDEX TRAN_COMPLEX_FKX3 ON TRANSPORTATION_COMPLEX (LOD3_MULTI_SURFACE_ID);
CREATE INDEX TRAN_COMPLEX_FKX4 ON TRANSPORTATION_COMPLEX (LOD4_MULTI_SURFACE_ID);

CREATE INDEX TUNNEL_FURNITURE_FKX ON TUNNEL_FURNITURE (LOD4_BREP_ID);
CREATE INDEX TUNNEL_FURNITURE_FKX1 ON TUNNEL_FURNITURE (LOD4_IMPLICIT_REP_ID);
CREATE INDEX TUNNEL_FURNITURE_FKX2 ON TUNNEL_FURNITURE (TUNNEL_HOLLOWSPACE_ID);

CREATE INDEX TUNNEL_HOLLOWSPACE_FKX ON TUNNEL_HOLLOWSPACE (TUNNEL_ID);
CREATE INDEX TUNNEL_HOLLOWSPACE_FKX1 ON TUNNEL_HOLLOWSPACE (LOD4_MULTI_SURFACE_ID);
CREATE INDEX TUNNEL_HOLLOWSPACE_FKX2 ON TUNNEL_HOLLOWSPACE (LOD4_SOLID_ID);

CREATE INDEX TUNNEL_INSTALLATION_FKX ON TUNNEL_INSTALLATION (LOD3_BREP_ID);
CREATE INDEX TUNNEL_INSTALLATION_FKX1 ON TUNNEL_INSTALLATION (TUNNEL_HOLLOWSPACE_ID);
CREATE INDEX TUNNEL_INSTALLATION_FKX2 ON TUNNEL_INSTALLATION (LOD4_BREP_ID);
CREATE INDEX TUNNEL_INSTALLATION_FKX3 ON TUNNEL_INSTALLATION (LOD2_BREP_ID);
CREATE INDEX TUNNEL_INSTALLATION_FKX4 ON TUNNEL_INSTALLATION (TUNNEL_ID);
CREATE INDEX TUNNEL_INSTALLATION_FKX5 ON TUNNEL_INSTALLATION (LOD2_IMPLICIT_REP_ID);
CREATE INDEX TUNNEL_INSTALLATION_FKX6 ON TUNNEL_INSTALLATION (LOD3_IMPLICIT_REP_ID);
CREATE INDEX TUNNEL_INSTALLATION_FKX7 ON TUNNEL_INSTALLATION (LOD4_IMPLICIT_REP_ID);

CREATE INDEX TUNNEL_OPENING_FKX1 ON TUNNEL_OPENING (LOD3_MULTI_SURFACE_ID);
CREATE INDEX TUNNEL_OPENING_FKX2 ON TUNNEL_OPENING (LOD4_MULTI_SURFACE_ID);
CREATE INDEX TUNNEL_OPENING_FKX3 ON TUNNEL_OPENING (LOD3_IMPLICIT_REP_ID);
CREATE INDEX TUNNEL_OPENING_FKX4 ON TUNNEL_OPENING (LOD4_IMPLICIT_REP_ID);
CREATE INDEX TUNNEL_OPENING_FKX5 ON TUNNEL_OPENING (OBJECTCLASS_ID);

CREATE INDEX TUNNEL_THEMATIC_SURF_FKX ON TUNNEL_THEMATIC_SURFACE (TUNNEL_HOLLOWSPACE_ID) ;
CREATE INDEX TUNNEL_THEMATIC_SURF_FKX1 ON TUNNEL_THEMATIC_SURFACE (TUNNEL_ID);
CREATE INDEX TUNNEL_THEMATIC_SURF_FKX2 ON TUNNEL_THEMATIC_SURFACE (LOD2_MULTI_SURFACE_ID);
CREATE INDEX TUNNEL_THEMATIC_SURF_FKX3 ON TUNNEL_THEMATIC_SURFACE (LOD3_MULTI_SURFACE_ID);
CREATE INDEX TUNNEL_THEMATIC_SURF_FKX4 ON TUNNEL_THEMATIC_SURFACE (LOD4_MULTI_SURFACE_ID);
CREATE INDEX TUNNEL_THEMATIC_SURF_FKX5 ON TUNNEL_THEMATIC_SURFACE (TUNNEL_INSTALLATION_ID);
CREATE INDEX TUNNEL_THEMATIC_SURF_FKX6 ON TUNNEL_THEMATIC_SURFACE (OBJECTCLASS_ID);

CREATE INDEX TUNNEL_FKX ON TUNNEL (LOD1_MULTI_SURFACE_ID);
CREATE INDEX TUNNEL_FKX1 ON TUNNEL (LOD2_MULTI_SURFACE_ID);
CREATE INDEX TUNNEL_FKX2 ON TUNNEL (LOD3_MULTI_SURFACE_ID);
CREATE INDEX TUNNEL_FKX3 ON TUNNEL (LOD4_MULTI_SURFACE_ID);
CREATE INDEX TUNNEL_FKX4 ON TUNNEL (TUNNEL_ROOT_ID);
CREATE INDEX TUNNEL_FKX5 ON TUNNEL (TUNNEL_PARENT_ID);
CREATE INDEX TUNNEL_FKX6 ON TUNNEL (LOD1_SOLID_ID);
CREATE INDEX TUNNEL_FKX7 ON TUNNEL (LOD2_SOLID_ID);
CREATE INDEX TUNNEL_FKX8 ON TUNNEL (LOD3_SOLID_ID);
CREATE INDEX TUNNEL_FKX9 ON TUNNEL (LOD4_SOLID_ID);

CREATE INDEX WATERBODY_FKX1 ON WATERBODY (LOD2_SOLID_ID);
CREATE INDEX WATERBODY_FKX2 ON WATERBODY (LOD3_SOLID_ID);
CREATE INDEX WATERBODY_FKX3 ON WATERBODY (LOD4_SOLID_ID);
CREATE INDEX WATERBODY_FKX5 ON WATERBODY (LOD1_MULTI_SURFACE_ID);
CREATE INDEX WATERBODY_FKX4 ON WATERBODY (LOD0_MULTI_SURFACE_ID);
CREATE INDEX WATERBODY_FKX ON WATERBODY (LOD1_SOLID_ID);

CREATE INDEX WATERBOUNDARY_SURFACE_FKX ON WATERBOUNDARY_SURFACE (LOD2_SURFACE_ID);
CREATE INDEX WATERBOUNDARY_SURFACE_FKX1 ON WATERBOUNDARY_SURFACE (LOD3_SURFACE_ID);
CREATE INDEX WATERBOUNDARY_SURFACE_FKX2 ON WATERBOUNDARY_SURFACE (LOD4_SURFACE_ID);
CREATE INDEX WATERBOUNDARY_SURFACE_FKX3 ON WATERBOUNDARY_SURFACE (OBJECTCLASS_ID);