DELETE FROM objectclass;

-- Core Module --

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (0, null, null, 'Undefined', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (1, null, null, 'ObjectType', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (2, null, null, 'FeatureType', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (3, 2, 2, 'Core::AbstractFeature', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (4, 3, 2, 'Core::Address', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (5, 3, 2, 'Core::AbstractPointCloud', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (6, 3, 2, 'Core::AbstractFeatureWithLifespan', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (7, 6, 2, 'Core::AbstractCityObject', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (8, 7, 2, 'Core::AbstractSpace', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (9, 8, 2, 'Core::AbstractLogicalSpace', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (10, 8, 2, 'Core::AbstractPhysicalSpace', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (11, 10, 2, 'Core::AbstractUnoccupiedSpace', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (12, 10, 2, 'Core::AbstractOccupiedSpace', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (13, 7, 2, 'Core::AbstractSpaceBoundary', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (14, 13, 2, 'Core::AbstractThematicSurface', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (15, 14, 2, 'Core::ClosureSurface', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (16, 6, 2, 'Core::AbstractDynamizer', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (17, 6, 2, 'Core::AbstractVersionTransition', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (18, 6, 2, 'Core::CityModel', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (19, 6, 2, 'Core::AbstractVersion', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (20, 6, 2, 'Core::AbstractAppearance', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (21, 1, 1, 'Core::CityObjectRelation', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (22, 1, 1, 'Core::ImplicitGeometry', 0);

-- Dynamizer Module --

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (100, 16, 2, 'Dynamizer::Dynamizer', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (101, 3, 2, 'Dynamizer::AbstractTimeseries', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (102, 101, 2, 'Dynamizer::AbstractAtomicTimeseries', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (103, 102, 2, 'Dynamizer::TabulatedFileTimeseries', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (104, 102, 2, 'Dynamizer::StandardFileTimeseries', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (105, 102, 2, 'Dynamizer::GenericTimeseries', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (106, 101, 2, 'Dynamizer::CompositeTimeseries', 0);

-- Generics Module --

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (200, 9, 2, 'Generics::GenericLogicalSpace', 1);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (201, 12, 2, 'Generics::GenericOccupiedSpace', 1);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (202, 11, 2, 'Generics::GenericUnoccupiedSpace', 1);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (203, 14, 2, 'Generics::GenericThematicSurface', 1);

-- LandUse Module --

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (300, 14, 2, 'LandUse::LandUse', 1);

-- PointCloud Module --

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (400, 5, 2, 'PointCloud::PointCloud', 0);

-- Relief Module --

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (500, 13, 2, 'Relief::ReliefFeature', 1);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (501, 13, 2, 'Relief::AbstractReliefComponent', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (502, 501, 2, 'Relief::TINRelief', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (503, 501, 2, 'Relief::MassPointRelief', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (504, 501, 2, 'Relief::BreaklineRelief', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (505, 501, 2, 'Relief::RasterRelief', 0);

-- Transportation Module --

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (600, 11, 2, 'Transportation::AbstractTransportationSpace', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (602, 600, 2, 'Transportation::Railway', 1);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (603, 600, 2, 'Transportation::Section', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (604, 600, 2, 'Transportation::Waterway', 1);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (605, 600, 2, 'Transportation::Intersection', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (606, 600, 2, 'Transportation::Square', 1);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (607, 600, 2, 'Transportation::Track', 1);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (608, 600, 2, 'Transportation::Road', 1);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (609, 11, 2, 'Transportation::AuxiliaryTrafficSpace', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (610, 11, 2, 'Transportation::ClearanceSpace', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (611, 11, 2, 'Transportation::TrafficSpace', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (612, 11, 2, 'Transportation::Hole', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (613, 14, 2, 'Transportation::AuxiliaryTrafficArea', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (614, 14, 2, 'Transportation::TrafficArea', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (615, 14, 2, 'Transportation::Marking', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (616, 14, 2, 'Transportation::HoleSurface', 0);

-- Construction Module --

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (700, 12, 2, 'Construction::AbstractConstruction', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (701, 700, 2, 'Construction::OtherConstruction', 1);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (702, 12, 2, 'Construction::AbstractConstructiveElement', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (703, 12, 2, 'Construction::AbstractFillingElement', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (704, 703, 2, 'Construction::Window', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (705, 703, 2, 'Construction::Door', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (706, 12, 2, 'Construction::AbstractFurniture', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (707, 12, 2, 'Construction::AbstractInstallation', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (708, 14, 2, 'Construction::AbstractConstructionSurface', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (709, 708, 2, 'Construction::WallSurface', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (710, 708, 2, 'Construction::GroundSurface', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (711, 708, 2, 'Construction::InteriorWallSurface', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (712, 708, 2, 'Construction::RoofSurface', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (713, 708, 2, 'Construction::FloorSurface', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (714, 708, 2, 'Construction::OuterFloorSurface', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (715, 708, 2, 'Construction::CeilingSurface', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (716, 708, 2, 'Construction::OuterCeilingSurface', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (717, 14, 2, 'Construction::AbstractFillingSurface', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (718, 717, 2, 'Construction::DoorSurface', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (719, 717, 2, 'Construction::WindowSurface', 0);

-- Tunnel Module --

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (800, 700, 2, 'Tunnel::AbstractTunnel', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (801, 800, 2, 'Tunnel::TunnelPart', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (802, 800, 2, 'Tunnel::Tunnel', 1);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (803, 702, 2, 'Tunnel::TunnelConstructiveElement', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (804, 11, 2, 'Tunnel::HollowSpace', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (805, 707, 2, 'Tunnel::TunnelInstallation', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (806, 706, 2, 'Tunnel::TunnelFurniture', 0);

-- Building Module --

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (900, 700, 2, 'Building::AbstractBuilding', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (901, 900, 2, 'Building::BuildingPart', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (902, 900, 2, 'Building::Building', 1);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (903, 702, 2, 'Building::BuildingConstructiveElement', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (904, 11, 2, 'Building::BuildingRoom', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (905, 707, 2, 'Building::BuildingInstallation', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (906, 706, 2, 'Building::BuildingFurniture', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (907, 9, 2, 'Building::AbstractBuildingSubdivision', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (908, 907, 2, 'Building::BuildingUnit', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (909, 907, 2, 'Building::Storey', 0);

-- Bridge Module --

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (1000, 700, 2, 'Bridge::AbstractBridge', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (1001, 1000, 2, 'Bridge::BridgePart', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (1002, 1000, 2, 'Bridge::Bridge', 1);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (1003, 702, 2, 'Bridge::BridgeConstructiveElement', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (1004, 11, 2, 'Bridge::BridgeRoom', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (1005, 707, 2, 'Bridge::BridgeInstallation', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (1006, 706, 2, 'Bridge::BridgeFurniture', 0);

-- Appearance Module --

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (1100, 20, 2, 'Appearance::Appearance', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (1101, 3, 2, 'Appearance::AbstractSurfaceData', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (1102, 1101, 2, 'Appearance::X3DMaterial', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (1103, 1101, 2, 'Appearance::AbstractTexture', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (1104, 1103, 2, 'Appearance::ParameterizedTexture', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (1105, 1103, 2, 'Appearance::GeoreferencedTexture', 0);

-- CityObjectGroup Module --

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (1200, 9, 2, 'CityObjectGroup::CityObjectGroup', 1);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (1201, 1, 1, 'CityObjectGroup::Role', 0);

-- Vegetation Module --

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (1300, 12, 2, 'Vegetation::AbstractVegetationObject', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (1301, 1300, 2, 'Vegetation::SolitaryVegetationObject', 1);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (1302, 1300, 2, 'Vegetation::PlantCover', 1);

-- Versioning Module --

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (1400, 19, 2, 'Versioning::Version', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (1401, 17, 2, 'Versioning::VersionTransition', 0);

-- WaterBody Module --

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (1500, 12, 2, 'WaterBody::WaterBody', 1);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (1501, 14, 2, 'WaterBody::AbstractWaterBoundarySurface', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (1502, 1501, 2, 'WaterBody::WaterSurface', 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (1503, 1501, 2, 'WaterBody::WaterGroundSurface', 0);

-- CityFurniture Module --

INSERT INTO objectclass (ID, SUPERCLASS_ID, BASECLASS_ID, CLASSNAME, IS_TOPLEVEL)
VALUES (1600, 12, 2, 'CityFurniture::CityFurniture', 1);











