CREATE TABLE TUNNEL_THEMATIC_SURFACE 
(
  ID NUMBER NOT NULL 
, OBJECTCLASS_ID NUMBER 
, TUNNEL_ID NUMBER 
, TUNNEL_HOLLOWSPACE_ID NUMBER 
, TUNNEL_INSTALLATION_ID NUMBER 
, LOD2_MULTI_SURFACE_ID NUMBER 
, LOD3_MULTI_SURFACE_ID NUMBER 
, LOD4_MULTI_SURFACE_ID NUMBER 
, CONSTRAINT TUNNEL_THEMATIC_SURFACE_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX TUNNEL_THEMATIC_SURF_PK ON TUNNEL_THEMATIC_SURFACE (ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX TUNNEL_THEMATIC_SURF_FKX ON TUNNEL_THEMATIC_SURFACE (TUNNEL_HOLLOWSPACE_ID) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX TUNNEL_THEMATIC_SURF_FKX1 ON TUNNEL_THEMATIC_SURFACE (TUNNEL_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX TUNNEL_THEMATIC_SURF_FKX2 ON TUNNEL_THEMATIC_SURFACE (LOD2_MULTI_SURFACE_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX TUNNEL_THEMATIC_SURF_FKX3 ON TUNNEL_THEMATIC_SURFACE (LOD3_MULTI_SURFACE_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX TUNNEL_THEMATIC_SURF_FKX4 ON TUNNEL_THEMATIC_SURFACE (LOD4_MULTI_SURFACE_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX TUNNEL_THEMATIC_SURF_FKX5 ON TUNNEL_THEMATIC_SURFACE (TUNNEL_INSTALLATION_ID ASC);

CREATE INDEX TUNNEL_THEMATIC_SURF_FKX6 ON TUNNEL_THEMATIC_SURFACE (OBJECTCLASS_ID ASC);

ALTER TABLE TUNNEL_THEMATIC_SURFACE
ADD CONSTRAINT TUNNEL_THEMATIC_SURFACE_FK FOREIGN KEY
(
  LOD2_MULTI_SURFACE_ID 
)
REFERENCES SURFACE_GEOMETRY
(
  ID 
)
ENABLE;

ALTER TABLE TUNNEL_THEMATIC_SURFACE
ADD CONSTRAINT TUNNEL_THEMATIC_SURFACE_FK1 FOREIGN KEY
(
  LOD3_MULTI_SURFACE_ID 
)
REFERENCES SURFACE_GEOMETRY
(
  ID 
)
ENABLE;

ALTER TABLE TUNNEL_THEMATIC_SURFACE
ADD CONSTRAINT TUNNEL_THEMATIC_SURFACE_FK2 FOREIGN KEY
(
  LOD4_MULTI_SURFACE_ID 
)
REFERENCES SURFACE_GEOMETRY
(
  ID 
)
ENABLE;

ALTER TABLE TUNNEL_THEMATIC_SURFACE
ADD CONSTRAINT TUNNEL_THEMATIC_SURFACE_FK3 FOREIGN KEY
(
  ID 
)
REFERENCES CITYOBJECT
(
  ID 
)
ENABLE;

ALTER TABLE TUNNEL_THEMATIC_SURFACE
ADD CONSTRAINT TUNNEL_THEMATIC_SURFACE_FK4 FOREIGN KEY
(
  TUNNEL_HOLLOWSPACE_ID 
)
REFERENCES TUNNEL_HOLLOWSPACE
(
  ID 
)
ENABLE;

ALTER TABLE TUNNEL_THEMATIC_SURFACE
ADD CONSTRAINT TUNNEL_THEMATIC_SURFACE_FK5 FOREIGN KEY
(
  TUNNEL_INSTALLATION_ID 
)
REFERENCES TUNNEL_INSTALLATION
(
  ID 
)
ENABLE;

ALTER TABLE TUNNEL_THEMATIC_SURFACE
ADD CONSTRAINT TUNNEL_THEMATIC_SURFACE_FK6 FOREIGN KEY
(
  TUNNEL_ID 
)
REFERENCES TUNNEL
(
  ID 
)
ENABLE;

ALTER TABLE TUNNEL_THEMATIC_SURFACE
ADD CONSTRAINT TUNNEL_THEMATIC_SURFACE_FK7 FOREIGN KEY
(
  OBJECTCLASS_ID 
)
REFERENCES OBJECTCLASS
(
  ID 
)
ENABLE;
