CREATE TABLE TUNNEL_OPEN_TO_THEM_SURF 
(
  OPENING_ID NUMBER NOT NULL 
, THEMATIC_SURFACE_ID NUMBER NOT NULL 
, CONSTRAINT TUNNEL_OPEN_TO_THEM_SURF_PK PRIMARY KEY 
  (
    OPENING_ID 
  , THEMATIC_SURFACE_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX BRIDGE_OPENING_TO_THEM_SURFAC2 ON TUNNEL_OPEN_TO_THEM_SURF (OPENING_ID ASC, THEMATIC_SURFACE_ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

ALTER TABLE TUNNEL_OPEN_TO_THEM_SURF
ADD CONSTRAINT TUNNEL_OPEN_TO_THEM_SURF_FK FOREIGN KEY
(
  OPENING_ID 
)
REFERENCES TUNNEL_OPENING
(
  ID 
)
ENABLE;

ALTER TABLE TUNNEL_OPEN_TO_THEM_SURF
ADD CONSTRAINT TUNNEL_OPEN_TO_THEM_SURF_FK1 FOREIGN KEY
(
  OPENING_ID 
)
REFERENCES TUNNEL_THEMATIC_SURFACE
(
  ID 
)
ENABLE;
