CREATE TABLE TUNNEL_OPENING 
(
  ID NUMBER NOT NULL 
, OBJECTCLASS_ID NUMBER 
, LOD3_MULTI_SURFACE_ID NUMBER 
, LOD4_MULTI_SURFACE_ID NUMBER 
, LOD3_IMPLICIT_REP_ID NUMBER 
, LOD3_IMPLICIT_REF_POINT MDSYS.SDO_GEOMETRY 
, LOD3_IMPLICIT_TRANSFORMATION VARCHAR2(1000) 
, LOD4_IMPLICIT_REP_ID NUMBER 
, LOD4_IMPLICIT_REF_POINT MDSYS.SDO_GEOMETRY 
, LOD4_IMPLICIT_TRANSFORMATION VARCHAR2(1000) 
, CONSTRAINT TUNNEL_OPENING_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX TUNNEL_OPENING_PK ON TUNNEL_OPENING (ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX TUNNEL_OPENING_FKX1 ON TUNNEL_OPENING (LOD3_MULTI_SURFACE_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX TUNNEL_OPENING_FKX2 ON TUNNEL_OPENING (LOD4_MULTI_SURFACE_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX TUNNEL_OPENING_FKX3 ON TUNNEL_OPENING (LOD3_IMPLICIT_REP_ID ASC);

CREATE INDEX TUNNEL_OPENING_FKX4 ON TUNNEL_OPENING (LOD4_IMPLICIT_REP_ID ASC);

CREATE INDEX TUNNEL_OPENING_FKX5 ON TUNNEL_OPENING (OBJECTCLASS_ID ASC);

CREATE INDEX TUNNEL_OPEN_LOD3REFPT_SPX ON TUNNEL_OPENING (LOD3_IMPLICIT_REF_POINT) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE INDEX TUNNEL_OPEN_LOD4REFPT_SPX ON TUNNEL_OPENING (LOD4_IMPLICIT_REF_POINT) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

ALTER TABLE TUNNEL_OPENING
ADD CONSTRAINT TUNNEL_OPENING_FK FOREIGN KEY
(
  ID 
)
REFERENCES CITYOBJECT
(
  ID 
)
ENABLE;

ALTER TABLE TUNNEL_OPENING
ADD CONSTRAINT TUNNEL_OPENING_FK1 FOREIGN KEY
(
  LOD3_MULTI_SURFACE_ID 
)
REFERENCES SURFACE_GEOMETRY
(
  ID 
)
ENABLE;

ALTER TABLE TUNNEL_OPENING
ADD CONSTRAINT TUNNEL_OPENING_FK2 FOREIGN KEY
(
  LOD4_MULTI_SURFACE_ID 
)
REFERENCES SURFACE_GEOMETRY
(
  ID 
)
ENABLE;

ALTER TABLE TUNNEL_OPENING
ADD CONSTRAINT TUNNEL_OPENING_FK3 FOREIGN KEY
(
  LOD4_IMPLICIT_REP_ID 
)
REFERENCES IMPLICIT_GEOMETRY
(
  ID 
)
ENABLE;

ALTER TABLE TUNNEL_OPENING
ADD CONSTRAINT TUNNEL_OPENING_FK4 FOREIGN KEY
(
  LOD3_IMPLICIT_REP_ID 
)
REFERENCES IMPLICIT_GEOMETRY
(
  ID 
)
ENABLE;

ALTER TABLE TUNNEL_OPENING
ADD CONSTRAINT TUNNEL_OPENING_OBJCLASS_FK FOREIGN KEY
(
  OBJECTCLASS_ID 
)
REFERENCES OBJECTCLASS
(
  ID 
)
ENABLE;
