CREATE TABLE TUNNEL_HOLLOWSPACE 
(
  ID NUMBER NOT NULL 
, CLASS VARCHAR2(256) 
, CLASS_CODESPACE VARCHAR2(4000) 
, FUNCTION VARCHAR2(1000) 
, FUNCTION_CODESPACE VARCHAR2(4000) 
, USAGE VARCHAR2(1000) 
, USAGE_CODESPACE VARCHAR2(4000) 
, TUNNEL_ID NUMBER NOT NULL 
, LOD4_MULTI_SURFACE_ID NUMBER 
, LOD4_SOLID_ID NUMBER 
, CONSTRAINT TUNNEL_HOLLOWSPACE_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX TUNNEL_HOLLOWSPACE_PK ON TUNNEL_HOLLOWSPACE (ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX TUNNEL_HOLLOWSPACE_FKX ON TUNNEL_HOLLOWSPACE (TUNNEL_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX TUNNEL_HOLLOWSPACE_FKX1 ON TUNNEL_HOLLOWSPACE (LOD4_MULTI_SURFACE_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX TUNNEL_HOLLOWSPACE_FKX2 ON TUNNEL_HOLLOWSPACE (LOD4_SOLID_ID ASC);

ALTER TABLE TUNNEL_HOLLOWSPACE
ADD CONSTRAINT TUNNEL_HOLLOWSPACE_CITYOBJ_FK FOREIGN KEY
(
  ID 
)
REFERENCES CITYOBJECT
(
  ID 
)
ENABLE;

ALTER TABLE TUNNEL_HOLLOWSPACE
ADD CONSTRAINT TUNNEL_HOLLOWSPACE_GEOM_FK FOREIGN KEY
(
  LOD4_MULTI_SURFACE_ID 
)
REFERENCES SURFACE_GEOMETRY
(
  ID 
)
ENABLE;

ALTER TABLE TUNNEL_HOLLOWSPACE
ADD CONSTRAINT TUNNEL_HOLLOWSPACE_GEOM_FK2 FOREIGN KEY
(
  LOD4_SOLID_ID 
)
REFERENCES SURFACE_GEOMETRY
(
  ID 
)
ENABLE;

ALTER TABLE TUNNEL_HOLLOWSPACE
ADD CONSTRAINT TUNNEL_HOLLOWSPACE_TUNNEL_FK FOREIGN KEY
(
  TUNNEL_ID 
)
REFERENCES TUNNEL
(
  ID 
)
ENABLE;
