CREATE TABLE TUNNEL_INSTALLATION 
(
  ID NUMBER NOT NULL 
, IS_EXTERNAL NUMBER(1, 0) 
, CLASS VARCHAR2(256) 
, CLASS_CODESPACE VARCHAR2(4000) 
, FUNCTION VARCHAR2(1000) 
, FUNCTION_CODESPACE VARCHAR2(4000) 
, USAGE VARCHAR2(1000) 
, USAGE_CODESPACE VARCHAR2(4000) 
, TUNNEL_ID NUMBER 
, TUNNEL_HOLLOWSPACE_ID NUMBER 
, LOD2_IMPLICIT_REP_ID NUMBER 
, LOD2_IMPLICIT_REF_POINT MDSYS.SDO_GEOMETRY 
, LOD2_IMPLICIT_TRANSFORMATION VARCHAR2(1000) 
, LOD3_IMPLICIT_REP_ID NUMBER 
, LOD3_IMPLICIT_REF_POINT MDSYS.SDO_GEOMETRY 
, LOD3_IMPLICIT_TRANSFORMATION VARCHAR2(1000) 
, LOD4_IMPLICIT_REP_ID NUMBER 
, LOD4_IMPLICIT_REF_POINT MDSYS.SDO_GEOMETRY 
, LOD4_IMPLICIT_TRANSFORMATION VARCHAR2(1000) 
, LOD2_BREP_ID NUMBER 
, LOD3_BREP_ID NUMBER 
, LOD4_BREP_ID NUMBER 
, LOD2_OTHER_GEOM MDSYS.SDO_GEOMETRY 
, LOD3_OTHER_GEOM MDSYS.SDO_GEOMETRY 
, LOD4_OTHER_GEOM MDSYS.SDO_GEOMETRY 
, CONSTRAINT TUNNEL_INSTALLATION_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX TUNNEL_INSTALLATION_PK ON TUNNEL_INSTALLATION (ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX TUNNEL_INSTALLATION_FKX ON TUNNEL_INSTALLATION (LOD3_BREP_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX TUNNEL_INSTALLATION_FKX1 ON TUNNEL_INSTALLATION (TUNNEL_HOLLOWSPACE_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX TUNNEL_INSTALLATION_FKX2 ON TUNNEL_INSTALLATION (LOD4_BREP_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX TUNNEL_INSTALLATION_FKX3 ON TUNNEL_INSTALLATION (LOD2_BREP_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX TUNNEL_INSTALLATION_FKX4 ON TUNNEL_INSTALLATION (TUNNEL_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX TUNNEL_INSTALLATION_FKX5 ON TUNNEL_INSTALLATION (LOD2_IMPLICIT_REP_ID ASC);

CREATE INDEX TUNNEL_INSTALLATION_FKX6 ON TUNNEL_INSTALLATION (LOD3_IMPLICIT_REP_ID ASC);

CREATE INDEX TUNNEL_INSTALLATION_FKX7 ON TUNNEL_INSTALLATION (LOD4_IMPLICIT_REP_ID ASC);

CREATE INDEX TUNNEL_INST_LOD2OTHER_SPX ON TUNNEL_INSTALLATION (LOD2_OTHER_GEOM) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE INDEX TUNNEL_INST_LOD2REFPT_SPX ON TUNNEL_INSTALLATION (LOD2_IMPLICIT_REF_POINT) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE INDEX TUNNEL_INST_LOD3OTHER_SPX ON TUNNEL_INSTALLATION (LOD3_OTHER_GEOM) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE INDEX TUNNEL_INST_LOD3REFPT_SPX ON TUNNEL_INSTALLATION (LOD3_IMPLICIT_REF_POINT) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE INDEX TUNNEL_INST_LOD4OTHER_SPX ON TUNNEL_INSTALLATION (LOD4_OTHER_GEOM) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE INDEX TUNNEL_INST_LOD4REFPT_SPX ON TUNNEL_INSTALLATION (LOD4_IMPLICIT_REF_POINT) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

ALTER TABLE TUNNEL_INSTALLATION
ADD CONSTRAINT TUNNEL_INSTALLATION_FK FOREIGN KEY
(
  ID 
)
REFERENCES CITYOBJECT
(
  ID 
)
ENABLE;

ALTER TABLE TUNNEL_INSTALLATION
ADD CONSTRAINT TUNNEL_INSTALLATION_FK1 FOREIGN KEY
(
  TUNNEL_ID 
)
REFERENCES TUNNEL
(
  ID 
)
ENABLE;

ALTER TABLE TUNNEL_INSTALLATION
ADD CONSTRAINT TUNNEL_INSTALLATION_FK2 FOREIGN KEY
(
  LOD2_BREP_ID 
)
REFERENCES SURFACE_GEOMETRY
(
  ID 
)
ENABLE;

ALTER TABLE TUNNEL_INSTALLATION
ADD CONSTRAINT TUNNEL_INSTALLATION_FK3 FOREIGN KEY
(
  LOD3_BREP_ID 
)
REFERENCES SURFACE_GEOMETRY
(
  ID 
)
ENABLE;

ALTER TABLE TUNNEL_INSTALLATION
ADD CONSTRAINT TUNNEL_INSTALLATION_FK4 FOREIGN KEY
(
  LOD4_BREP_ID 
)
REFERENCES SURFACE_GEOMETRY
(
  ID 
)
ENABLE;

ALTER TABLE TUNNEL_INSTALLATION
ADD CONSTRAINT TUNNEL_INSTALLATION_FK5 FOREIGN KEY
(
  LOD2_IMPLICIT_REP_ID 
)
REFERENCES IMPLICIT_GEOMETRY
(
  ID 
)
ENABLE;

ALTER TABLE TUNNEL_INSTALLATION
ADD CONSTRAINT TUNNEL_INSTALLATION_FK6 FOREIGN KEY
(
  LOD3_IMPLICIT_REP_ID 
)
REFERENCES IMPLICIT_GEOMETRY
(
  ID 
)
ENABLE;

ALTER TABLE TUNNEL_INSTALLATION
ADD CONSTRAINT TUNNEL_INSTALLATION_FK7 FOREIGN KEY
(
  LOD4_IMPLICIT_REP_ID 
)
REFERENCES IMPLICIT_GEOMETRY
(
  ID 
)
ENABLE;

ALTER TABLE TUNNEL_INSTALLATION
ADD CONSTRAINT TUNNEL_INSTALLATION_HOLL_FK FOREIGN KEY
(
  TUNNEL_HOLLOWSPACE_ID 
)
REFERENCES TUNNEL_HOLLOWSPACE
(
  ID 
)
ENABLE;
