DELETE FROM aggregation_info;

-- Core Module --

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (20, 7, 'appearance', 1, 0, -1, 0);

-- Dynamizer Module --

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (101, 100, 'dynamicData', 1, 0, -1, 0);

-- Relief Module --

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (501, 500, 'reliefComponent', 5, 1, -1, 0);

-- Transportation Module --

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (610, 611, 'clearanceSpace', 6, 0, -1, 0);

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (611, 600, 'trafficSpace', 6, 0, -1, 0);

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (615, 600, 'marking', 6, 0, -1, 0);

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (612, 600, 'hole', 6, 0, -1, 0);

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (609, 600, 'auxiliaryTrafficSpace', 6, 0, -1, 0);

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (603, 607, 'section', 6, 0, -1, 0);

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (605, 607, 'intersection', 6, 0, -1, 0);

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (603, 608, 'section', 6, 0, -1, 0);

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (605, 608, 'intersection', 6, 0, -1, 0);

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (603, 604, 'section', 6, 0, -1, 0);

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (605, 604, 'intersection', 6, 0, -1, 0);

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (603, 602, 'section', 6, 0, -1, 0);

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (605, 602, 'intersection', 6, 0, -1, 0);

-- Construction Module --

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (4, 705, 'address', 7, 0, -1, 0);

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (4, 718, 'address', 7, 0, -1, 0);

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (14, 700, 'boundary', 7, 0, -1, 0);

-- Tunnel Module --

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (802, 801, 'tunnelPart', 8, 1, -1, 1);

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (804, 800, 'hollowSpace', 8, 0, -1, 0);

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (805, 800, 'tunnelInstallation', 8, 0, -1, 0);

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (806, 800, 'tunnelFurniture', 8, 0, -1, 0);

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (803, 800, 'tunnelConstructiveElement', 8, 0, -1, 0);

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (806, 804, 'tunnelFurniture', 8, 0, -1, 0);

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (805, 804, '805', 8, 0, -1, 0);

-- Building Module --

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (902, 901, 'buildingPart', 9, 1, -1, 1);

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (4, 900, 'address', 9, 0, -1, 0);

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (4, 908, 'address', 9, 0, -1, 0);

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (907, 900, 'buildingSubdivision', 9, 0, -1, 0);

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (904, 900, 'buildingPart', 9, 0, -1, 0);

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (905, 900, 'buildingInstallation', 9, 0, -1, 0);

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (906, 900, 'buildingFurniture', 9, 0, -1, 0);

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (903, 900, 'buildingConstructiveElement', 9, 0, -1, 0);

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (906, 904, 'buildingFurniture', 9, 0, -1, 0);

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (905, 904, 'buildingInstallation', 9, 0, -1, 0);

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (905, 907, 'buildingInstallation', 9, 0, -1, 0);

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (906, 907, 'buildingFurniture', 9, 0, -1, 0);

-- Bridge Module --

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (1002, 1001, 'bridgePart', 10, 1, -1, 1);

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (4, 1000, 'address', 10, 0, -1, 0);

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (1004, 1000, 'bridgeRoom', 10, 0, -1, 0);

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (1005, 1000, 'bridgeInstallation', 10, 0, -1, 0);

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (1006, 1000, 'bridgeFurniture', 10, 0, -1, 0);

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (1003, 1000, 'bridgeConstructiveElement', 10, 0, -1, 0);

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (1005, 1004, 'bridgeInstallation', 10, 0, -1, 0);

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (1006, 1004, 'bridgeFurniture', 10, 0, -1, 0);

-- Appearance Module --

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (1101, 1100, 'surfaceData', 11, 0, -1, 0);


-- CityObjectGroup Module --

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (7, 1200, 'groupMember', 12, 0, -1, 0);


-- Versioning Module --

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (6, 1400, 'versionMember', 14, 0, -1, 0);

-- WaterBody Module --

INSERT INTO aggregation_info (CHILD_ID, PARENT_ID, PROPERTY_NAME, PROPERTY_NAMESPACE_ID, MIN_OCCURS, MAX_OCCURS, IS_COMPOSITE)
VALUES (1501, 1500, 'boundary', 15, 0, -1, 0);

