DELETE FROM objectclass;

-- Core Module --

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (0, null, 'Undefined', 0, null);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (1, null, 'ObjectType', 0, null);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (2, 1, 'FeatureType', 0, null);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (3, 2, 'AbstractFeature', 0, 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (4, 3, 'Address', 0, 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (5, 3, 'AbstractPointCloud', 0, 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (6, 3, 'AbstractFeatureWithLifespan', 0, 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (7, 6, 'AbstractCityObject', 0, 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (8, 7, 'AbstractSpace', 0, 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (9, 8, 'AbstractLogicalSpace', 0, 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (10, 8, 'AbstractPhysicalSpace', 0, 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (11, 10, 'AbstractUnoccupiedSpace', 0, 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (12, 10, 'AbstractOccupiedSpace', 0, 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (13, 7, 'AbstractSpaceBoundary', 0, 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (14, 13, 'AbstractThematicSurface', 0, 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (15, 14, 'ClosureSurface', 0, 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (16, 6, 'AbstractDynamizer', 0, 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (17, 6, 'AbstractVersionTransition', 0, 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (18, 6, 'CityModel', 0, 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (19, 6, 'AbstractVersion', 0, 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (20, 6, 'AbstractAppearance', 0, 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (21, 1, 'CityObjectRelation', 0, 0);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (22, 1, 'ImplicitGeometry', 0, 0);

-- Dynamizer Module --

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (100, 16, 'Dynamizer', 0, 100);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (101, 3, 'AbstractTimeseries', 0, 100);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (102, 101, 'AbstractAtomicTimeseries', 0, 100);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (103, 102, 'TabulatedFileTimeseries', 0, 100);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (104, 102, 'StandardFileTimeseries', 0, 100);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (105, 102, 'GenericTimeseries', 0, 100);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (106, 101, 'CompositeTimeseries', 0, 100);

-- Generics Module --

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (200, 9, 'GenericLogicalSpace', 1, 200);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (201, 12, 'GenericOccupiedSpace', 1, 200);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (202, 11, 'GenericUnoccupiedSpace', 1, 200);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (203, 14, 'GenericThematicSurface', 1, 200);

-- LandUse Module --

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (300, 14, 'LandUse', 1, 300);

-- PointCloud Module --

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (400, 5, 'PointCloud::PointCloud', 0, 400);

-- Relief Module --

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (500, 13, 'ReliefFeature', 1, 500);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (501, 13, 'AbstractReliefComponent', 0, 500);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (502, 501, 'TINRelief', 0, 500);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (503, 501, 'MassPointRelief', 0, 500);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (504, 501, 'BreaklineRelief', 0, 500);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (505, 501, 'RasterRelief', 0, 500);

-- Transportation Module --

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (600, 11, 'AbstractTransportationSpace', 0, 600);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (602, 600, 'Railway', 1, 600);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (603, 600, 'Section', 0, 600);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (604, 600, 'Waterway', 1, 600);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (605, 600, 'Intersection', 0, 600);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (606, 600, 'Square', 1, 600);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (607, 600, 'Track', 1, 600);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (608, 600, 'Road', 1, 600);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (609, 11, 'AuxiliaryTrafficSpace', 0, 600);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (610, 11, 'ClearanceSpace', 0, 600);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (611, 11, 'TrafficSpace', 0, 600);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (612, 11, 'Hole', 0, 600);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (613, 14, 'AuxiliaryTrafficArea', 0, 600);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (614, 14, 'TrafficArea', 0, 600);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (615, 14, 'Marking', 0, 600);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (616, 14, 'HoleSurface', 0, 600);

-- Construction Module --

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (700, 12, 'AbstractConstruction', 0, 700);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (701, 700, 'OtherConstruction', 1, 700);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (702, 12, 'AbstractConstructiveElement', 0, 700);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (703, 12, 'AbstractFillingElement', 0, 700);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (704, 703, 'Window', 0, 700);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (705, 703, 'Door', 0, 700);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (706, 12, 'AbstractFurniture', 0, 700);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (707, 12, 'AbstractInstallation', 0, 700);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (708, 14, 'AbstractConstructionSurface', 0, 700);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (709, 708, 'WallSurface', 0, 700);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (710, 708, 'GroundSurface', 0, 700);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (711, 708, 'InteriorWallSurface', 0, 700);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (712, 708, 'RoofSurface', 0, 700);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (713, 708, 'FloorSurface', 0, 700);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (714, 708, 'OuterFloorSurface', 0, 700);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (715, 708, 'CeilingSurface', 0, 700);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (716, 708, 'OuterCeilingSurface', 0, 700);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (717, 14, 'AbstractFillingSurface', 0, 700);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (718, 717, 'DoorSurface', 0, 700);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (719, 717, 'WindowSurface', 0, 700);

-- Tunnel Module --

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (800, 700, 'AbstractTunnel', 0, 800);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (801, 800, 'TunnelPart', 0, 800);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (802, 800, 'Tunnel', 1, 800);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (803, 702, 'TunnelConstructiveElement', 0, 800);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (804, 11, 'HollowSpace', 0, 800);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (805, 707, 'TunnelInstallation', 0, 800);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (806, 706, 'TunnelFurniture', 0, 800);

-- Building Module --

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (900, 700, 'AbstractBuilding', 0, 900);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (901, 900, 'BuildingPart', 0, 900);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (902, 900, 'Building', 1, 900);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (903, 702, 'BuildingConstructiveElement', 0, 900);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (904, 11, 'BuildingRoom', 0, 900);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (905, 707, 'BuildingInstallation', 0, 900);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (906, 706, 'BuildingFurniture', 0, 900);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (907, 9, 'AbstractBuildingSubdivision', 0, 900);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (908, 907, 'BuildingUnit', 0, 900);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (909, 907, 'Storey', 0, 900);

-- Bridge Module --

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (1000, 700, 'AbstractBridge', 0, 1000);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (1001, 1000, 'BridgePart', 0, 1000);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (1002, 1000, 'Bridge', 1, 1000);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (1003, 702, 'BridgeConstructiveElement', 0, 1000);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (1004, 11, 'BridgeRoom', 0, 1000);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (1005, 707, 'BridgeInstallation', 0, 1000);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (1006, 706, 'BridgeFurniture', 0, 1000);

-- Appearance Module --

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (1100, 20, 'Appearance', 0, 1100);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (1101, 3, 'AbstractSurfaceData', 0, 1100);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (1102, 1101, 'X3DMaterial', 0, 1100);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (1103, 1101, 'AbstractTexture', 0, 1100);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (1104, 1103, 'ParameterizedTexture', 0, 1100);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (1105, 1103, 'GeoreferencedTexture', 0, 1100);

-- CityObjectGroup Module --

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (1200, 9, 'CityObjectGroup', 1, 1200);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (1201, 1, 'Role', 0, 1200);

-- Vegetation Module --

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (1300, 12, 'AbstractVegetationObject', 0, 1300);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (1301, 1300, 'SolitaryVegetationObject', 1, 1300);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (1302, 1300, 'PlantCover', 1, 1300);

-- Versioning Module --

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (1400, 19, 'Version', 0, 1400);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (1401, 17, 'VersionTransition', 0, 1400);

-- WaterBody Module --

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (1500, 12, 'WaterBody', 1, 1500);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (1501, 14, 'AbstractWaterBoundarySurface', 0, 1500);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (1502, 1501, 'WaterSurface', 0, 1500);

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (1503, 1501, 'WaterGroundSurface', 0, 1500);

-- CityFurniture Module --

INSERT INTO objectclass (ID, SUPERCLASS_ID, CLASSNAME, IS_TOPLEVEL, NAMESPACE_ID)
VALUES (1600, 12, 'CityFurniture', 1, 1600);











