\pset footer off
SET client_min_messages TO WARNING;
\set ON_ERROR_STOP ON

\set USERNAME :username
\set SCHEMA_NAME :schema_name

\echo
\echo 'Revoking access privileges on schema "':SCHEMA_NAME'" from user "':USERNAME'" ...'

REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA :"SCHEMA_NAME" FROM :"USERNAME";
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA :"SCHEMA_NAME" FROM :"USERNAME";
REVOKE USAGE, CREATE ON SCHEMA :"SCHEMA_NAME" FROM :"USERNAME";
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA citydb_pkg FROM :"USERNAME";
REVOKE USAGE ON SCHEMA citydb_pkg FROM :"USERNAME";
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM :"USERNAME";
REVOKE USAGE ON SCHEMA public FROM :"USERNAME";
REVOKE CONNECT, TEMP ON DATABASE :"DBNAME" FROM :"USERNAME";

\echo
\echo 'Access privileges successfully revoked.'