CREATE TABLE DATABASE_SRS 
(
  SRID NUMBER(38, 0) NOT NULL 
, GML_SRS_NAME VARCHAR2(1000) 
, CONSTRAINT DATABASE_SRS_PK PRIMARY KEY 
  (
    SRID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX DATABASE_SRS_PK ON DATABASE_SRS (SRID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
);
