CREATE TABLE OBJECTCLASS 
(
  ID NUMBER NOT NULL 
, CLASSNAME VARCHAR2(256) 
, SUPERCLASS_ID NUMBER 
, CONSTRAINT OBJECTCLASS_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OBJECTCLASS_PK ON OBJECTCLASS (ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX OBJECTCLASS_FKX ON OBJECTCLASS (SUPERCLASS_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
);

ALTER TABLE OBJECTCLASS
ADD CONSTRAINT OBJECTCLASS_OBJECTCLASS_FK FOREIGN KEY
(
  SUPERCLASS_ID 
)
REFERENCES OBJECTCLASS
(
  ID 
)
ENABLE;
