CREATE SEQUENCE FEATURE_CHANGELOG_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 0 NOCACHE NOCYCLE;

CREATE  TABLE FEATURE_CHANGELOG ( 
	ID                   NUMBER(38)  DEFAULT FEATURE_CHANGELOG_SEQ.NEXTVAL NOT NULL,
	FEATURE_ID           NUMBER(38)   ,
	OBJECTCLASS_ID       NUMBER(10)   NOT NULL,
	OBJECTID             VARCHAR2(1000)   ,
	IDENTIFIER           VARCHAR2(1000)   ,
	IDENTIFIER_CODESPACE VARCHAR2(4000)   ,
	ENVELOPE             SDO_GEOMETRY   ,
	TRANSACTION_TYPE     VARCHAR2(20)   NOT NULL,
	TRANSACTION_DATE     TIMESTAMP WITH TIME ZONE   NOT NULL,
	DB_USER              VARCHAR2(1000)   ,
	REASON_FOR_UPDATE    VARCHAR2(4000)   ,
	CONSTRAINT FEATURE_CHANGELOG_PK PRIMARY KEY ( ID ) 
 );

CREATE INDEX FEATURE_CHANGELOG_FEATURE_FKX ON FEATURE_CHANGELOG ( FEATURE_ID ) PCTFREE = 10;

CREATE INDEX FEATURE_CHANGELOG_OBJECTCLASS_INX ON FEATURE_CHANGELOG ( OBJECTCLASS_ID ) PCTFREE = 10;

CREATE INDEX FEATURE_CHANGELOG_OBJECTID_INX ON FEATURE_CHANGELOG ( OBJECTID ) PCTFREE = 10;

CREATE INDEX FEATURE_CHANGELOG_IDENTIFIER_INX ON FEATURE_CHANGELOG ( IDENTIFIER, IDENTIFIER_CODESPACE ) PCTFREE = 10;

CREATE INDEX FEATURE_CHANGELOG_TRANSACTION_DATE_INX ON FEATURE_CHANGELOG ( TRANSACTION_DATE ) PCTFREE = 0;

ALTER TABLE FEATURE_CHANGELOG ADD CONSTRAINT FEATURE_CHANGELOG_FEATURE_FK FOREIGN KEY ( FEATURE_ID ) REFERENCES FEATURE( ID );

