CREATE TABLE ADDRESS_TO_BRIDGE 
(
  BIRDGE_ID NUMBER NOT NULL 
, ADDRESS_ID NUMBER NOT NULL 
, CONSTRAINT ADDRESS_TO_BRIDGE_PK PRIMARY KEY 
  (
    BIRDGE_ID 
  , ADDRESS_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX ADDRESS_TO_BRIDGE_PK ON ADDRESS_TO_BRIDGE (BIRDGE_ID ASC, ADDRESS_ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX ADDRESS_TO_BRIDGE_FKX ON ADDRESS_TO_BRIDGE (BIRDGE_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX ADDRESS_TO_BRIDGE_FKX1 ON ADDRESS_TO_BRIDGE (ADDRESS_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

ALTER TABLE ADDRESS_TO_BRIDGE
ADD CONSTRAINT ADDRESS_TO_BRIDGE_ADDRESS_FK FOREIGN KEY
(
  ADDRESS_ID 
)
REFERENCES ADDRESS
(
  ID 
)
ENABLE;

ALTER TABLE ADDRESS_TO_BRIDGE
ADD CONSTRAINT ADDRESS_TO_BRIDGE_FK FOREIGN KEY
(
  BIRDGE_ID 
)
REFERENCES BRIDGE
(
  ID 
)
ENABLE;
