CREATE TABLE BRD_OPEN_TO_THEM_SURFACE 
(
  BRIDGE_OPENING_ID NUMBER NOT NULL 
, THEMATIC_SURFACE_ID NUMBER NOT NULL 
, CONSTRAINT BRD_OPEN_TO_THEM_SURFACE_PK PRIMARY KEY 
  (
    BRIDGE_OPENING_ID 
  , THEMATIC_SURFACE_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX BRD_OPEN_TO_THEM_SURF_PX ON BRD_OPEN_TO_THEM_SURFACE (BRIDGE_OPENING_ID ASC, THEMATIC_SURFACE_ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

ALTER TABLE BRD_OPEN_TO_THEM_SURFACE
ADD CONSTRAINT BRD_OPEN_TO_THEM_SURFACE_FK FOREIGN KEY
(
  BRIDGE_OPENING_ID 
)
REFERENCES BRIDGE_OPENING
(
  ID 
)
ENABLE;

ALTER TABLE BRD_OPEN_TO_THEM_SURFACE
ADD CONSTRAINT BRD_OPEN_TO_THEM_SURFACE_FK1 FOREIGN KEY
(
  THEMATIC_SURFACE_ID 
)
REFERENCES BRD_THEMATIC_SURFACE
(
  ID 
)
ENABLE;
