CREATE SEQUENCE ADDRESS_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 0 NOCACHE NOCYCLE;

CREATE SEQUENCE ADE_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999999999 NOCACHE NOCYCLE;

CREATE SEQUENCE APPEARANCE_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 0 NOCACHE NOCYCLE;

CREATE SEQUENCE APPEAR_TO_SURFACE_DATA_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 0 NOCACHE NOCYCLE;

CREATE SEQUENCE CODELIST_ENTRY_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 0 NOCACHE NOCYCLE;

CREATE SEQUENCE CODELIST_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 0 NOCACHE NOCYCLE;

CREATE SEQUENCE FEATURE_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 0 NOCACHE NOCYCLE;

CREATE SEQUENCE GEOMETRY_DATA_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 0 NOCACHE NOCYCLE;

CREATE SEQUENCE IMPLICIT_GEOMETRY_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 0 NOCACHE NOCYCLE;

CREATE SEQUENCE PROPERTY_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 0 NOCACHE NOCYCLE;

CREATE SEQUENCE SURFACE_DATA_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 0 NOCACHE NOCYCLE;

CREATE SEQUENCE TEX_IMAGE_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 0 NOCACHE NOCYCLE;

CREATE  TABLE ADDRESS ( 
	ID                   NUMBER(38)  DEFAULT ADDRESS_SEQ.NEXTVAL NOT NULL,
	OBJECTID             VARCHAR2(1000)   ,
	IDENTIFIER           VARCHAR2(1000)   ,
	IDENTIFIER_CODESPACE VARCHAR2(4000)   ,
	STREET               VARCHAR2(1000)   ,
	HOUSE_NUMBER         VARCHAR2(1000)   ,
	PO_BOX               VARCHAR2(1000)   ,
	ZIP_CODE             VARCHAR2(1000)   ,
	CITY                 VARCHAR2(1000)   ,
	STATE                VARCHAR2(1000)   ,
	COUNTRY              VARCHAR2(1000)   ,
	FREE_TEXT            JSON   ,
	MULTI_POINT          SDO_GEOMETRY   ,
	CONTENT              VARCHAR2(4000)   ,
	CONTENT_MIME_TYPE    VARCHAR2(1000)   ,
	CONSTRAINT ADDRESS_PK PRIMARY KEY ( ID ) 
 );

CREATE  TABLE ADE ( 
	ID                   NUMBER(10)  DEFAULT ADE_SEQ.NEXTVAL NOT NULL,
	NAME                 VARCHAR2(1000)   NOT NULL,
	DESCRIPTION          VARCHAR2(4000)   ,
	VERSION              VARCHAR2(100)   ,
	CONSTRAINT ADE_PK PRIMARY KEY ( ID ) 
 );

CREATE  TABLE CODELIST ( 
	ID                   NUMBER(38)  DEFAULT CODELIST_SEQ.NEXTVAL NOT NULL,
	CODELIST_TYPE        VARCHAR2(1000)   ,
	URL                  VARCHAR2(4000)   ,
	MIME_TYPE            VARCHAR2(1000)   ,
	CONSTRAINT CODELIST_PK PRIMARY KEY ( ID ) 
 );

CREATE INDEX CODELIST_CODELIST_TYPE_INX ON CODELIST ( CODELIST_TYPE );

CREATE  TABLE CODELIST_ENTRY ( 
	ID                   NUMBER(38)  DEFAULT CODELIST_ENTRY_SEQ.NEXTVAL NOT NULL,
	CODELIST_ID          NUMBER(38)   ,
	CODE                 VARCHAR2(1000)   ,
	DEFINITION           VARCHAR2(4000)   ,
	CONSTRAINT CODELIST_ENTRY_PK PRIMARY KEY ( ID ) 
 );

CREATE INDEX CODELIST_ENTRY_CODELIST_FKX ON CODELIST_ENTRY ( CODELIST_ID );

CREATE  TABLE DATABASE_SRS ( 
	SRID                 NUMBER(38)   NOT NULL,
	SRS_NAME             VARCHAR2(1000)   ,
	CONSTRAINT DATABASE_SRS_PK PRIMARY KEY ( SRID ) 
 );

CREATE  TABLE FEATURE ( 
	ID                   NUMBER(38)  DEFAULT FEATURE_SEQ.NEXTVAL NOT NULL,
	OBJECTCLASS_ID       NUMBER(10)   NOT NULL,
	OBJECTID             VARCHAR2(1000)   ,
	IDENTIFIER           VARCHAR2(1000)   ,
	IDENTIFIER_CODESPACE VARCHAR2(4000)   ,
	ENVELOPE             SDO_GEOMETRY   ,
	LAST_MODIFICATION_DATE TIMESTAMP WITH TIME ZONE   ,
	UPDATING_PERSON      VARCHAR2(1000)   ,
	REASON_FOR_UPDATE    VARCHAR2(4000)   ,
	LINEAGE              VARCHAR2(4000)   ,
	CREATION_DATE        TIMESTAMP WITH TIME ZONE   ,
	TERMINATION_DATE     TIMESTAMP WITH TIME ZONE   ,
	VALID_FROM           TIMESTAMP WITH TIME ZONE   ,
	VALID_TO             TIMESTAMP WITH TIME ZONE   ,
	CONSTRAINT FEATURE_PK PRIMARY KEY ( ID ) 
 );

CREATE INDEX FEATURE_OBJECTCLASS_INX ON FEATURE ( OBJECTCLASS_ID );

CREATE INDEX FEATURE_OBJECTID_INX ON FEATURE ( OBJECTID );

CREATE INDEX FEATURE_IDENTIFIER_INX ON FEATURE ( IDENTIFIER, IDENTIFIER_CODESPACE );

CREATE INDEX FEATURE_CREATION_DATE_INX ON FEATURE ( CREATION_DATE );

CREATE INDEX FEATURE_TERMINATION_DATE_INX ON FEATURE ( TERMINATION_DATE );

CREATE INDEX FEATURE_VALID_FROM_INX ON FEATURE ( VALID_FROM );

CREATE INDEX FEATURE_VALID_TO_INX ON FEATURE ( VALID_TO );

CREATE  TABLE GEOMETRY_DATA ( 
	ID                   NUMBER(38)  DEFAULT GEOMETRY_DATA_SEQ.NEXTVAL NOT NULL,
	GEOMETRY             SDO_GEOMETRY   ,
	IMPLICIT_GEOMETRY    SDO_GEOMETRY   ,
	GEOMETRY_PROPERTIES  JSON   ,
	FEATURE_ID           NUMBER(38)   ,
	CONSTRAINT GEOMETRY_DATA_PK PRIMARY KEY ( ID ) 
 );

CREATE INDEX GEOMETRY_DATA_FEATURE_FKX ON GEOMETRY_DATA ( FEATURE_ID );

CREATE  TABLE IMPLICIT_GEOMETRY ( 
	ID                   NUMBER(38)  DEFAULT IMPLICIT_GEOMETRY_SEQ.NEXTVAL NOT NULL,
	OBJECTID             VARCHAR2(1000)   ,
	MIME_TYPE            VARCHAR2(1000)   ,
	MIME_TYPE_CODESPACE  VARCHAR2(4000)   ,
	REFERENCE_TO_LIBRARY VARCHAR2(4000)   ,
	LIBRARY_OBJECT       BLOB   ,
	RELATIVE_GEOMETRY_ID NUMBER(38)   ,
	CONSTRAINT IMPLICIT_GEOMETRY_PK PRIMARY KEY ( ID ) 
 );

CREATE INDEX IMPLICIT_GEOMETRY_FKX ON IMPLICIT_GEOMETRY ( RELATIVE_GEOMETRY_ID );

CREATE INDEX IMPLICIT_GEOMETRY_OBJECTID_INX ON IMPLICIT_GEOMETRY ( OBJECTID );

CREATE  TABLE NAMESPACE ( 
	ID                   NUMBER(10)   NOT NULL,
	ALIAS                VARCHAR2(50)   ,
	NAMESPACE            VARCHAR2(1000)   ,
	ADE_ID               NUMBER(10)   ,
	CONSTRAINT NAMESPACE_PK PRIMARY KEY ( ID ) 
 );

CREATE  TABLE OBJECTCLASS ( 
	ID                   NUMBER(10)   NOT NULL,
	SUPERCLASS_ID        NUMBER(10)   ,
	CLASSNAME            VARCHAR2(255)   ,
	IS_ABSTRACT          NUMBER(1)   ,
	IS_TOPLEVEL          NUMBER(1)   ,
	ADE_ID               NUMBER(10)   ,
	NAMESPACE_ID         NUMBER(10)   ,
	SCHEMA               JSON   ,
	CONSTRAINT OBJECTCLASS_PK PRIMARY KEY ( ID ) 
 );

CREATE INDEX OBJECTCLASS_SUPERCLASS_FKX ON OBJECTCLASS ( SUPERCLASS_ID );

CREATE  TABLE TEX_IMAGE ( 
	ID                   NUMBER(38)  DEFAULT TEX_IMAGE_SEQ.NEXTVAL NOT NULL,
	IMAGE_URI            VARCHAR2(4000)   ,
	IMAGE_DATA           BLOB   ,
	MIME_TYPE            VARCHAR2(1000)   ,
	MIME_TYPE_CODESPACE  VARCHAR2(4000)   ,
	CONSTRAINT TEX_IMAGE_PK PRIMARY KEY ( ID ) 
 );

CREATE  TABLE APPEARANCE ( 
	ID                   NUMBER(38)  DEFAULT APPEARANCE_SEQ.NEXTVAL NOT NULL,
	OBJECTID             VARCHAR2(1000)   ,
	IDENTIFIER           VARCHAR2(1000)   ,
	IDENTIFIER_CODESPACE VARCHAR2(4000)   ,
	THEME                VARCHAR2(1000)   ,
	IS_GLOBAL            NUMBER(1)   ,
	FEATURE_ID           NUMBER(38)   ,
	IMPLICIT_GEOMETRY_ID NUMBER(38)   ,
	CONSTRAINT APPEARANCE_PK PRIMARY KEY ( ID ) 
 );

CREATE INDEX APPEARANCE_FEATURE_FKX ON APPEARANCE ( FEATURE_ID );

CREATE INDEX APPEARANCE_IMPLICIT_GEOM_FKX ON APPEARANCE ( IMPLICIT_GEOMETRY_ID );

CREATE INDEX APPEARANCE_THEME_INX ON APPEARANCE ( THEME );

CREATE  TABLE DATATYPE ( 
	ID                   NUMBER(10)   NOT NULL,
	SUPERTYPE_ID         NUMBER(10)   ,
	TYPENAME             VARCHAR2(255)   ,
	IS_ABSTRACT          NUMBER(1)   ,
	ADE_ID               NUMBER(10)   ,
	NAMESPACE_ID         NUMBER(10)   ,
	SCHEMA               JSON   ,
	CONSTRAINT DATATYPE_PK PRIMARY KEY ( ID ) 
 );

CREATE INDEX DATATYPE_SUPERTYPE_FKX ON DATATYPE ( SUPERTYPE_ID );

CREATE  TABLE PROPERTY ( 
	ID                   NUMBER(38)  DEFAULT PROPERTY_SEQ.NEXTVAL NOT NULL,
	FEATURE_ID           NUMBER(38)   ,
	PARENT_ID            NUMBER(38)   ,
	DATATYPE_ID          NUMBER(10)   NOT NULL,
	NAMESPACE_ID         NUMBER(10)   ,
	NAME                 VARCHAR2(1000)   ,
	VAL_INT              NUMBER(38)   ,
	VAL_DOUBLE           BINARY_DOUBLE   ,
	VAL_STRING           VARCHAR2(4000)   ,
	VAL_TIMESTAMP        TIMESTAMP WITH TIME ZONE   ,
	VAL_URI              VARCHAR2(4000)   ,
	VAL_CODESPACE        VARCHAR2(4000)   ,
	VAL_UOM              VARCHAR2(4000)   ,
	VAL_ARRAY            JSON   ,
	VAL_LOD              VARCHAR2(255)   ,
	VAL_GEOMETRY_ID      NUMBER(38)   ,
	VAL_IMPLICITGEOM_ID  NUMBER(38)   ,
	VAL_IMPLICITGEOM_REFPOINT SDO_GEOMETRY   ,
	VAL_APPEARANCE_ID    NUMBER(38)   ,
	VAL_ADDRESS_ID       NUMBER(38)   ,
	VAL_FEATURE_ID       NUMBER(38)   ,
	VAL_RELATION_TYPE    NUMBER(10)   ,
	VAL_CONTENT          VARCHAR2(4000)   ,
	VAL_CONTENT_MIME_TYPE VARCHAR2(1000)   ,
	CONSTRAINT PROPERTY_PK PRIMARY KEY ( ID ) 
 );

CREATE INDEX PROPERTY_FEATURE_FKX ON PROPERTY ( FEATURE_ID );

CREATE INDEX PROPERTY_PARENT_FKX ON PROPERTY ( PARENT_ID );

CREATE INDEX PROPERTY_NAMESPACE_INX ON PROPERTY ( NAMESPACE_ID );

CREATE INDEX PROPERTY_NAME_INX ON PROPERTY ( NAME );

CREATE INDEX PROPERTY_VAL_STRING_INX ON PROPERTY ( VAL_STRING );

CREATE INDEX PROPERTY_VAL_UOM_INX ON PROPERTY ( VAL_UOM );

CREATE INDEX PROPERTY_VAL_URI_INX ON PROPERTY ( VAL_URI );

CREATE INDEX PROPERTY_VAL_INT_INX ON PROPERTY ( VAL_INT );

CREATE INDEX PROPERTY_VAL_DOUBLE_INX ON PROPERTY ( VAL_DOUBLE );

CREATE INDEX PROPERTY_VAL_DATE_INX ON PROPERTY ( VAL_TIMESTAMP );

CREATE INDEX PROPERTY_VAL_FEATURE_FKX ON PROPERTY ( VAL_FEATURE_ID );

CREATE INDEX PROPERTY_VAL_GEOMETRY_FKX ON PROPERTY ( VAL_GEOMETRY_ID );

CREATE INDEX PROPERTY_VAL_IMPLICITGEOM_FKX ON PROPERTY ( VAL_IMPLICITGEOM_ID );

CREATE INDEX PROPERTY_VAL_APPEARANCE_FKX ON PROPERTY ( VAL_APPEARANCE_ID );

CREATE INDEX PROPERTY_VAL_RELATION_TYPE_INX ON PROPERTY ( VAL_RELATION_TYPE );

CREATE INDEX PROPERTY_VAL_ADDRESS_FKX ON PROPERTY ( VAL_ADDRESS_ID );

CREATE INDEX PROPERTY_VAL_LOD_INX ON PROPERTY ( VAL_LOD );

CREATE  TABLE SURFACE_DATA ( 
	ID                   NUMBER(38)  DEFAULT SURFACE_DATA_SEQ.NEXTVAL NOT NULL,
	OBJECTID             VARCHAR2(1000)   ,
	IDENTIFIER           VARCHAR2(1000)   ,
	IDENTIFIER_CODESPACE VARCHAR2(4000)   ,
	IS_FRONT             NUMBER(1)   ,
	OBJECTCLASS_ID       NUMBER(10)   NOT NULL,
	X3D_SHININESS        BINARY_DOUBLE   ,
	X3D_TRANSPARENCY     BINARY_DOUBLE   ,
	X3D_AMBIENT_INTENSITY BINARY_DOUBLE   ,
	X3D_SPECULAR_COLOR   VARCHAR2(20)   ,
	X3D_DIFFUSE_COLOR    VARCHAR2(20)   ,
	X3D_EMISSIVE_COLOR   VARCHAR2(20)   ,
	X3D_IS_SMOOTH        NUMBER(1)   ,
	TEX_IMAGE_ID         NUMBER(38)   ,
	TEX_TEXTURE_TYPE     VARCHAR2(255)   ,
	TEX_WRAP_MODE        VARCHAR2(255)   ,
	TEX_BORDER_COLOR     VARCHAR2(20)   ,
	GT_ORIENTATION       JSON   ,
	GT_REFERENCE_POINT   SDO_GEOMETRY   ,
	CONSTRAINT SURFACE_DATA_PK PRIMARY KEY ( ID ) 
 );

CREATE INDEX SURFACE_DATA_TEX_IMAGE_FKX ON SURFACE_DATA ( TEX_IMAGE_ID );

CREATE INDEX SURFACE_DATA_OBJCLASS_FKX ON SURFACE_DATA ( OBJECTCLASS_ID );

CREATE  TABLE SURFACE_DATA_MAPPING ( 
	SURFACE_DATA_ID      NUMBER(38)   NOT NULL,
	GEOMETRY_DATA_ID     NUMBER(38)   NOT NULL,
	MATERIAL_MAPPING     JSON   ,
	TEXTURE_MAPPING      JSON   ,
	WORLD_TO_TEXTURE_MAPPING JSON   ,
	GEOREFERENCED_TEXTURE_MAPPING JSON   ,
	CONSTRAINT SURFACE_DATA_MAPPING_PK PRIMARY KEY ( SURFACE_DATA_ID, GEOMETRY_DATA_ID ) 
 );

CREATE INDEX SURFACE_DATA_MAPPING_FKX1 ON SURFACE_DATA_MAPPING ( GEOMETRY_DATA_ID );

CREATE INDEX SURFACE_DATA_MAPPING_FKX2 ON SURFACE_DATA_MAPPING ( SURFACE_DATA_ID );

CREATE  TABLE APPEAR_TO_SURFACE_DATA ( 
	ID                   NUMBER(38)  DEFAULT APPEAR_TO_SURFACE_DATA_SEQ.NEXTVAL NOT NULL,
	APPEARANCE_ID        NUMBER(38)   NOT NULL,
	SURFACE_DATA_ID      NUMBER(38)   ,
	CONSTRAINT APPEAR_TO_SURFACE_DATA_PK PRIMARY KEY ( ID ) 
 );

CREATE INDEX APPEAR_TO_SURFACE_DATA_FKX1 ON APPEAR_TO_SURFACE_DATA ( SURFACE_DATA_ID );

CREATE INDEX APPEAR_TO_SURFACE_DATA_FKX2 ON APPEAR_TO_SURFACE_DATA ( APPEARANCE_ID );

ALTER TABLE APPEARANCE ADD CONSTRAINT APPEARANCE_FEATURE_FK FOREIGN KEY ( FEATURE_ID ) REFERENCES FEATURE( ID ) ON DELETE SET NULL;

ALTER TABLE APPEARANCE ADD CONSTRAINT APPEARANCE_IMPLICIT_GEOM_FK FOREIGN KEY ( IMPLICIT_GEOMETRY_ID ) REFERENCES IMPLICIT_GEOMETRY( ID ) ON DELETE CASCADE;

ALTER TABLE APPEAR_TO_SURFACE_DATA ADD CONSTRAINT APPEAR_TO_SURFACE_DATA_FK1 FOREIGN KEY ( SURFACE_DATA_ID ) REFERENCES SURFACE_DATA( ID ) ON DELETE CASCADE;

ALTER TABLE APPEAR_TO_SURFACE_DATA ADD CONSTRAINT APPEAR_TO_SURFACE_DATA_FK2 FOREIGN KEY ( APPEARANCE_ID ) REFERENCES APPEARANCE( ID ) ON DELETE CASCADE;

ALTER TABLE CODELIST_ENTRY ADD CONSTRAINT CODELIST_ENTRY_CODELIST_FK FOREIGN KEY ( CODELIST_ID ) REFERENCES CODELIST( ID ) ON DELETE CASCADE;

ALTER TABLE DATATYPE ADD CONSTRAINT DATATYPE_ADE_FK FOREIGN KEY ( ADE_ID ) REFERENCES ADE( ID ) ON DELETE CASCADE;

ALTER TABLE DATATYPE ADD CONSTRAINT DATATYPE_NAMESPACE_FK FOREIGN KEY ( NAMESPACE_ID ) REFERENCES NAMESPACE( ID ) ON DELETE CASCADE;

ALTER TABLE DATATYPE ADD CONSTRAINT DATATYPE_SUPERTYPE_FK FOREIGN KEY ( SUPERTYPE_ID ) REFERENCES DATATYPE( ID ) ON DELETE CASCADE;

ALTER TABLE GEOMETRY_DATA ADD CONSTRAINT GEOMETRY_DATA_FEATURE_FK FOREIGN KEY ( FEATURE_ID ) REFERENCES FEATURE( ID ) ON DELETE SET NULL;

ALTER TABLE IMPLICIT_GEOMETRY ADD CONSTRAINT IMPLICIT_GEOMETRY_FK FOREIGN KEY ( RELATIVE_GEOMETRY_ID ) REFERENCES GEOMETRY_DATA( ID ) ON DELETE CASCADE;

ALTER TABLE NAMESPACE ADD CONSTRAINT FK_NAMESPACE_ADE FOREIGN KEY ( ADE_ID ) REFERENCES ADE( ID ) ON DELETE CASCADE;

ALTER TABLE OBJECTCLASS ADD CONSTRAINT OBJECTCLASS_ADE_FK FOREIGN KEY ( ADE_ID ) REFERENCES ADE( ID ) ON DELETE CASCADE;

ALTER TABLE OBJECTCLASS ADD CONSTRAINT OBJECTCLASS_SUPERCLASS_FK FOREIGN KEY ( SUPERCLASS_ID ) REFERENCES OBJECTCLASS( ID ) ON DELETE CASCADE;

ALTER TABLE OBJECTCLASS ADD CONSTRAINT OBJECTCLASS_NAMESPACE_FK FOREIGN KEY ( NAMESPACE_ID ) REFERENCES NAMESPACE( ID ) ON DELETE CASCADE;

ALTER TABLE PROPERTY ADD CONSTRAINT PROPERTY_APPEARANCE_FK FOREIGN KEY ( VAL_APPEARANCE_ID ) REFERENCES APPEARANCE( ID ) ON DELETE CASCADE;

ALTER TABLE PROPERTY ADD CONSTRAINT PROPERTY_FEATURE_FK FOREIGN KEY ( FEATURE_ID ) REFERENCES FEATURE( ID );

ALTER TABLE PROPERTY ADD CONSTRAINT PROPERTY_VAL_FEATURE_FK FOREIGN KEY ( VAL_FEATURE_ID ) REFERENCES FEATURE( ID ) ON DELETE SET NULL;

ALTER TABLE PROPERTY ADD CONSTRAINT PROPERTY_VAL_IMPLICITGEOM_FK FOREIGN KEY ( VAL_IMPLICITGEOM_ID ) REFERENCES IMPLICIT_GEOMETRY( ID ) ON DELETE CASCADE;

ALTER TABLE PROPERTY ADD CONSTRAINT PROPERTY_PARENT_FK FOREIGN KEY ( PARENT_ID ) REFERENCES PROPERTY( ID ) ON DELETE SET NULL;

ALTER TABLE PROPERTY ADD CONSTRAINT PROPERTY_VAL_GEOMETRY_FK FOREIGN KEY ( VAL_GEOMETRY_ID ) REFERENCES GEOMETRY_DATA( ID ) ON DELETE CASCADE;

ALTER TABLE PROPERTY ADD CONSTRAINT PROPERTY_VAL_ADDRESS_FK FOREIGN KEY ( VAL_ADDRESS_ID ) REFERENCES ADDRESS( ID ) ON DELETE CASCADE;

ALTER TABLE SURFACE_DATA ADD CONSTRAINT SURFACE_DATA_TEX_IMAGE_FK FOREIGN KEY ( TEX_IMAGE_ID ) REFERENCES TEX_IMAGE( ID ) ON DELETE SET NULL;

ALTER TABLE SURFACE_DATA_MAPPING ADD CONSTRAINT SURFACE_DATA_MAPPING_FK1 FOREIGN KEY ( GEOMETRY_DATA_ID ) REFERENCES GEOMETRY_DATA( ID ) ON DELETE CASCADE;

ALTER TABLE SURFACE_DATA_MAPPING ADD CONSTRAINT SURFACE_DATA_MAPPING_FK2 FOREIGN KEY ( SURFACE_DATA_ID ) REFERENCES SURFACE_DATA( ID ) ON DELETE CASCADE;

