CREATE TABLE GROUP_TO_CITYOBJECT 
(
  CITYOBJECT_ID NUMBER NOT NULL 
, CITYOBJECTGROUP_ID NUMBER NOT NULL 
, ROLE VARCHAR2(256) 
, CONSTRAINT GROUP_TO_CITYOBJECT_PK PRIMARY KEY 
  (
    CITYOBJECT_ID 
  , CITYOBJECTGROUP_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX GROUP_TO_CITYOBJECT_PK ON GROUP_TO_CITYOBJECT (CITYOBJECT_ID ASC, CITYOBJECTGROUP_ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX GTCO_COGID_IDX ON GROUP_TO_CITYOBJECT (CITYOBJECTGROUP_ID ASC);

ALTER TABLE GROUP_TO_CITYOBJECT
ADD CONSTRAINT GROUP_TO_CITYOBJECT_FK FOREIGN KEY
(
  CITYOBJECT_ID 
)
REFERENCES CITYOBJECT
(
  ID 
)
ENABLE;

ALTER TABLE GROUP_TO_CITYOBJECT
ADD CONSTRAINT GROUP_TO_CITYOBJECT_FK1 FOREIGN KEY
(
  CITYOBJECTGROUP_ID 
)
REFERENCES CITYOBJECTGROUP
(
  ID 
)
ENABLE;
