CREATE TABLE OPENING_TO_THEM_SURFACE 
(
  OPENING_ID NUMBER NOT NULL 
, THEMATIC_SURFACE_ID NUMBER NOT NULL 
, CONSTRAINT OPENING_TO_THEM_SURFACE_PK PRIMARY KEY 
  (
    OPENING_ID 
  , THEMATIC_SURFACE_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OPENING_TO_THEM_SURFACE_PK ON OPENING_TO_THEM_SURFACE (OPENING_ID ASC, THEMATIC_SURFACE_ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

ALTER TABLE OPENING_TO_THEM_SURFACE
ADD CONSTRAINT OPENING_TO_THEMATIC_SURFACE_FK FOREIGN KEY
(
  OPENING_ID 
)
REFERENCES OPENING
(
  ID 
)
ENABLE;

ALTER TABLE OPENING_TO_THEM_SURFACE
ADD CONSTRAINT OPENING_TO_THEMATIC_SURFAC_FK1 FOREIGN KEY
(
  THEMATIC_SURFACE_ID 
)
REFERENCES THEMATIC_SURFACE
(
  ID 
)
ENABLE;
