CREATE TABLE SURFACE_GEOMETRY 
(
  ID NUMBER NOT NULL 
, GMLID VARCHAR2(256) 
, PARENT_ID NUMBER 
, ROOT_ID NUMBER 
, CITYOBJECT_ID NUMBER 
, IS_SOLID NUMBER(1, 0) 
, IS_COMPOSITE NUMBER(1, 0) 
, IS_TRIANGULATED NUMBER(1, 0) 
, IS_XLINK NUMBER(1, 0) 
, IS_REVERSE NUMBER(1, 0) 
, GEOMETRY MDSYS.SDO_GEOMETRY 
, SOLID_GEOMETRY MDSYS.SDO_GEOMETRY 
, CONSTRAINT SURFACE_GEOMETRY_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX SURFACE_GEOMETRY_PK ON SURFACE_GEOMETRY (ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX SURFACE_GEOMETRY_FKX ON SURFACE_GEOMETRY (PARENT_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX SURFACE_GEOMETRY_FKX1 ON SURFACE_GEOMETRY (ROOT_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX SURFACE_GEOMETRY_FKX2 ON SURFACE_GEOMETRY (CITYOBJECT_ID ASC);

CREATE UNIQUE INDEX SURFACE_GEOMETRY_INX ON SURFACE_GEOMETRY (GMLID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX SURFACE_GEOMETRY_SPX ON SURFACE_GEOMETRY (GEOMETRY) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE INDEX SURFACE_GEOMETRY_SPX2 ON SURFACE_GEOMETRY (SOLID_GEOMETRY) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

ALTER TABLE SURFACE_GEOMETRY
ADD CONSTRAINT SURFACE_GEOMETRY_CITYOBJECT_FK FOREIGN KEY
(
  CITYOBJECT_ID 
)
REFERENCES CITYOBJECT
(
  ID 
)
ENABLE;

ALTER TABLE SURFACE_GEOMETRY
ADD CONSTRAINT SURFACE_GEOMETRY_FK FOREIGN KEY
(
  PARENT_ID 
)
REFERENCES SURFACE_GEOMETRY
(
  ID 
)
ENABLE;

ALTER TABLE SURFACE_GEOMETRY
ADD CONSTRAINT SURFACE_GEOMETRY_FK1 FOREIGN KEY
(
  ROOT_ID 
)
REFERENCES SURFACE_GEOMETRY
(
  ID 
)
ENABLE;
