CREATE TABLE CITYOBJECT 
(
  ID NUMBER NOT NULL 
, CLASS_ID NUMBER NOT NULL 
, GMLID VARCHAR2(256) 
, NAME VARCHAR2(1000) 
, NAME_CODESPACE VARCHAR2(4000) 
, DESCRIPTION VARCHAR2(4000) 
, ENVELOPE MDSYS.SDO_GEOMETRY 
, CREATION_DATE TIMESTAMP NOT NULL 
, TERMINATION_DATE TIMESTAMP 
, LAST_MODIFICATION_DATE TIMESTAMP 
, UPDATING_PERSON VARCHAR2(256) 
, REASON_FOR_UPDATE VARCHAR2(4000) 
, LINEAGE VARCHAR2(256) 
, XML_SOURCE CLOB 
, RELATIVE_TO_TERRAIN VARCHAR2(256) 
, RELATIVE_TO_WATER VARCHAR2(256) 
, CONSTRAINT CITYOBJECT_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX CITYOBJECT_PK ON CITYOBJECT (ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
LOB (XML_SOURCE) STORE AS SYS_LOB0000115535C00019$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  RETENTION 
  NOCACHE 
  LOGGING 
  TABLESPACE "USERS" 
  STORAGE 
  ( 
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    BUFFER_POOL DEFAULT 
  )  
);

CREATE INDEX CITYOBJECT_FKX ON CITYOBJECT (CLASS_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
);

CREATE UNIQUE INDEX CITYOBJECT_INX ON CITYOBJECT (GMLID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX CITYOBJECT_SPX ON CITYOBJECT (ENVELOPE) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

ALTER TABLE CITYOBJECT
ADD CONSTRAINT CITYOBJECT_OBJECTCLASS_FK FOREIGN KEY
(
  CLASS_ID 
)
REFERENCES OBJECTCLASS
(
  ID 
)
ENABLE;
