CREATE TABLE CITYMODEL 
(
  ID NUMBER NOT NULL 
, GMLID VARCHAR2(256) 
, NAME VARCHAR2(1000) 
, NAME_CODESPACE VARCHAR2(4000) 
, DESCRIPTION VARCHAR2(4000) 
, ENVELOPE MDSYS.SDO_GEOMETRY 
, CREATION_DATE TIMESTAMP 
, TERMINATION_DATE TIMESTAMP 
, LAST_MODIFICATION_DATE TIMESTAMP 
, UPDATING_PERSON VARCHAR2(256) 
, REASON_FOR_UPDATE VARCHAR2(4000) 
, LINEAGE VARCHAR2(256) 
, CONSTRAINT CITYMODEL_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX CITYMODEL_PK ON CITYMODEL (ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
);

CREATE UNIQUE INDEX CITYMODEL_INX ON CITYMODEL (GMLID ASC);

CREATE INDEX CITYMODEL_SPX ON CITYMODEL (ENVELOPE) INDEXTYPE IS MDSYS.SPATIAL_INDEX;
