CREATE TABLE CITYOBJECT_MEMBER 
(
  CITYMODEL_ID NUMBER NOT NULL 
, CITYOBJECT_ID NUMBER NOT NULL 
, CONSTRAINT CITYOBJECT_MEMBER_PK PRIMARY KEY 
  (
    CITYMODEL_ID 
  , CITYOBJECT_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX CITYOBJECT_MEMBER_PK ON CITYOBJECT_MEMBER (CITYMODEL_ID ASC, CITYOBJECT_ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

ALTER TABLE CITYOBJECT_MEMBER
ADD CONSTRAINT CITYOBJECT_MEMBER_CITYMODEL_FK FOREIGN KEY
(
  CITYMODEL_ID 
)
REFERENCES CITYMODEL
(
  ID 
)
ENABLE;

ALTER TABLE CITYOBJECT_MEMBER
ADD CONSTRAINT CITYOBJECT_MEMBER_FK FOREIGN KEY
(
  CITYOBJECT_ID 
)
REFERENCES CITYOBJECT
(
  ID 
)
ENABLE;
