CREATE TABLE EXTERNAL_REFERENCE 
(
  ID NUMBER NOT NULL 
, INFOSYS VARCHAR2(4000) 
, NAME VARCHAR2(4000) 
, URI VARCHAR2(4000) 
, CITYOBJECT_ID NUMBER NOT NULL 
, CONSTRAINT EXTERNAL_REFERENCE_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX EXTERNAL_REFERENCE_PK ON EXTERNAL_REFERENCE (ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE INDEX EXTERNAL_REFERENCE_FKX ON EXTERNAL_REFERENCE (CITYOBJECT_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

ALTER TABLE EXTERNAL_REFERENCE
ADD CONSTRAINT EXTERNAL_REFERENCE_FK FOREIGN KEY
(
  CITYOBJECT_ID 
)
REFERENCES CITYOBJECT
(
  ID 
)
ENABLE;
