CREATE TABLE GENERALIZATION 
(
  CITYOBJECT_ID NUMBER NOT NULL 
, GENERALIZES_TO_ID NUMBER NOT NULL 
, CONSTRAINT GENERALIZATION_PK PRIMARY KEY 
  (
    CITYOBJECT_ID 
  , GENERALIZES_TO_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX GENERALIZATION_PK ON GENERALIZATION (CITYOBJECT_ID ASC, GENERALIZES_TO_ID ASC) 
      LOGGING 
      TABLESPACE "USERS" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

ALTER TABLE GENERALIZATION
ADD CONSTRAINT GENERALIZATION_FK FOREIGN KEY
(
  CITYOBJECT_ID 
)
REFERENCES CITYOBJECT
(
  ID 
)
ENABLE;

ALTER TABLE GENERALIZATION
ADD CONSTRAINT GENERALIZATION_FK1 FOREIGN KEY
(
  GENERALIZES_TO_ID 
)
REFERENCES CITYOBJECT
(
  ID 
)
ENABLE;
