DELETE FROM codelist_entry;

-- Building class --

INSERT INTO codelist_entry (ID, CODELIST_ID, CODE, DEFINITION)
VALUES
  (nextval('codelist_entry_seq'), 0, 1000, 'habitation'),
  (nextval('codelist_entry_seq'), 0, 1010, 'sanitation'),
  (nextval('codelist_entry_seq'), 0, 1020, 'administration'),
  (nextval('codelist_entry_seq'), 0, 1030, 'business, trade'),
  (nextval('codelist_entry_seq'), 0, 1040, 'catering'),
  (nextval('codelist_entry_seq'), 0, 1050, 'recreation'),
  (nextval('codelist_entry_seq'), 0, 1060, 'sport'),
  (nextval('codelist_entry_seq'), 0, 1070, 'culture'),
  (nextval('codelist_entry_seq'), 0, 1080, 'church institution'),
  (nextval('codelist_entry_seq'), 0, 1090, 'agriculture, forestry'),
  (nextval('codelist_entry_seq'), 0, 1100, 'schools, education, research'),
  (nextval('codelist_entry_seq'), 0, 1120, 'maintainence and waste management'),
  (nextval('codelist_entry_seq'), 0, 1130, 'healthcare'),
  (nextval('codelist_entry_seq'), 0, 1140, 'security'),
  (nextval('codelist_entry_seq'), 0, 1150, 'storage'),
  (nextval('codelist_entry_seq'), 0, 1160, 'industry'),
  (nextval('codelist_entry_seq'), 0, 1170, 'traffic'),
  (nextval('codelist_entry_seq'), 0, 1180, 'function');

-- Building function --

INSERT INTO codelist_entry (ID, CODELIST_ID, CODE, DEFINITION)
VALUES
  (nextval('codelist_entry_seq'), 1, 1000, 'residential building'),
  (nextval('codelist_entry_seq'), 1, 1010, 'tenement'),
  (nextval('codelist_entry_seq'), 1, 1020, 'hostel'),
  (nextval('codelist_entry_seq'), 1, 1030, 'residential- and administration building'),
  (nextval('codelist_entry_seq'), 1, 1040, 'residential- and office building'),
  (nextval('codelist_entry_seq'), 1, 1050, 'residential- and business building'),
  (nextval('codelist_entry_seq'), 1, 1060, 'residential- and plant building'),
  (nextval('codelist_entry_seq'), 1, 1070, 'agrarian- and forestry building'),
  (nextval('codelist_entry_seq'), 1, 1080, 'residential- and commercial building'),
  (nextval('codelist_entry_seq'), 1, 1090, 'forester''s lodge'),
  (nextval('codelist_entry_seq'), 1, 1100, 'holiday house'),
  (nextval('codelist_entry_seq'), 1, 1120, 'office building'),
  (nextval('codelist_entry_seq'), 1, 1130, 'credit institution'),
  (nextval('codelist_entry_seq'), 1, 1140, 'insurance'),
  (nextval('codelist_entry_seq'), 1, 1150, 'business building'),
  (nextval('codelist_entry_seq'), 1, 1160, 'department store'),
  (nextval('codelist_entry_seq'), 1, 1170, 'shopping centre'),
  (nextval('codelist_entry_seq'), 1, 1180, 'kiosk'),
  (nextval('codelist_entry_seq'), 1, 1190, 'pharmacy'),
  (nextval('codelist_entry_seq'), 1, 1200, 'pavilion'),
  (nextval('codelist_entry_seq'), 1, 1210, 'hotel'),
  (nextval('codelist_entry_seq'), 1, 1220, 'youth hostel'),
  (nextval('codelist_entry_seq'), 1, 1230, 'campsite building'),
  (nextval('codelist_entry_seq'), 1, 1240, 'restaurant'),
  (nextval('codelist_entry_seq'), 1, 1250, 'cantine'),
  (nextval('codelist_entry_seq'), 1, 1260, 'recreational site'),
  (nextval('codelist_entry_seq'), 1, 1270, 'function room'),
  (nextval('codelist_entry_seq'), 1, 1280, 'cinema'),
  (nextval('codelist_entry_seq'), 1, 1290, 'bowling alley'),
  (nextval('codelist_entry_seq'), 1, 1300, 'casino'),
  (nextval('codelist_entry_seq'), 1, 1310, 'industrial building'),
  (nextval('codelist_entry_seq'), 1, 1320, 'factory'),
  (nextval('codelist_entry_seq'), 1, 1330, 'workshop'),
  (nextval('codelist_entry_seq'), 1, 1340, 'petrol / gas station'),
  (nextval('codelist_entry_seq'), 1, 1350, 'washing plant'),
  (nextval('codelist_entry_seq'), 1, 1360, 'cold store'),
  (nextval('codelist_entry_seq'), 1, 1370, 'depot'),
  (nextval('codelist_entry_seq'), 1, 1380, 'building for research purposes'),
  (nextval('codelist_entry_seq'), 1, 1390, 'quarry'),
  (nextval('codelist_entry_seq'), 1, 1400, 'salt works'),
  (nextval('codelist_entry_seq'), 1, 1410, 'miscellaneous industrial building'),
  (nextval('codelist_entry_seq'), 1, 1420, 'mill'),
  (nextval('codelist_entry_seq'), 1, 1430, 'windmill'),
  (nextval('codelist_entry_seq'), 1, 1440, 'water mill'),
  (nextval('codelist_entry_seq'), 1, 1450, 'bucket elevator'),
  (nextval('codelist_entry_seq'), 1, 1460, 'weather station'),
  (nextval('codelist_entry_seq'), 1, 1470, 'traffic assets office'),
  (nextval('codelist_entry_seq'), 1, 1480, 'street maintenance'),
  (nextval('codelist_entry_seq'), 1, 1490, 'waiting hall'),
  (nextval('codelist_entry_seq'), 1, 1500, 'signal control box'),
  (nextval('codelist_entry_seq'), 1, 1510, 'engine shed'),
  (nextval('codelist_entry_seq'), 1, 1520, 'signal box or stop signal'),
  (nextval('codelist_entry_seq'), 1, 1530, 'plant building for air traffic'),
  (nextval('codelist_entry_seq'), 1, 1540, 'hangar'),
  (nextval('codelist_entry_seq'), 1, 1550, 'plant building for shipping'),
  (nextval('codelist_entry_seq'), 1, 1560, 'shipyard'),
  (nextval('codelist_entry_seq'), 1, 1570, 'dock'),
  (nextval('codelist_entry_seq'), 1, 1580, 'plant building for canal lock'),
  (nextval('codelist_entry_seq'), 1, 1590, 'boathouse'),
  (nextval('codelist_entry_seq'), 1, 1600, 'plant building for cablecar'),
  (nextval('codelist_entry_seq'), 1, 1610, 'multi-storey car park'),
  (nextval('codelist_entry_seq'), 1, 1620, 'parking level'),
  (nextval('codelist_entry_seq'), 1, 1630, 'garage'),
  (nextval('codelist_entry_seq'), 1, 1640, 'vehicle hall'),
  (nextval('codelist_entry_seq'), 1, 1650, 'underground garage'),
  (nextval('codelist_entry_seq'), 1, 1660, 'building for supply'),
  (nextval('codelist_entry_seq'), 1, 1670, 'waterworks'),
  (nextval('codelist_entry_seq'), 1, 1680, 'pump station'),
  (nextval('codelist_entry_seq'), 1, 1690, 'water basin'),
  (nextval('codelist_entry_seq'), 1, 1700, 'electric power station'),
  (nextval('codelist_entry_seq'), 1, 1710, 'transformer station'),
  (nextval('codelist_entry_seq'), 1, 1720, 'converter'),
  (nextval('codelist_entry_seq'), 1, 1730, 'reactor'),
  (nextval('codelist_entry_seq'), 1, 1740, 'turbine house'),
  (nextval('codelist_entry_seq'), 1, 1750, 'boiler house'),
  (nextval('codelist_entry_seq'), 1, 1760, 'building for telecommunications'),
  (nextval('codelist_entry_seq'), 1, 1770, 'gas works'),
  (nextval('codelist_entry_seq'), 1, 1780, 'heat plant'),
  (nextval('codelist_entry_seq'), 1, 1790, 'pumping station'),
  (nextval('codelist_entry_seq'), 1, 1800, 'building for disposal'),
  (nextval('codelist_entry_seq'), 1, 1810, 'building for effluent disposal'),
  (nextval('codelist_entry_seq'), 1, 1820, 'building for filter plant'),
  (nextval('codelist_entry_seq'), 1, 1830, 'toilet'),
  (nextval('codelist_entry_seq'), 1, 1840, 'rubbish bunker'),
  (nextval('codelist_entry_seq'), 1, 1850, 'building for rubbish incineration'),
  (nextval('codelist_entry_seq'), 1, 1860, 'building for rubbish disposal'),
  (nextval('codelist_entry_seq'), 1, 1870, 'building for agrarian and forestry'),
  (nextval('codelist_entry_seq'), 1, 1880, 'barn'),
  (nextval('codelist_entry_seq'), 1, 1890, 'stall'),
  (nextval('codelist_entry_seq'), 1, 1900, 'equestrian hall'),
  (nextval('codelist_entry_seq'), 1, 1910, 'alpine cabin'),
  (nextval('codelist_entry_seq'), 1, 1920, 'hunting lodge'),
  (nextval('codelist_entry_seq'), 1, 1930, 'arboretum'),
  (nextval('codelist_entry_seq'), 1, 1940, 'glass house'),
  (nextval('codelist_entry_seq'), 1, 1950, 'moveable glass house'),
  (nextval('codelist_entry_seq'), 1, 1960, 'public building'),
  (nextval('codelist_entry_seq'), 1, 1970, 'administration building'),
  (nextval('codelist_entry_seq'), 1, 1980, 'parliament'),
  (nextval('codelist_entry_seq'), 1, 1990, 'guildhall'),
  (nextval('codelist_entry_seq'), 1, 2000, 'post office'),
  (nextval('codelist_entry_seq'), 1, 2010, 'customs office'),
  (nextval('codelist_entry_seq'), 1, 2020, 'court'),
  (nextval('codelist_entry_seq'), 1, 2030, 'embassy or consulate'),
  (nextval('codelist_entry_seq'), 1, 2040, 'district administration'),
  (nextval('codelist_entry_seq'), 1, 2050, 'district government'),
  (nextval('codelist_entry_seq'), 1, 2060, 'tax office'),
  (nextval('codelist_entry_seq'), 1, 2070, 'building for education and research'),
  (nextval('codelist_entry_seq'), 1, 2080, 'comprehensive school'),
  (nextval('codelist_entry_seq'), 1, 2090, 'vocational school'),
  (nextval('codelist_entry_seq'), 1, 2100, 'college or university'),
  (nextval('codelist_entry_seq'), 1, 2110, 'research establishment'),
  (nextval('codelist_entry_seq'), 1, 2120, 'building for cultural purposes'),
  (nextval('codelist_entry_seq'), 1, 2130, 'castle'),
  (nextval('codelist_entry_seq'), 1, 2140, 'theatre or opera'),
  (nextval('codelist_entry_seq'), 1, 2150, 'concert building'),
  (nextval('codelist_entry_seq'), 1, 2160, 'museum'),
  (nextval('codelist_entry_seq'), 1, 2170, 'broadcasting building'),
  (nextval('codelist_entry_seq'), 1, 2180, 'activity building'),
  (nextval('codelist_entry_seq'), 1, 2190, 'library'),
  (nextval('codelist_entry_seq'), 1, 2200, 'fort'),
  (nextval('codelist_entry_seq'), 1, 2210, 'religious building'),
  (nextval('codelist_entry_seq'), 1, 2220, 'church'),
  (nextval('codelist_entry_seq'), 1, 2230, 'synagogue'),
  (nextval('codelist_entry_seq'), 1, 2240, 'chapel'),
  (nextval('codelist_entry_seq'), 1, 2250, 'community center'),
  (nextval('codelist_entry_seq'), 1, 2260, 'place of worship'),
  (nextval('codelist_entry_seq'), 1, 2270, 'mosque'),
  (nextval('codelist_entry_seq'), 1, 2280, 'temple'),
  (nextval('codelist_entry_seq'), 1, 2290, 'convent'),
  (nextval('codelist_entry_seq'), 1, 2300, 'building for health care'),
  (nextval('codelist_entry_seq'), 1, 2310, 'hospital'),
  (nextval('codelist_entry_seq'), 1, 2320, 'healing centre or care home'),
  (nextval('codelist_entry_seq'), 1, 2330, 'health centre or outpatients clinic'),
  (nextval('codelist_entry_seq'), 1, 2340, 'building for social purposes'),
  (nextval('codelist_entry_seq'), 1, 2350, 'youth centre'),
  (nextval('codelist_entry_seq'), 1, 2360, 'seniors centre'),
  (nextval('codelist_entry_seq'), 1, 2370, 'homeless shelter'),
  (nextval('codelist_entry_seq'), 1, 2380, 'kindergarten or nursery'),
  (nextval('codelist_entry_seq'), 1, 2390, 'asylum seekers home'),
  (nextval('codelist_entry_seq'), 1, 2400, 'police station'),
  (nextval('codelist_entry_seq'), 1, 2410, 'fire station'),
  (nextval('codelist_entry_seq'), 1, 2420, 'barracks'),
  (nextval('codelist_entry_seq'), 1, 2430, 'bunker'),
  (nextval('codelist_entry_seq'), 1, 2440, 'penitentiary or prison'),
  (nextval('codelist_entry_seq'), 1, 2450, 'cemetery building'),
  (nextval('codelist_entry_seq'), 1, 2460, 'funeral parlor'),
  (nextval('codelist_entry_seq'), 1, 2470, 'crematorium'),
  (nextval('codelist_entry_seq'), 1, 2480, 'train station'),
  (nextval('codelist_entry_seq'), 1, 2490, 'airport building'),
  (nextval('codelist_entry_seq'), 1, 2500, 'building for underground station'),
  (nextval('codelist_entry_seq'), 1, 2510, 'building for tramway'),
  (nextval('codelist_entry_seq'), 1, 2520, 'building for bus station'),
  (nextval('codelist_entry_seq'), 1, 2530, 'shipping terminal'),
  (nextval('codelist_entry_seq'), 1, 2540, 'building for recuperation purposes'),
  (nextval('codelist_entry_seq'), 1, 2550, 'building for sport purposes'),
  (nextval('codelist_entry_seq'), 1, 2560, 'sports hall'),
  (nextval('codelist_entry_seq'), 1, 2570, 'building for sports field'),
  (nextval('codelist_entry_seq'), 1, 2580, 'swimming baths'),
  (nextval('codelist_entry_seq'), 1, 2590, 'indoor swimming pool'),
  (nextval('codelist_entry_seq'), 1, 2600, 'sanatorium'),
  (nextval('codelist_entry_seq'), 1, 2610, 'zoo building'),
  (nextval('codelist_entry_seq'), 1, 2620, 'zoo green house'),
  (nextval('codelist_entry_seq'), 1, 2630, 'botanical show house'),
  (nextval('codelist_entry_seq'), 1, 2640, 'bothy'),
  (nextval('codelist_entry_seq'), 1, 2650, 'tourist information centre'),
  (nextval('codelist_entry_seq'), 1, 2700, 'others');

-- Building usage --

INSERT INTO codelist_entry (ID, CODELIST_ID, CODE, DEFINITION)
VALUES
  (nextval('codelist_entry_seq'), 2, 1000, 'residential building'),
  (nextval('codelist_entry_seq'), 2, 1010, 'tenement'),
  (nextval('codelist_entry_seq'), 2, 1020, 'hostel'),
  (nextval('codelist_entry_seq'), 2, 1030, 'residential- and administration building'),
  (nextval('codelist_entry_seq'), 2, 1040, 'residential- and office building'),
  (nextval('codelist_entry_seq'), 2, 1050, 'residential- and business building'),
  (nextval('codelist_entry_seq'), 2, 1060, 'residential- and plant building'),
  (nextval('codelist_entry_seq'), 2, 1070, 'agrarian- and forestry building'),
  (nextval('codelist_entry_seq'), 2, 1080, 'residential- and commercial building'),
  (nextval('codelist_entry_seq'), 2, 1090, 'forester''s lodge'),
  (nextval('codelist_entry_seq'), 2, 1100, 'holiday house'),
  (nextval('codelist_entry_seq'), 2, 1120, 'office building'),
  (nextval('codelist_entry_seq'), 2, 1130, 'credit institution'),
  (nextval('codelist_entry_seq'), 2, 1140, 'insurance'),
  (nextval('codelist_entry_seq'), 2, 1150, 'business building'),
  (nextval('codelist_entry_seq'), 2, 1160, 'department store'),
  (nextval('codelist_entry_seq'), 2, 1170, 'shopping centre'),
  (nextval('codelist_entry_seq'), 2, 1180, 'kiosk'),
  (nextval('codelist_entry_seq'), 2, 1190, 'pharmacy'),
  (nextval('codelist_entry_seq'), 2, 1200, 'pavilion'),
  (nextval('codelist_entry_seq'), 2, 1210, 'hotel'),
  (nextval('codelist_entry_seq'), 2, 1220, 'youth hostel'),
  (nextval('codelist_entry_seq'), 2, 1230, 'campsite building'),
  (nextval('codelist_entry_seq'), 2, 1240, 'restaurant'),
  (nextval('codelist_entry_seq'), 2, 1250, 'cantine'),
  (nextval('codelist_entry_seq'), 2, 1260, 'recreational site'),
  (nextval('codelist_entry_seq'), 2, 1270, 'function room'),
  (nextval('codelist_entry_seq'), 2, 1280, 'cinema'),
  (nextval('codelist_entry_seq'), 2, 1290, 'bowling alley'),
  (nextval('codelist_entry_seq'), 2, 1300, 'casino'),
  (nextval('codelist_entry_seq'), 2, 1310, 'industrial building'),
  (nextval('codelist_entry_seq'), 2, 1320, 'factory'),
  (nextval('codelist_entry_seq'), 2, 1330, 'workshop'),
  (nextval('codelist_entry_seq'), 2, 1340, 'petrol / gas station'),
  (nextval('codelist_entry_seq'), 2, 1350, 'washing plant'),
  (nextval('codelist_entry_seq'), 2, 1360, 'cold store'),
  (nextval('codelist_entry_seq'), 2, 1370, 'depot'),
  (nextval('codelist_entry_seq'), 2, 1380, 'building for research purposes'),
  (nextval('codelist_entry_seq'), 2, 1390, 'quarry'),
  (nextval('codelist_entry_seq'), 2, 1400, 'salt works'),
  (nextval('codelist_entry_seq'), 2, 1410, 'miscellaneous industrial building'),
  (nextval('codelist_entry_seq'), 2, 1420, 'mill'),
  (nextval('codelist_entry_seq'), 2, 1430, 'windmill'),
  (nextval('codelist_entry_seq'), 2, 1440, 'water mill'),
  (nextval('codelist_entry_seq'), 2, 1450, 'bucket elevator'),
  (nextval('codelist_entry_seq'), 2, 1460, 'weather station'),
  (nextval('codelist_entry_seq'), 2, 1470, 'traffic assets office'),
  (nextval('codelist_entry_seq'), 2, 1480, 'street maintenance'),
  (nextval('codelist_entry_seq'), 2, 1490, 'waiting hall'),
  (nextval('codelist_entry_seq'), 2, 1500, 'signal control box'),
  (nextval('codelist_entry_seq'), 2, 1510, 'engine shed'),
  (nextval('codelist_entry_seq'), 2, 1520, 'signal box or stop signal'),
  (nextval('codelist_entry_seq'), 2, 1530, 'plant building for air traffic'),
  (nextval('codelist_entry_seq'), 2, 1540, 'hangar'),
  (nextval('codelist_entry_seq'), 2, 1550, 'plant building for shipping'),
  (nextval('codelist_entry_seq'), 2, 1560, 'shipyard'),
  (nextval('codelist_entry_seq'), 2, 1570, 'dock'),
  (nextval('codelist_entry_seq'), 2, 1580, 'plant building for canal lock'),
  (nextval('codelist_entry_seq'), 2, 1590, 'boathouse'),
  (nextval('codelist_entry_seq'), 2, 1600, 'plant building for cablecar'),
  (nextval('codelist_entry_seq'), 2, 1610, 'multi-storey car park'),
  (nextval('codelist_entry_seq'), 2, 1620, 'parking level'),
  (nextval('codelist_entry_seq'), 2, 1630, 'garage'),
  (nextval('codelist_entry_seq'), 2, 1640, 'vehicle hall'),
  (nextval('codelist_entry_seq'), 2, 1650, 'underground garage'),
  (nextval('codelist_entry_seq'), 2, 1660, 'building for supply'),
  (nextval('codelist_entry_seq'), 2, 1670, 'waterworks'),
  (nextval('codelist_entry_seq'), 2, 1680, 'pump station'),
  (nextval('codelist_entry_seq'), 2, 1690, 'water basin'),
  (nextval('codelist_entry_seq'), 2, 1700, 'electric power station'),
  (nextval('codelist_entry_seq'), 2, 1710, 'transformer station'),
  (nextval('codelist_entry_seq'), 2, 1720, 'converter'),
  (nextval('codelist_entry_seq'), 2, 1730, 'reactor'),
  (nextval('codelist_entry_seq'), 2, 1740, 'turbine house'),
  (nextval('codelist_entry_seq'), 2, 1750, 'boiler house'),
  (nextval('codelist_entry_seq'), 2, 1760, 'building for telecommunications'),
  (nextval('codelist_entry_seq'), 2, 1770, 'gas works'),
  (nextval('codelist_entry_seq'), 2, 1780, 'heat plant'),
  (nextval('codelist_entry_seq'), 2, 1790, 'pumping station'),
  (nextval('codelist_entry_seq'), 2, 1800, 'building for disposal'),
  (nextval('codelist_entry_seq'), 2, 1810, 'building for effluent disposal'),
  (nextval('codelist_entry_seq'), 2, 1820, 'building for filter plant'),
  (nextval('codelist_entry_seq'), 2, 1830, 'toilet'),
  (nextval('codelist_entry_seq'), 2, 1840, 'rubbish bunker'),
  (nextval('codelist_entry_seq'), 2, 1850, 'building for rubbish incineration'),
  (nextval('codelist_entry_seq'), 2, 1860, 'building for rubbish disposal'),
  (nextval('codelist_entry_seq'), 2, 1870, 'building for agrarian and forestry'),
  (nextval('codelist_entry_seq'), 2, 1880, 'barn'),
  (nextval('codelist_entry_seq'), 2, 1890, 'stall'),
  (nextval('codelist_entry_seq'), 2, 1900, 'equestrian hall'),
  (nextval('codelist_entry_seq'), 2, 1910, 'alpine cabin'),
  (nextval('codelist_entry_seq'), 2, 1920, 'hunting lodge'),
  (nextval('codelist_entry_seq'), 2, 1930, 'arboretum'),
  (nextval('codelist_entry_seq'), 2, 1940, 'glass house'),
  (nextval('codelist_entry_seq'), 2, 1950, 'moveable glass house'),
  (nextval('codelist_entry_seq'), 2, 1960, 'public building'),
  (nextval('codelist_entry_seq'), 2, 1970, 'administration building'),
  (nextval('codelist_entry_seq'), 2, 1980, 'parliament'),
  (nextval('codelist_entry_seq'), 2, 1990, 'guildhall'),
  (nextval('codelist_entry_seq'), 2, 2000, 'post office'),
  (nextval('codelist_entry_seq'), 2, 2010, 'customs office'),
  (nextval('codelist_entry_seq'), 2, 2020, 'court'),
  (nextval('codelist_entry_seq'), 2, 2030, 'embassy or consulate'),
  (nextval('codelist_entry_seq'), 2, 2040, 'district administration'),
  (nextval('codelist_entry_seq'), 2, 2050, 'district government'),
  (nextval('codelist_entry_seq'), 2, 2060, 'tax office'),
  (nextval('codelist_entry_seq'), 2, 2070, 'building for education and research'),
  (nextval('codelist_entry_seq'), 2, 2080, 'comprehensive school'),
  (nextval('codelist_entry_seq'), 2, 2090, 'vocational school'),
  (nextval('codelist_entry_seq'), 2, 2100, 'college or university'),
  (nextval('codelist_entry_seq'), 2, 2110, 'research establishment'),
  (nextval('codelist_entry_seq'), 2, 2120, 'building for cultural purposes'),
  (nextval('codelist_entry_seq'), 2, 2130, 'castle'),
  (nextval('codelist_entry_seq'), 2, 2140, 'theatre or opera'),
  (nextval('codelist_entry_seq'), 2, 2150, 'concert building'),
  (nextval('codelist_entry_seq'), 2, 2160, 'museum'),
  (nextval('codelist_entry_seq'), 2, 2170, 'broadcasting building'),
  (nextval('codelist_entry_seq'), 2, 2180, 'activity building'),
  (nextval('codelist_entry_seq'), 2, 2190, 'library'),
  (nextval('codelist_entry_seq'), 2, 2200, 'fort'),
  (nextval('codelist_entry_seq'), 2, 2210, 'religious building'),
  (nextval('codelist_entry_seq'), 2, 2220, 'church'),
  (nextval('codelist_entry_seq'), 2, 2230, 'synagogue'),
  (nextval('codelist_entry_seq'), 2, 2240, 'chapel'),
  (nextval('codelist_entry_seq'), 2, 2250, 'community center'),
  (nextval('codelist_entry_seq'), 2, 2260, 'place of worship'),
  (nextval('codelist_entry_seq'), 2, 2270, 'mosque'),
  (nextval('codelist_entry_seq'), 2, 2280, 'temple'),
  (nextval('codelist_entry_seq'), 2, 2290, 'convent'),
  (nextval('codelist_entry_seq'), 2, 2300, 'building for health care'),
  (nextval('codelist_entry_seq'), 2, 2310, 'hospital'),
  (nextval('codelist_entry_seq'), 2, 2320, 'healing centre or care home'),
  (nextval('codelist_entry_seq'), 2, 2330, 'health centre or outpatients clinic'),
  (nextval('codelist_entry_seq'), 2, 2340, 'building for social purposes'),
  (nextval('codelist_entry_seq'), 2, 2350, 'youth centre'),
  (nextval('codelist_entry_seq'), 2, 2360, 'seniors centre'),
  (nextval('codelist_entry_seq'), 2, 2370, 'homeless shelter'),
  (nextval('codelist_entry_seq'), 2, 2380, 'kindergarten or nursery'),
  (nextval('codelist_entry_seq'), 2, 2390, 'asylum seekers home'),
  (nextval('codelist_entry_seq'), 2, 2400, 'police station'),
  (nextval('codelist_entry_seq'), 2, 2410, 'fire station'),
  (nextval('codelist_entry_seq'), 2, 2420, 'barracks'),
  (nextval('codelist_entry_seq'), 2, 2430, 'bunker'),
  (nextval('codelist_entry_seq'), 2, 2440, 'penitentiary or prison'),
  (nextval('codelist_entry_seq'), 2, 2450, 'cemetery building'),
  (nextval('codelist_entry_seq'), 2, 2460, 'funeral parlor'),
  (nextval('codelist_entry_seq'), 2, 2470, 'crematorium'),
  (nextval('codelist_entry_seq'), 2, 2480, 'train station'),
  (nextval('codelist_entry_seq'), 2, 2490, 'airport building'),
  (nextval('codelist_entry_seq'), 2, 2500, 'building for underground station'),
  (nextval('codelist_entry_seq'), 2, 2510, 'building for tramway'),
  (nextval('codelist_entry_seq'), 2, 2520, 'building for bus station'),
  (nextval('codelist_entry_seq'), 2, 2530, 'shipping terminal'),
  (nextval('codelist_entry_seq'), 2, 2540, 'building for recuperation purposes'),
  (nextval('codelist_entry_seq'), 2, 2550, 'building for sport purposes'),
  (nextval('codelist_entry_seq'), 2, 2560, 'sports hall'),
  (nextval('codelist_entry_seq'), 2, 2570, 'building for sports field'),
  (nextval('codelist_entry_seq'), 2, 2580, 'swimming baths'),
  (nextval('codelist_entry_seq'), 2, 2590, 'indoor swimming pool'),
  (nextval('codelist_entry_seq'), 2, 2600, 'sanatorium'),
  (nextval('codelist_entry_seq'), 2, 2610, 'zoo building'),
  (nextval('codelist_entry_seq'), 2, 2620, 'zoo green house'),
  (nextval('codelist_entry_seq'), 2, 2630, 'botanical show house'),
  (nextval('codelist_entry_seq'), 2, 2640, 'bothy'),
  (nextval('codelist_entry_seq'), 2, 2650, 'tourist information centre'),
  (nextval('codelist_entry_seq'), 2, 2700, 'others');