name: build-3dcitydb-scripts

on: [push, pull_request]

jobs:
  validate-schema-mapping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - name: Install Ajv JSON schema validator
        run: npm install -g ajv-cli
      - name: Validate schema mapping
        run: ajv test --valid --spec=draft2020 --strict=true
          -s json-schema/schema-mapping.schema.json
          -d schema-mapping/**/*.json
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-disabled: true
      - name: Grant execute permission to Gradle
        run: chmod +x ./gradlew
      - name: Execute Gradle build
        run: ./gradlew installDist