name: psql-docker-build-push-edge

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        baseimage-tag: ['16-3.4']   # base image tags for 'edge' image
        variant: ['', '-alpine']    # image variants: '' = debian

    steps:
    -
      name: Parse short sha
      uses: benjlevesque/short-sha@v2.2
      id: short-sha
    -
      name: Checkout repo
      uses: actions/checkout@v4
    -
      name: Docker login
      id: docker_login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    -
      name: Build and push image
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: ./postgresql
        push: true
        tags: bwibo/3dcitydb-pg:edge${{ matrix.variant }}
        build-args: |
          BASEIMAGE_TAG=${{ matrix.baseimage-tag }}${{ matrix.variant }}
          CITYDB_VERSION=${{ steps.short-sha.outputs.sha }}
    -
      name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
    -
      name: Inspect image
      run: docker inspect bwibo/3dcitydb-pg:edge${{ matrix.variant }}
