name: psql-docker-build-push-release-latest

on:
  workflow_dispatch:
  release:
    types: [released, edited]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        baseimage-tag: ['15-3.4']
        variant: ['', '-alpine']    # image variants: '' = debian

    steps:
    -
      name: Checkout repo
      uses: actions/checkout@v4
    -
      name: Get release version without v
      id: release_version
      uses: battila7/get-version-action@v2
    -
      name: Docker login
      id: docker_login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    -
      name: Build and push image
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: ./postgresql
        push: true
        tags: 3dcitydb/3dcitydb-pg:latest${{ matrix.variant }}
        build-args: |
          BASEIMAGE_TAG=${{ matrix.baseimage-tag }}${{ matrix.variant }}
          CITYDB_VERSION=${{ steps.release_version.outputs.version }}
    -
      name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
    -
      name: Inspect image
      run: docker inspect 3dcitydb/3dcitydb-pg:latest${{ matrix.variant }}
